<div class="div_line"  data-info=({id:28897,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:28898,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: e_msoft.h 577 2007-06-30 15:30:16Z dhiebert $
</div></div></div><div class="div_line"  data-info=({id:28899,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:28900,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 2002-2003, Darren Hiebert
</div></div></div><div class="div_line"  data-info=({id:28901,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:28902,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:28903,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License.
</div></div></div><div class="div_line"  data-info=({id:28904,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:28905,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Configures ctags for Microsoft environment.
</div></div></div><div class="div_line"  data-info=({id:28906,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:28907,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/e_msoft.h#line12' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>E_MSOFT_H</a>
</div></div></div><div class="div_line"  data-info=({id:28908,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>E_MSOFT_H</span>
</div></div></div><div class="div_line"  data-info=({id:28909,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28910,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  MS-DOS/Windows doesn't allow manipulation of standard error,
</div></div></div><div class="div_line"  data-info=({id:28911,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  so we send it to stdout instead.
</div></div></div><div class="div_line"  data-info=({id:28912,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:28913,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>errout</span>  stdout
</div></div></div><div class="div_line"  data-info=({id:28914,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28915,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>CASE_INSENSITIVE_FILENAMES</span> 1
</div></div></div><div class="div_line"  data-info=({id:28916,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>MANUAL_GLOBBING</span> 1
</div></div></div><div class="div_line"  data-info=({id:28917,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>MSDOS_STYLE_PATH</span> 1
</div></div></div><div class="div_line"  data-info=({id:28918,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_DOS_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28919,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FCNTL_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28920,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_IO_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28921,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STDLIB_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28922,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_STAT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28923,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_TYPES_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28924,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_TIME_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28925,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_CLOCK</span> 1
</div></div></div><div class="div_line"  data-info=({id:28926,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_CHSIZE</span> 1
</div></div></div><div class="div_line"  data-info=({id:28927,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FGETPOS</span> 1
</div></div></div><div class="div_line"  data-info=({id:28928,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRICMP</span> 1
</div></div></div><div class="div_line"  data-info=({id:28929,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRNICMP</span> 1
</div></div></div><div class="div_line"  data-info=({id:28930,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRSTR</span> 1
</div></div></div><div class="div_line"  data-info=({id:28931,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRERROR</span> 1
</div></div></div><div class="div_line"  data-info=({id:28932,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FINDNEXT</span> 1
</div></div></div><div class="div_line"  data-info=({id:28933,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_TEMPNAM</span> 1
</div></div></div><div class="div_line"  data-info=({id:28934,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>tempnam</span>(dir,pfx) _tempnam(dir,pfx)
</div></div></div><div class="div_line"  data-info=({id:28935,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>TMPDIR</span> "\\"
</div></div></div><div class="div_line"  data-info=({id:28936,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28937,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __BORLANDC__
</div></div></div><div class="div_line"  data-info=({id:28938,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28939,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_DIR_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28940,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_DIRENT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28941,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_FINDFIRST</span> 1
</div></div></div><div class="div_line"  data-info=({id:28942,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28943,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#elif defined (_MSC_VER)
</div></div></div><div class="div_line"  data-info=({id:28944,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28945,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE__FINDFIRST</span> 1
</div></div></div><div class="div_line"  data-info=({id:28946,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_DIRECT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28947,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28948,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># if _MSC_VER &gt;= 1300
</div></div></div><div class="div_line"  data-info=({id:28949,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>findfirst_t</span> intptr_t  /* Visual Studio 7 */
</div></div></div><div class="div_line"  data-info=({id:28950,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># else
</div></div></div><div class="div_line"  data-info=({id:28951,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>findfirst_t</span> long      /* Visual Studio 6 or earlier */
</div></div></div><div class="div_line"  data-info=({id:28952,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># endif
</div></div></div><div class="div_line"  data-info=({id:28953,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28954,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#elif defined (__MINGW32__)
</div></div></div><div class="div_line"  data-info=({id:28955,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28956,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># include &lt;<span class='ctd include'>_mingw.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:28957,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># if defined (__MSVCRT__) && __MINGW32_MAJOR_VERSION == 1 && __MINGW32_MINOR_VERSION &lt; 2
</div></div></div><div class="div_line"  data-info=({id:28958,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Work-around for broken implementation of fgetpos()/fsetpos() on Mingw32 */
</div></div></div><div class="div_line"  data-info=({id:28959,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  undef <a href='ctags/e_amiga.h#line19' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:8})'>HAVE_FGETPOS</a>
</div></div></div><div class="div_line"  data-info=({id:28960,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>NEED_PROTO_FGETPOS</span> 1
</div></div></div><div class="div_line"  data-info=({id:28961,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># endif
</div></div></div><div class="div_line"  data-info=({id:28962,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_DIR_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28963,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE_DIRENT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:28964,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>HAVE__FINDFIRST</span> 1
</div></div></div><div class="div_line"  data-info=({id:28965,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>findfirst_t</span> long
</div></div></div><div class="div_line"  data-info=({id:28966,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>ffblk</span> _finddata_t
</div></div></div><div class="div_line"  data-info=({id:28967,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>FA_DIREC</span> _A_SUBDIR
</div></div></div><div class="div_line"  data-info=({id:28968,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>ff_name</span> name
</div></div></div><div class="div_line"  data-info=({id:28969,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28970,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:28971,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:28972,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><script>var local_symbol_set='([{name:"CASE_INSENSITIVE_FILENAMES",ln:19},{name:"E_MSOFT_H",ln:12},{name:"FA_DIREC",ln:71},{name:"HAVE_CHSIZE",ln:30},{name:"HAVE_CLOCK",ln:29},{name:"HAVE_DIRECT_H",ln:50},{name:"HAVE_DIRENT_H",ln:44},{name:"HAVE_DIRENT_H",ln:67},{name:"HAVE_DIR_H",ln:43},{name:"HAVE_DIR_H",ln:66},{name:"HAVE_DOS_H",ln:22},{name:"HAVE_FCNTL_H",ln:23},{name:"HAVE_FGETPOS",ln:31},{name:"HAVE_FGETPOS",ln:63},{name:"HAVE_FINDFIRST",ln:45},{name:"HAVE_FINDNEXT",ln:36},{name:"HAVE_IO_H",ln:24},{name:"HAVE_STDLIB_H",ln:25},{name:"HAVE_STRERROR",ln:35},{name:"HAVE_STRICMP",ln:32},{name:"HAVE_STRNICMP",ln:33},{name:"HAVE_STRSTR",ln:34},{name:"HAVE_SYS_STAT_H",ln:26},{name:"HAVE_SYS_TYPES_H",ln:27},{name:"HAVE_TEMPNAM",ln:37},{name:"HAVE_TIME_H",ln:28},{name:"HAVE__FINDFIRST",ln:49},{name:"HAVE__FINDFIRST",ln:68},{name:"MANUAL_GLOBBING",ln:20},{name:"MSDOS_STYLE_PATH",ln:21},{name:"NEED_PROTO_FGETPOS",ln:64},{name:"TMPDIR",ln:39},{name:"errout",ln:17},{name:"ff_name",ln:72},{name:"ffblk",ln:70},{name:"findfirst_t",ln:53},{name:"findfirst_t",ln:55},{name:"findfirst_t",ln:69},{name:"tempnam",ln:38},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/e_msoft.h"})';
</script>