<div class="div_line"  data-info=({id:36080,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:36081,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: e_riscos.h 136 2002-03-08 22:35:19Z darren $
</div></div></div><div class="div_line"  data-info=({id:36082,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:36083,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 2002, Andrew Wingate
</div></div></div><div class="div_line"  data-info=({id:36084,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:36085,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Author: Andrew Wingate &lt;andy@sparse.net&gt;
</div></div></div><div class="div_line"  data-info=({id:36086,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:36087,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:36088,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License. It is provided on an as-is basis and no
</div></div></div><div class="div_line"  data-info=({id:36089,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   responsibility is accepted for its failure to perform as expected.
</div></div></div><div class="div_line"  data-info=({id:36090,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:36091,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Configures ctags for RISC OS environment.
</div></div></div><div class="div_line"  data-info=({id:36092,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:36093,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   We currently use UnixLib. This file is subject to change if
</div></div></div><div class="div_line"  data-info=({id:36094,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   we move to using SharedCLibrary and libGNU.
</div></div></div><div class="div_line"  data-info=({id:36095,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:36096,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/e_riscos.h#line18' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>E_RISCOS_H</a>
</div></div></div><div class="div_line"  data-info=({id:36097,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>E_RISCOS_H</span>
</div></div></div><div class="div_line"  data-info=({id:36098,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:36099,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>MACROS_USE_PATTERNS</span> 1
</div></div></div><div class="div_line"  data-info=({id:36100,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>DEFAULT_FILE_FORMAT</span> 2
</div></div></div><div class="div_line"  data-info=({id:36101,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>INTERNAL_SORT</span> 1 /* Not all systems will have installed sort(1) */
</div></div></div><div class="div_line"  data-info=({id:36102,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>TMPDIR</span> "&lt;Wimp$ScrapDir&gt;"
</div></div></div><div class="div_line"  data-info=({id:36103,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:36104,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Various definitions for UnixLib */
</div></div></div><div class="div_line"  data-info=({id:36105,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>STDC_HEADERS</span> 1
</div></div></div><div class="div_line"  data-info=({id:36106,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_CHMOD</span> 1
</div></div></div><div class="div_line"  data-info=({id:36107,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_CHSIZE</span> 1
</div></div></div><div class="div_line"  data-info=({id:36108,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_CLOCK</span> 1
</div></div></div><div class="div_line"  data-info=({id:36109,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FGETPOS</span> 1
</div></div></div><div class="div_line"  data-info=({id:36110,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FNMATCH</span> 1
</div></div></div><div class="div_line"  data-info=({id:36111,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FTRUNCATE</span> 1
</div></div></div><div class="div_line"  data-info=({id:36112,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_MKSTEMP</span> 1
</div></div></div><div class="div_line"  data-info=({id:36113,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_OPENDIR</span> 1
</div></div></div><div class="div_line"  data-info=({id:36114,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_PUTENV</span> 1
</div></div></div><div class="div_line"  data-info=({id:36115,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_REGCOMP</span> 1 /* Requires RegEx library */
</div></div></div><div class="div_line"  data-info=({id:36116,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_REMOVE</span> 1
</div></div></div><div class="div_line"  data-info=({id:36117,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SETENV</span> 1
</div></div></div><div class="div_line"  data-info=({id:36118,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRERROR</span> 1
</div></div></div><div class="div_line"  data-info=({id:36119,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRICMP</span> 1
</div></div></div><div class="div_line"  data-info=({id:36120,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRNICMP</span> 1
</div></div></div><div class="div_line"  data-info=({id:36121,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRSTR</span> 1
</div></div></div><div class="div_line"  data-info=({id:36122,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_TIMES</span> 1
</div></div></div><div class="div_line"  data-info=({id:36123,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_TRUNCATE</span> 1
</div></div></div><div class="div_line"  data-info=({id:36124,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_DIRENT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36125,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FCNTL_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36126,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_FNMATCH_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36127,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STAT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36128,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STDLIB_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36129,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_STRING_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36130,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_DIR_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36131,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_STAT_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36132,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_TIMES_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36133,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_SYS_TYPES_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36134,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_TIME_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36135,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HAVE_UNISTD_H</span> 1
</div></div></div><div class="div_line"  data-info=({id:36136,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:36137,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><script>var local_symbol_set='([{name:"DEFAULT_FILE_FORMAT",ln:21},{name:"E_RISCOS_H",ln:18},{name:"HAVE_CHMOD",ln:27},{name:"HAVE_CHSIZE",ln:28},{name:"HAVE_CLOCK",ln:29},{name:"HAVE_DIRENT_H",ln:45},{name:"HAVE_FCNTL_H",ln:46},{name:"HAVE_FGETPOS",ln:30},{name:"HAVE_FNMATCH",ln:31},{name:"HAVE_FNMATCH_H",ln:47},{name:"HAVE_FTRUNCATE",ln:32},{name:"HAVE_MKSTEMP",ln:33},{name:"HAVE_OPENDIR",ln:34},{name:"HAVE_PUTENV",ln:35},{name:"HAVE_REGCOMP",ln:36},{name:"HAVE_REMOVE",ln:37},{name:"HAVE_SETENV",ln:38},{name:"HAVE_STAT_H",ln:48},{name:"HAVE_STDLIB_H",ln:49},{name:"HAVE_STRERROR",ln:39},{name:"HAVE_STRICMP",ln:40},{name:"HAVE_STRING_H",ln:50},{name:"HAVE_STRNICMP",ln:41},{name:"HAVE_STRSTR",ln:42},{name:"HAVE_SYS_DIR_H",ln:51},{name:"HAVE_SYS_STAT_H",ln:52},{name:"HAVE_SYS_TIMES_H",ln:53},{name:"HAVE_SYS_TYPES_H",ln:54},{name:"HAVE_TIMES",ln:43},{name:"HAVE_TIME_H",ln:55},{name:"HAVE_TRUNCATE",ln:44},{name:"HAVE_UNISTD_H",ln:56},{name:"INTERNAL_SORT",ln:22},{name:"MACROS_USE_PATTERNS",ln:20},{name:"STDC_HEADERS",ln:26},{name:"TMPDIR",ln:23},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/e_riscos.h"})';
</script>