<div class="div_line"  data-info=({id:508,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:509,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: options.h 443 2006-05-30 04:37:13Z darren $
</div></div></div><div class="div_line"  data-info=({id:510,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:511,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 1998-2003, Darren Hiebert
</div></div></div><div class="div_line"  data-info=({id:512,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:513,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:514,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License.
</div></div></div><div class="div_line"  data-info=({id:515,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:516,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Defines external interface to option processing.
</div></div></div><div class="div_line"  data-info=({id:517,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:518,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/options.h#line12' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_OPTIONS_H</a>
</div></div></div><div class="div_line"  data-info=({id:519,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>_OPTIONS_H</span>
</div></div></div><div class="div_line"  data-info=({id:520,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:521,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#if defined(<a href='ctags/options.c#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>OPTION_WRITE</a>) || defined(VAXC)
</div></div></div><div class="div_line"  data-info=({id:522,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>CONST_OPTION</span>
</div></div></div><div class="div_line"  data-info=({id:523,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#else
</div></div></div><div class="div_line"  data-info=({id:524,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>CONST_OPTION</span> const
</div></div></div><div class="div_line"  data-info=({id:525,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:526,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:527,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:528,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   INCLUDE FILES
</div></div></div><div class="div_line"  data-info=({id:529,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:530,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>general.h</span>"  /* must always come first */
</div></div></div><div class="div_line"  data-info=({id:531,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:532,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>stdarg.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:533,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:534,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>args.h</span>"
</div></div></div><div class="div_line"  data-info=({id:535,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>parse.h</span>"
</div></div></div><div class="div_line"  data-info=({id:536,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>strlist.h</span>"
</div></div></div><div class="div_line"  data-info=({id:537,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>vstring.h</span>"
</div></div></div><div class="div_line"  data-info=({id:538,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:539,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:540,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   DATA DECLARATIONS
</div></div></div><div class="div_line"  data-info=({id:541,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:542,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:543,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef enum { <span class='ctd member'>OPTION_NONE</span>, OPTION_SHORT, OPTION_LONG } optionType;
</div></div></div><div class="div_line"  data-info=({id:544,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:545,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <span class='ctd strdef'>sCookedArgs</span> {
</div></div></div><div class="div_line"  data-info=({id:546,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* private */
</div></div></div><div class="div_line"  data-info=({id:547,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;Arguments* <span class='ctd member'>args</span>;
</div></div></div><div class="div_line"  data-info=({id:548,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *<span class='ctd member'>shortOptions</span>;
</div></div></div><div class="div_line"  data-info=({id:549,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char <span class='ctd member'>simple</span>[2];
</div></div></div><div class="div_line"  data-info=({id:550,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isOption</span>;
</div></div></div><div class="div_line"  data-info=({id:551,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>longOption</span>;
</div></div></div><div class="div_line"  data-info=({id:552,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char* <span class='ctd member'>parameter</span>;
</div></div></div><div class="div_line"  data-info=({id:553,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* public */
</div></div></div><div class="div_line"  data-info=({id:554,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char* <span class='ctd member'>item</span>;
</div></div></div><div class="div_line"  data-info=({id:555,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>cookedArgs</span>;
</div></div></div><div class="div_line"  data-info=({id:556,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:557,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef enum <span class='ctd enumdef'>eLocate</span> {
</div></div></div><div class="div_line"  data-info=({id:558,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>EX_MIX</span>,      /* line numbers for defines, patterns otherwise */
</div></div></div><div class="div_line"  data-info=({id:559,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>EX_LINENUM</span>,  /* -n  only line numbers in tag file */
</div></div></div><div class="div_line"  data-info=({id:560,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>EX_PATTERN</span>   /* -N  only patterns in tag file */
</div></div></div><div class="div_line"  data-info=({id:561,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>exCmd</span>;
</div></div></div><div class="div_line"  data-info=({id:562,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:563,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef enum <span class='ctd enumdef'>sortType</span> {
</div></div></div><div class="div_line"  data-info=({id:564,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>SO_UNSORTED</span>,
</div></div></div><div class="div_line"  data-info=({id:565,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>SO_SORTED</span>,
</div></div></div><div class="div_line"  data-info=({id:566,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>SO_FOLDSORTED</span>
</div></div></div><div class="div_line"  data-info=({id:567,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>sortType</span>;
</div></div></div><div class="div_line"  data-info=({id:568,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:569,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>sInclude</span> {
</div></div></div><div class="div_line"  data-info=({id:570,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>fileNames</span>;      /* include tags for source file names */
</div></div></div><div class="div_line"  data-info=({id:571,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>qualifiedTags</span>;  /* include tags for qualified class members */
</div></div></div><div class="div_line"  data-info=({id:572,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>fileScope</span>;      /* include tags of file scope only */
</div></div></div><div class="div_line"  data-info=({id:573,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:574,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:575,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>sExtFields</span> {  /* extension field content control */
</div></div></div><div class="div_line"  data-info=({id:576,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>access</span>;
</div></div></div><div class="div_line"  data-info=({id:577,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>fileScope</span>;
</div></div></div><div class="div_line"  data-info=({id:578,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>implementation</span>;
</div></div></div><div class="div_line"  data-info=({id:579,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>inheritance</span>;
</div></div></div><div class="div_line"  data-info=({id:580,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>kind</span>;
</div></div></div><div class="div_line"  data-info=({id:581,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>kindKey</span>;
</div></div></div><div class="div_line"  data-info=({id:582,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>kindLong</span>;
</div></div></div><div class="div_line"  data-info=({id:583,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>language</span>;
</div></div></div><div class="div_line"  data-info=({id:584,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>lineNumber</span>;
</div></div></div><div class="div_line"  data-info=({id:585,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>scope</span>;
</div></div></div><div class="div_line"  data-info=({id:586,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>signature</span>;
</div></div></div><div class="div_line"  data-info=({id:587,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>typeRef</span>;
</div></div></div><div class="div_line"  data-info=({id:588,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:589,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:590,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  This stores the command line options.
</div></div></div><div class="div_line"  data-info=({id:591,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:592,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <span class='ctd strdef'>sOptionValues</span> {
</div></div></div><div class="div_line"  data-info=({id:593,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ctags/options.h#line62' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sInclude</a> <span class='ctd member'>include</span>;/* --extra  extra tag inclusion */
</div></div></div><div class="div_line"  data-info=({id:594,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ctags/options.h#line68' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sExtFields</a> <span class='ctd member'>extensionFields</span>;/* --fields  extension field control */
</div></div></div><div class="div_line"  data-info=({id:595,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;stringList* <span class='ctd member'>ignore</span>;     /* -I  name of file containing tokens to ignore */
</div></div></div><div class="div_line"  data-info=({id:596,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>append</span>;         /* -a  append to "tags" file */
</div></div></div><div class="div_line"  data-info=({id:597,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>backward</span>;       /* -B  regexp patterns search backwards */
</div></div></div><div class="div_line"  data-info=({id:598,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>etags</span>;          /* -e  output Emacs style tags file */
</div></div></div><div class="div_line"  data-info=({id:599,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;exCmd <span class='ctd member'>locate</span>;           /* --excmd  EX command used to locate tag */
</div></div></div><div class="div_line"  data-info=({id:600,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>recurse</span>;        /* -R  recurse into directories */
</div></div></div><div class="div_line"  data-info=({id:601,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/options.h#line56' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sortType</a> <span class='ctd member'>sorted</span>;        /* -u,--sort  sort tags */
</div></div></div><div class="div_line"  data-info=({id:602,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>verbose</span>;        /* -V  verbose */
</div></div></div><div class="div_line"  data-info=({id:603,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>xref</span>;           /* -x  generate xref output instead */
</div></div></div><div class="div_line"  data-info=({id:604,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *<span class='ctd member'>fileList</span>;         /* -L  name of file containing names of files */
</div></div></div><div class="div_line"  data-info=({id:605,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *<span class='ctd member'>tagFileName</span>;      /* -o  name of tags file */
</div></div></div><div class="div_line"  data-info=({id:606,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;stringList* <span class='ctd member'>headerExt</span>;  /* -h  header extensions */
</div></div></div><div class="div_line"  data-info=({id:607,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;stringList* <span class='ctd member'>etagsInclude</span>;/* --etags-include  list of TAGS files to include*/
</div></div></div><div class="div_line"  data-info=({id:608,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int <span class='ctd member'>tagFileFormat</span>;/* --format  tag file format (level) */
</div></div></div><div class="div_line"  data-info=({id:609,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>if0</span>;            /* --if0  examine code within "#if 0" branch */
</div></div></div><div class="div_line"  data-info=({id:610,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>kindLong</span>;       /* --kind-long */
</div></div></div><div class="div_line"  data-info=({id:611,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;langType <span class='ctd member'>language</span>;      /* --lang specified language override */
</div></div></div><div class="div_line"  data-info=({id:612,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>followLinks</span>;    /* --link  follow symbolic links? */
</div></div></div><div class="div_line"  data-info=({id:613,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>filter</span>;         /* --filter  behave as filter: files in, tags out */
</div></div></div><div class="div_line"  data-info=({id:614,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char* <span class='ctd member'>filterTerminator</span>; /* --filter-terminator  string to output */
</div></div></div><div class="div_line"  data-info=({id:615,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>tagRelative</span>;    /* --tag-relative file paths relative to tag file */
</div></div></div><div class="div_line"  data-info=({id:616,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>printTotals</span>;    /* --totals  print cumulative statistics */
</div></div></div><div class="div_line"  data-info=({id:617,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>lineDirectives</span>; /* --linedirectives  process #line directives */
</div></div></div><div class="div_line"  data-info=({id:618,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef DEBUG
</div></div></div><div class="div_line"  data-info=({id:619,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;long <span class='ctd member'>debugLevel</span>;        /* -D  debugging output */
</div></div></div><div class="div_line"  data-info=({id:620,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned long <span class='ctd member'>breakLine</span>;/* -b  source line at which to call lineBreak() */
</div></div></div><div class="div_line"  data-info=({id:621,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:622,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>optionValues</span>;
</div></div></div><div class="div_line"  data-info=({id:623,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:624,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:625,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GLOBAL VARIABLES
</div></div></div><div class="div_line"  data-info=({id:626,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:627,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/options.h#line15' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>CONST_OPTION</a> optionValues&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/options.c#line104' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>Option</a>;
</div></div></div><div class="div_line"  data-info=({id:628,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:629,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:630,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   FUNCTION PROTOTYPES
</div></div></div><div class="div_line"  data-info=({id:631,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:632,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>verbose</span> (const char *const format, ...) __printf__ (1, 2);
</div></div></div><div class="div_line"  data-info=({id:633,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line377' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>freeList</a> (stringList** const pString);
</div></div></div><div class="div_line"  data-info=({id:634,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line386' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>setDefaultTagFileName</a> (void);
</div></div></div><div class="div_line"  data-info=({id:635,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line404' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>checkOptions</a> (void);
</div></div></div><div class="div_line"  data-info=({id:636,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line396' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>filesRequired</a> (void);
</div></div></div><div class="div_line"  data-info=({id:637,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line443' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>testEtagsInvocation</a> (void);
</div></div></div><div class="div_line"  data-info=({id:638,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:639,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern cookedArgs* <a href='ctags/options.c#line542' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgNewFromString</a> (const char* string);
</div></div></div><div class="div_line"  data-info=({id:640,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern cookedArgs* <a href='ctags/options.c#line551' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgNewFromArgv</a> (char* const* const argv);
</div></div></div><div class="div_line"  data-info=({id:641,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern cookedArgs* <a href='ctags/options.c#line560' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgNewFromFile</a> (FILE* const fp);
</div></div></div><div class="div_line"  data-info=({id:642,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern cookedArgs* <a href='ctags/options.c#line569' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgNewFromLineFile</a> (FILE* const fp);
</div></div></div><div class="div_line"  data-info=({id:643,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line578' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgDelete</a> (cookedArgs* const current);
</div></div></div><div class="div_line"  data-info=({id:644,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line595' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgOff</a> (cookedArgs* const current);
</div></div></div><div class="div_line"  data-info=({id:645,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line601' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgIsOption</a> (cookedArgs* const current);
</div></div></div><div class="div_line"  data-info=({id:646,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char* <a href='ctags/options.c#line607' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgItem</a> (cookedArgs* const current);
</div></div></div><div class="div_line"  data-info=({id:647,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line613' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>cArgForth</a> (cookedArgs* const current);
</div></div></div><div class="div_line"  data-info=({id:648,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:649,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line759' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isExcludedFile</a> (const char* const name);
</div></div></div><div class="div_line"  data-info=({id:650,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line704' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isIncludeFile</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:651,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/options.c#line1259' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isIgnoreToken</a> (const char *const name, <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> *const pIgnoreParens, const char **const replacement);
</div></div></div><div class="div_line"  data-info=({id:652,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1612' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>parseOption</a> (cookedArgs* const cargs);
</div></div></div><div class="div_line"  data-info=({id:653,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1630' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>parseOptions</a> (cookedArgs* const cargs);
</div></div></div><div class="div_line"  data-info=({id:654,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1675' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>previewFirstOption</a> (cookedArgs* const cargs);
</div></div></div><div class="div_line"  data-info=({id:655,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1772' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>readOptionConfiguration</a> (void);
</div></div></div><div class="div_line"  data-info=({id:656,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1785' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>initOptions</a> (void);
</div></div></div><div class="div_line"  data-info=({id:657,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/options.c#line1816' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>freeOptionResources</a> (void);
</div></div></div><div class="div_line"  data-info=({id:658,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:659,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif  /* _OPTIONS_H */
</div></div></div><div class="div_line"  data-info=({id:660,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:661,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* vi:set tabstop=4 shiftwidth=4: */
</div></div></div><script>var local_symbol_set='([{name:"CONST_OPTION",ln:15},{name:"CONST_OPTION",ln:17},{name:"EX_LINENUM",ln:52},{name:"EX_MIX",ln:51},{name:"EX_PATTERN",ln:53},{name:"OPTION_LONG",ln:36},{name:"OPTION_NONE",ln:36},{name:"OPTION_SHORT",ln:36},{name:"SO_FOLDSORTED",ln:59},{name:"SO_SORTED",ln:58},{name:"SO_UNSORTED",ln:57},{name:"_OPTIONS_H",ln:12},{name:"access",ln:69},{name:"append",ln:89},{name:"args",ln:40},{name:"backward",ln:90},{name:"breakLine",ln:113},{name:"cookedArgs",ln:48},{name:"debugLevel",ln:112},{name:"eLocate",ln:50},{name:"etags",ln:91},{name:"etagsInclude",ln:100},{name:"exCmd",ln:54},{name:"extensionFields",ln:87},{name:"fileList",ln:97},{name:"fileNames",ln:63},{name:"fileScope",ln:65},{name:"fileScope",ln:70},{name:"filter",ln:106},{name:"filterTerminator",ln:107},{name:"followLinks",ln:105},{name:"headerExt",ln:99},{name:"if0",ln:102},{name:"ignore",ln:88},{name:"implementation",ln:71},{name:"include",ln:86},{name:"inheritance",ln:72},{name:"isOption",ln:43},{name:"item",ln:47},{name:"kind",ln:73},{name:"kindKey",ln:74},{name:"kindLong",ln:103},{name:"kindLong",ln:75},{name:"language",ln:104},{name:"language",ln:76},{name:"lineDirectives",ln:110},{name:"lineNumber",ln:77},{name:"locate",ln:92},{name:"longOption",ln:44},{name:"optionType",ln:36},{name:"optionValues",ln:115},{name:"parameter",ln:45},{name:"printTotals",ln:109},{name:"qualifiedTags",ln:64},{name:"recurse",ln:93},{name:"sCookedArgs",ln:38},{name:"sExtFields",ln:68},{name:"sInclude",ln:62},{name:"sOptionValues",ln:85},{name:"scope",ln:78},{name:"shortOptions",ln:41},{name:"signature",ln:79},{name:"simple",ln:42},{name:"sortType",ln:56},{name:"sortType",ln:60},{name:"sorted",ln:94},{name:"tagFileFormat",ln:101},{name:"tagFileName",ln:98},{name:"tagRelative",ln:108},{name:"typeRef",ln:80},{name:"verbose",ln:95},{name:"xref",ln:96},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/options.h"})';
</script>