<div class="div_line"  data-info=({id:59592,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:59593,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: parse.h 443 2006-05-30 04:37:13Z darren $
</div></div></div><div class="div_line"  data-info=({id:59594,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:59595,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 1998-2003, Darren Hiebert
</div></div></div><div class="div_line"  data-info=({id:59596,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:59597,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:59598,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License.
</div></div></div><div class="div_line"  data-info=({id:59599,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:59600,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Private definitions for parsing support.
</div></div></div><div class="div_line"  data-info=({id:59601,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:59602,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/parse.h#line12' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_PARSE_H</a>
</div></div></div><div class="div_line"  data-info=({id:59603,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>_PARSE_H</span>
</div></div></div><div class="div_line"  data-info=({id:59604,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59605,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:59606,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   INCLUDE FILES
</div></div></div><div class="div_line"  data-info=({id:59607,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:59608,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>general.h</span>"  /* must always come first */
</div></div></div><div class="div_line"  data-info=({id:59609,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>parsers.h</span>"  /* contains list of parsers */
</div></div></div><div class="div_line"  data-info=({id:59610,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>strlist.h</span>"
</div></div></div><div class="div_line"  data-info=({id:59611,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59612,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:59613,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   MACROS
</div></div></div><div class="div_line"  data-info=({id:59614,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:59615,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>KIND_COUNT</span>(kindTable) (sizeof(kindTable)/sizeof(kindOption))
</div></div></div><div class="div_line"  data-info=({id:59616,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59617,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>LANG_AUTO</span>   (-1)
</div></div></div><div class="div_line"  data-info=({id:59618,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>LANG_IGNORE</span> (-2)
</div></div></div><div class="div_line"  data-info=({id:59619,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59620,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:59621,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   DATA DECLARATIONS
</div></div></div><div class="div_line"  data-info=({id:59622,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:59623,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef int <span class='ctd typedef'>langType</span>;
</div></div></div><div class="div_line"  data-info=({id:59624,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59625,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>createRegexTag</span>) (const vString* const name);
</div></div></div><div class="div_line"  data-info=({id:59626,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>simpleParser</span>) (void);
</div></div></div><div class="div_line"  data-info=({id:59627,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef <span class='ctd fndef'>boolean</span> (*rescanParser) (const unsigned int passCount);
</div></div></div><div class="div_line"  data-info=({id:59628,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>parserInitialize</span>) (langType language);
</div></div></div><div class="div_line"  data-info=({id:59629,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59630,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <span class='ctd strdef'>sKindOption</span> {
</div></div></div><div class="div_line"  data-info=({id:59631,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> enabled;          /* are tags for kind enabled? */
</div></div></div><div class="div_line"  data-info=({id:59632,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int letter;               /* kind letter */
</div></div></div><div class="div_line"  data-info=({id:59633,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char* name;         /* kind name */
</div></div></div><div class="div_line"  data-info=({id:59634,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char* description;  /* displayed in --help output */
</div></div></div><div class="div_line"  data-info=({id:59635,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>kindOption</span>;
</div></div></div><div class="div_line"  data-info=({id:59636,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59637,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct {
</div></div></div><div class="div_line"  data-info=({id:59638,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* defined by parser */
</div></div></div><div class="div_line"  data-info=({id:59639,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char* name;                    /* name of language */
</div></div></div><div class="div_line"  data-info=({id:59640,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;kindOption* kinds;             /* tag kinds handled by parser */
</div></div></div><div class="div_line"  data-info=({id:59641,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int kindCount;        /* size of `kinds' list */
</div></div></div><div class="div_line"  data-info=({id:59642,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *const *extensions; /* list of default extensions */
</div></div></div><div class="div_line"  data-info=({id:59643,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *const *patterns;   /* list of default file name patterns */
</div></div></div><div class="div_line"  data-info=({id:59644,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;parserInitialize initialize;   /* initialization routine, if needed */
</div></div></div><div class="div_line"  data-info=({id:59645,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;simpleParser parser;           /* simple parser (common case) */
</div></div></div><div class="div_line"  data-info=({id:59646,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;rescanParser parser2;          /* rescanning parser (unusual case) */
</div></div></div><div class="div_line"  data-info=({id:59647,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> regex;                 /* is this a regex parser? */
</div></div></div><div class="div_line"  data-info=({id:59648,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59649,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* used internally */
</div></div></div><div class="div_line"  data-info=({id:59650,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int id;               /* id assigned to language */
</div></div></div><div class="div_line"  data-info=({id:59651,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> enabled;               /* currently enabled? */
</div></div></div><div class="div_line"  data-info=({id:59652,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;stringList* currentPatterns;   /* current list of file name patterns */
</div></div></div><div class="div_line"  data-info=({id:59653,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;stringList* currentExtensions; /* current list of extensions */
</div></div></div><div class="div_line"  data-info=({id:59654,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>parserDefinition</span>;
</div></div></div><div class="div_line"  data-info=({id:59655,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59656,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef parserDefinition* (<span class='ctd typedef'>parserDefinitionFunc</span>) (void);
</div></div></div><div class="div_line"  data-info=({id:59657,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59658,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct {
</div></div></div><div class="div_line"  data-info=({id:59659,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;size_t <a href='ctags/gnu_regex/regex.h#line434' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>start</a>;   /* character index in line where match starts */
</div></div></div><div class="div_line"  data-info=({id:59660,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;size_t length;  /* length of match */
</div></div></div><div class="div_line"  data-info=({id:59661,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>regexMatch</span>;
</div></div></div><div class="div_line"  data-info=({id:59662,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59663,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>regexCallback</span>) (const char *line, const regexMatch *matches, unsigned int count);
</div></div></div><div class="div_line"  data-info=({id:59664,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59665,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:59666,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   FUNCTION PROTOTYPES
</div></div></div><div class="div_line"  data-info=({id:59667,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:59668,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59669,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Each parsers' definition function is called. The routine is expected to
</div></div></div><div class="div_line"  data-info=({id:59670,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * return a structure allocated using parserNew(). This structure must,
</div></div></div><div class="div_line"  data-info=({id:59671,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * at minimum, set the `parser' field.
</div></div></div><div class="div_line"  data-info=({id:59672,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:59673,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern parserDefinitionFunc <a href='ctags/parsers.h#line18' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>PARSER_LIST</a>;
</div></div></div><div class="div_line"  data-info=({id:59674,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59675,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Legacy interface */
</div></div></div><div class="div_line"  data-info=({id:59676,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/c.c#line474' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>includingDefineTags</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59677,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59678,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Language processing and parsing */
</div></div></div><div class="div_line"  data-info=({id:59679,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line41' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>makeSimpleTag</a> (const vString* const name, kindOption* const kinds, const int kind);
</div></div></div><div class="div_line"  data-info=({id:59680,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern parserDefinition* <a href='ctags/parse.c#line60' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>parserNew</a> (const char* name);
</div></div></div><div class="div_line"  data-info=({id:59681,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *<a href='ctags/parse.c#line67' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>getLanguageName</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59682,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern langType <a href='ctags/parse.c#line80' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>getNamedLanguage</a> (const char *const name);
</div></div></div><div class="div_line"  data-info=({id:59683,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern langType <a href='ctags/parse.c#line169' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>getFileLanguage</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:59684,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line210' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>installLanguageMapDefault</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59685,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line239' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>installLanguageMapDefaults</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59686,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line249' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>clearLanguageMap</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59687,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/parse.c#line267' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>removeLanguageExtensionMap</a> (const char *const extension);
</div></div></div><div class="div_line"  data-info=({id:59688,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line283' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>addLanguageExtensionMap</a> (const langType language, const char* extension);
</div></div></div><div class="div_line"  data-info=({id:59689,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line256' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>addLanguagePatternMap</a> (const langType language, const char* ptrn);
</div></div></div><div class="div_line"  data-info=({id:59690,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line189' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>printLanguageMap</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59691,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line553' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>printLanguageMaps</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59692,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line298' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>enableLanguages</a> (const <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> state);
</div></div></div><div class="div_line"  data-info=({id:59693,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line292' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>enableLanguage</a> (const langType language, const <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> state);
</div></div></div><div class="div_line"  data-info=({id:59694,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line313' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>initializeParsing</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59695,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line356' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>freeParserResources</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59696,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line378' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>processLanguageDefineOption</a> (const char *const option, const char *const parameter);
</div></div></div><div class="div_line"  data-info=({id:59697,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/parse.c#line474' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>processKindOption</a> (const char *const option, const char *const parameter);
</div></div></div><div class="div_line"  data-info=({id:59698,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void printKindOptions (void);
</div></div></div><div class="div_line"  data-info=({id:59699,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line519' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>printLanguageKinds</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59700,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/parse.c#line574' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>printLanguageList</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59701,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/parse.c#line650' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>parseFile</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:59702,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59703,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Regex interface */
</div></div></div><div class="div_line"  data-info=({id:59704,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef <a href='ctags/general.h#line53' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>HAVE_REGEX</a>
</div></div></div><div class="div_line"  data-info=({id:59705,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line531' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>findRegexTags</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59706,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/lregex.c#line516' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>matchRegex</a> (const vString* const line, const langType language);
</div></div></div><div class="div_line"  data-info=({id:59707,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:59708,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/lregex.c#line604' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>processRegexOption</a> (const char *const option, const char *const parameter);
</div></div></div><div class="div_line"  data-info=({id:59709,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line583' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>addLanguageRegex</a> (const langType language, const char* const regex);
</div></div></div><div class="div_line"  data-info=({id:59710,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line540' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>addTagRegex</a> (const langType language, const char* const regex, const char* const name, const char* const kinds, const char* const flags);
</div></div></div><div class="div_line"  data-info=({id:59711,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line566' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>addCallbackRegex</a> (const langType language, const char *const regex, const char *const flags, const regexCallback callback);
</div></div></div><div class="div_line"  data-info=({id:59712,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line627' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>disableRegexKinds</a> (const langType language);
</div></div></div><div class="div_line"  data-info=({id:59713,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/lregex.c#line641' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>enableRegexKind</a> (const langType language, const int kind, const <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> mode);
</div></div></div><div class="div_line"  data-info=({id:59714,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line663' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>printRegexKinds</a> (const langType language, <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> indent);
</div></div></div><div class="div_line"  data-info=({id:59715,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line677' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>freeRegexResources</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59716,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/lregex.c#line691' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>checkRegex</a> (void);
</div></div></div><div class="div_line"  data-info=({id:59717,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59718,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif  /* _PARSE_H */
</div></div></div><div class="div_line"  data-info=({id:59719,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:59720,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* vi:set tabstop=4 shiftwidth=4: */
</div></div></div><script>var local_symbol_set='([{name:"KIND_COUNT",ln:24},{name:"LANG_AUTO",ln:26},{name:"LANG_IGNORE",ln:27},{name:"_PARSE_H",ln:12},{name:"createRegexTag",ln:34},{name:"currentExtensions",ln:62},{name:"currentPatterns",ln:61},{name:"description",ln:43},{name:"enabled",ln:40},{name:"enabled",ln:60},{name:"extensions",ln:51},{name:"id",ln:59},{name:"initialize",ln:53},{name:"kindCount",ln:50},{name:"kindOption",ln:44},{name:"kinds",ln:49},{name:"langType",ln:32},{name:"length",ln:69},{name:"letter",ln:41},{name:"name",ln:42},{name:"name",ln:48},{name:"parser",ln:54},{name:"parser2",ln:55},{name:"parserDefinition",ln:63},{name:"parserDefinitionFunc",ln:65},{name:"parserInitialize",ln:37},{name:"patterns",ln:52},{name:"regex",ln:56},{name:"regexCallback",ln:72},{name:"regexMatch",ln:70},{name:"rescanParser",ln:36},{name:"sKindOption",ln:39},{name:"simpleParser",ln:35},{name:"start",ln:68},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/parse.h"})';
</script>