<div class="div_line"  data-info=({id:33463,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33464,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: routines.h 536 2007-06-02 06:09:00Z elliotth $
</div></div></div><div class="div_line"  data-info=({id:33465,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:33466,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 2002, Darren Hiebert
</div></div></div><div class="div_line"  data-info=({id:33467,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:33468,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:33469,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License.
</div></div></div><div class="div_line"  data-info=({id:33470,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:33471,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   External interface to routines.c
</div></div></div><div class="div_line"  data-info=({id:33472,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:33473,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/routines.h#line12' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_ROUTINES_H</a>
</div></div></div><div class="div_line"  data-info=({id:33474,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>_ROUTINES_H</span>
</div></div></div><div class="div_line"  data-info=({id:33475,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33476,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33477,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   INCLUDE FILES
</div></div></div><div class="div_line"  data-info=({id:33478,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:33479,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>general.h</span>"  /* must always come first */
</div></div></div><div class="div_line"  data-info=({id:33480,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33481,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33482,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   MACROS
</div></div></div><div class="div_line"  data-info=({id:33483,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:33484,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>xMalloc</span>(n,Type)    (Type *)<a href='ctags/routines.c#line236' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eMalloc</a>((size_t)(n) * sizeof (Type))
</div></div></div><div class="div_line"  data-info=({id:33485,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>xCalloc</span>(n,Type)    (Type *)<a href='ctags/routines.c#line246' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eCalloc</a>((size_t)(n), sizeof (Type))
</div></div></div><div class="div_line"  data-info=({id:33486,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>xRealloc</span>(p,n,Type) (Type *)<a href='ctags/routines.c#line256' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eRealloc</a>((p), (n) * sizeof (Type))
</div></div></div><div class="div_line"  data-info=({id:33487,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33488,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33489,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Portability macros
</div></div></div><div class="div_line"  data-info=({id:33490,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:33491,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/routines.h#line31' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>PATH_SEPARATOR</a>
</div></div></div><div class="div_line"  data-info=({id:33492,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># if defined (<a href='ctags/e_djgpp.h#line15' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>MSDOS_STYLE_PATH</a>)
</div></div></div><div class="div_line"  data-info=({id:33493,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>PATH_SEPARATOR</span> '\\'
</div></div></div><div class="div_line"  data-info=({id:33494,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># elif defined (QDOS)
</div></div></div><div class="div_line"  data-info=({id:33495,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>PATH_SEPARATOR</span> '_'
</div></div></div><div class="div_line"  data-info=({id:33496,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># else
</div></div></div><div class="div_line"  data-info=({id:33497,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#  define <span class='ctd macdef'>PATH_SEPARATOR</span> '/'
</div></div></div><div class="div_line"  data-info=({id:33498,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># endif
</div></div></div><div class="div_line"  data-info=({id:33499,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33500,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33501,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#if defined (<a href='ctags/e_djgpp.h#line15' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>MSDOS_STYLE_PATH</a>) && defined (<a href='ctags/e_os2.h#line14' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>UNIX_PATH_SEPARATOR</a>)
</div></div></div><div class="div_line"  data-info=({id:33502,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>OUTPUT_PATH_SEPARATOR</span>&#160;&#160;&#160;&#160;'/'
</div></div></div><div class="div_line"  data-info=({id:33503,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#else
</div></div></div><div class="div_line"  data-info=({id:33504,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"># define <span class='ctd macdef'>OUTPUT_PATH_SEPARATOR</span>&#160;&#160;&#160;&#160;<a href='ctags/routines.h#line31' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>PATH_SEPARATOR</a>
</div></div></div><div class="div_line"  data-info=({id:33505,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33506,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33507,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33508,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   DATA DECLARATIONS
</div></div></div><div class="div_line"  data-info=({id:33509,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:33510,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#if defined (<a href='ctags/e_djgpp.h#line15' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>MSDOS_STYLE_PATH</a>) || defined (<a href='ctags/general.h#line36' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>VMS</a>)
</div></div></div><div class="div_line"  data-info=({id:33511,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *const <a href='ctags/routines.c#line154' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>PathDelimiters</a>;
</div></div></div><div class="div_line"  data-info=({id:33512,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33513,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char *<a href='ctags/routines.c#line159' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>CurrentDirectory</a>;
</div></div></div><div class="div_line"  data-info=({id:33514,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef int <span class='ctd typedef'>errorSelection</span>;
</div></div></div><div class="div_line"  data-info=({id:33515,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">enum <span class='ctd enumdef'>eErrorTypes</span> { FATAL = 1, WARNING = 2, PERROR = 4 };
</div></div></div><div class="div_line"  data-info=({id:33516,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33517,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct {
</div></div></div><div class="div_line"  data-info=({id:33518,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Name of file for which status is valid */
</div></div></div><div class="div_line"  data-info=({id:33519,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char* <span class='ctd member'>name</span>;
</div></div></div><div class="div_line"  data-info=({id:33520,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33521,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Does file exist? If not, members below do not contain valid data. */
</div></div></div><div class="div_line"  data-info=({id:33522,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>exists</span>;
</div></div></div><div class="div_line"  data-info=({id:33523,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33524,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* is file path a symbolic link to another file? */
</div></div></div><div class="div_line"  data-info=({id:33525,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isSymbolicLink</span>;
</div></div></div><div class="div_line"  data-info=({id:33526,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33527,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Is file (pointed to) a directory? */
</div></div></div><div class="div_line"  data-info=({id:33528,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isDirectory</span>;
</div></div></div><div class="div_line"  data-info=({id:33529,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33530,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Is file (pointed to) a normal file? */
</div></div></div><div class="div_line"  data-info=({id:33531,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isNormalFile</span>;
</div></div></div><div class="div_line"  data-info=({id:33532,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33533,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Is file (pointed to) executable? */
</div></div></div><div class="div_line"  data-info=({id:33534,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isExecutable</span>;
</div></div></div><div class="div_line"  data-info=({id:33535,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33536,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Is file (pointed to) setuid? */
</div></div></div><div class="div_line"  data-info=({id:33537,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd member'>isSetuid</span>;
</div></div></div><div class="div_line"  data-info=({id:33538,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33539,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;/* Size of file (pointed to) */
</div></div></div><div class="div_line"  data-info=({id:33540,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned long <span class='ctd member'>size</span>;
</div></div></div><div class="div_line"  data-info=({id:33541,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>fileStatus</span>; 
</div></div></div><div class="div_line"  data-info=({id:33542,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33543,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:33544,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   FUNCTION PROTOTYPES
</div></div></div><div class="div_line"  data-info=({id:33545,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:33546,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void freeRoutineResources (void);
</div></div></div><div class="div_line"  data-info=({id:33547,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void setExecutableName (const char *const path);
</div></div></div><div class="div_line"  data-info=({id:33548,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *getExecutableName (void);
</div></div></div><div class="div_line"  data-info=({id:33549,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *getExecutablePath (void);
</div></div></div><div class="div_line"  data-info=({id:33550,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>error</span> (const errorSelection selection, const char *const format, ...) __printf__ (2, 3);
</div></div></div><div class="div_line"  data-info=({id:33551,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33552,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Memory allocation functions */
</div></div></div><div class="div_line"  data-info=({id:33553,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef NEED_PROTO_MALLOC
</div></div></div><div class="div_line"  data-info=({id:33554,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void *malloc (size_t);
</div></div></div><div class="div_line"  data-info=({id:33555,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void *realloc (void *ptr, size_t);
</div></div></div><div class="div_line"  data-info=({id:33556,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33557,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void *<a href='ctags/routines.c#line236' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eMalloc</a> (const size_t size);
</div></div></div><div class="div_line"  data-info=({id:33558,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void *<a href='ctags/routines.c#line246' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eCalloc</a> (const size_t count, const size_t size);
</div></div></div><div class="div_line"  data-info=({id:33559,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void *<a href='ctags/routines.c#line256' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eRealloc</a> (void *const ptr, const size_t size);
</div></div></div><div class="div_line"  data-info=({id:33560,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/routines.c#line270' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eFree</a> (void *const ptr);
</div></div></div><div class="div_line"  data-info=({id:33561,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33562,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* String manipulation functions */
</div></div></div><div class="div_line"  data-info=({id:33563,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern int <a href='ctags/readtags.c#line105' class='a_code_tag multi_def' data-info='({type:"fncall",tagreg:2})'>struppercmp</a> (const char *s1, const char *s2);
</div></div></div><div class="div_line"  data-info=({id:33564,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern int <a href='ctags/readtags.c#line115' class='a_code_tag multi_def' data-info='({type:"fncall",tagreg:2})'>strnuppercmp</a> (const char *s1, const char *s2, size_t n);
</div></div></div><div class="div_line"  data-info=({id:33565,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/e_djgpp.h#line42' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>HAVE_STRSTR</a>
</div></div></div><div class="div_line"  data-info=({id:33566,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line308' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>strstr</a> (const char *str, const char *substr);
</div></div></div><div class="div_line"  data-info=({id:33567,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33568,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line321' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eStrdup</a> (const char* str);
</div></div></div><div class="div_line"  data-info=({id:33569,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/routines.c#line328' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>toLowerString</a> (char* str);
</div></div></div><div class="div_line"  data-info=({id:33570,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/routines.c#line337' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>toUpperString</a> (char* str);
</div></div></div><div class="div_line"  data-info=({id:33571,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line348' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>newLowerString</a> (const char* str);
</div></div></div><div class="div_line"  data-info=({id:33572,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line360' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>newUpperString</a> (const char* str);
</div></div></div><div class="div_line"  data-info=({id:33573,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33574,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* File system functions */
</div></div></div><div class="div_line"  data-info=({id:33575,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/routines.c#line374' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>setCurrentDirectory</a> (void);
</div></div></div><div class="div_line"  data-info=({id:33576,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern fileStatus *<a href='ctags/routines.c#line418' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eStat</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:33577,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <a href='ctags/routines.c#line452' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eStatFree</a> (fileStatus *status);
</div></div></div><div class="div_line"  data-info=({id:33578,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/routines.c#line461' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>doesFileExist</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:33579,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/routines.c#line467' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isRecursiveLink</a> (const char* const dirName);
</div></div></div><div class="div_line"  data-info=({id:33580,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/routines.c#line541' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isSameFile</a> (const char *const name1, const char *const name2);
</div></div></div><div class="div_line"  data-info=({id:33581,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#if defined(<a href='ctags/e_msoft.h#line64' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>NEED_PROTO_FGETPOS</a>)
</div></div></div><div class="div_line"  data-info=({id:33582,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern int <a href='ctags/routines.c#line494' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>fgetpos</a>  (FILE *stream, <a href='ctags/general.h#line106' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>fpos_t</a> *pos);
</div></div></div><div class="div_line"  data-info=({id:33583,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern int <a href='ctags/routines.c#line505' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>fsetpos</a>  (FILE *stream, <a href='ctags/general.h#line106' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>fpos_t</a> *pos);
</div></div></div><div class="div_line"  data-info=({id:33584,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:33585,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *<a href='ctags/routines.c#line567' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>baseFilename</a> (const char *const filePath);
</div></div></div><div class="div_line"  data-info=({id:33586,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern const char *<a href='ctags/routines.c#line601' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>fileExtension</a> (const char *const fileName);
</div></div></div><div class="div_line"  data-info=({id:33587,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <a href='ctags/routines.c#line620' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>isAbsolutePath</a> (const char *const path);
</div></div></div><div class="div_line"  data-info=({id:33588,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern vString *<a href='ctags/routines.c#line646' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>combinePathAndFile</a> (const char *const path, const char *const file);
</div></div></div><div class="div_line"  data-info=({id:33589,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line715' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>absoluteFilename</a> (const char *file);
</div></div></div><div class="div_line"  data-info=({id:33590,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line791' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>absoluteDirname</a> (char *file);
</div></div></div><div class="div_line"  data-info=({id:33591,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern char* <a href='ctags/routines.c#line812' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>relativeFilename</a> (const char *file, const char *dir);
</div></div></div><div class="div_line"  data-info=({id:33592,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern FILE *<a href='ctags/routines.c#line851' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>tempFile</a> (const char *const mode, char **const pName);
</div></div></div><div class="div_line"  data-info=({id:33593,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33594,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif  /* _ROUTINES_H */
</div></div></div><div class="div_line"  data-info=({id:33595,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:33596,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* vi:set tabstop=4 shiftwidth=4: */
</div></div></div><script>var local_symbol_set='([{name:"FATAL",ln:53},{name:"OUTPUT_PATH_SEPARATOR",ln:40},{name:"OUTPUT_PATH_SEPARATOR",ln:42},{name:"PATH_SEPARATOR",ln:31},{name:"PATH_SEPARATOR",ln:33},{name:"PATH_SEPARATOR",ln:35},{name:"PERROR",ln:53},{name:"WARNING",ln:53},{name:"_ROUTINES_H",ln:12},{name:"eErrorTypes",ln:53},{name:"errorSelection",ln:52},{name:"exists",ln:60},{name:"fileStatus",ln:79},{name:"isDirectory",ln:66},{name:"isExecutable",ln:72},{name:"isNormalFile",ln:69},{name:"isSetuid",ln:75},{name:"isSymbolicLink",ln:63},{name:"name",ln:57},{name:"size",ln:78},{name:"xCalloc",ln:23},{name:"xMalloc",ln:22},{name:"xRealloc",ln:24},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/routines.h"})';
</script>