<div class="div_line"  data-info=({id:40394,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:40395,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   $Id: vstring.c 558 2007-06-15 19:17:02Z elliotth $
</div></div></div><div class="div_line"  data-info=({id:40396,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:40397,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   Copyright (c) 1998-2002, Darren Hiebert
</div></div></div><div class="div_line"  data-info=({id:40398,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:40399,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This source code is released for free distribution under the terms of the
</div></div></div><div class="div_line"  data-info=({id:40400,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   GNU General Public License.
</div></div></div><div class="div_line"  data-info=({id:40401,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*
</div></div></div><div class="div_line"  data-info=({id:40402,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   This module contains functions supporting resizeable strings.
</div></div></div><div class="div_line"  data-info=({id:40403,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:40404,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40405,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:40406,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   INCLUDE FILES
</div></div></div><div class="div_line"  data-info=({id:40407,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:40408,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>general.h</span>"  /* must always come first */
</div></div></div><div class="div_line"  data-info=({id:40409,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40410,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>limits.h</span>&gt;  /* to define INT_MAX */
</div></div></div><div class="div_line"  data-info=({id:40411,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>string.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:40412,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ctype.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:40413,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40414,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>debug.h</span>"
</div></div></div><div class="div_line"  data-info=({id:40415,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>routines.h</span>"
</div></div></div><div class="div_line"  data-info=({id:40416,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>vstring.h</span>"
</div></div></div><div class="div_line"  data-info=({id:40417,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40418,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:40419,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   DATA DEFINITIONS
</div></div></div><div class="div_line"  data-info=({id:40420,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:40421,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static const size_t <span class='ctd gvdef'>vStringInitialSize</span> = 32;
</div></div></div><div class="div_line"  data-info=({id:40422,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40423,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:40424,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   FUNCTION DEFINITIONS
</div></div></div><div class="div_line"  data-info=({id:40425,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:40426,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40427,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>vStringResize</span> (vString *const string, const size_t newSize)
</div></div></div><div class="div_line"  data-info=({id:40428,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40429,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *const newBuffer = xRealloc (string-&gt;buffer, newSize, char);
</div></div></div><div class="div_line"  data-info=({id:40430,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40431,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;size = newSize;
</div></div></div><div class="div_line"  data-info=({id:40432,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;buffer = newBuffer;
</div></div></div><div class="div_line"  data-info=({id:40433,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40434,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40435,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:40436,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*   External interface
</div></div></div><div class="div_line"  data-info=({id:40437,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">*/
</div></div></div><div class="div_line"  data-info=({id:40438,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40439,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern <a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> <span class='ctd fndef'>vStringAutoResize</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40440,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40441,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/main.c#line57' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>boolean</a> ok = <a href='ctags/general.h#line99' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>;
</div></div></div><div class="div_line"  data-info=({id:40442,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40443,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (string-&gt;size &lt;= INT_MAX / 2)
</div></div></div><div class="div_line"  data-info=({id:40444,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40445,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const size_t newSize = string-&gt;size * 2;
</div></div></div><div class="div_line"  data-info=({id:40446,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40447,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line34' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringResize</a> (string, newSize);
</div></div></div><div class="div_line"  data-info=({id:40448,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40449,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return ok;
</div></div></div><div class="div_line"  data-info=({id:40450,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40451,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40452,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringClear</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40453,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40454,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;length = 0;
</div></div></div><div class="div_line"  data-info=({id:40455,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;buffer [0] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40456,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DebugStatement ( memset (string-&gt;buffer, 0, string-&gt;size); )
</div></div></div><div class="div_line"  data-info=({id:40457,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40458,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40459,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringDelete</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40460,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40461,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (string != NULL)
</div></div></div><div class="div_line"  data-info=({id:40462,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40463,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (string-&gt;buffer != NULL)
</div></div></div><div class="div_line"  data-info=({id:40464,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/routines.c#line270' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eFree</a> (string-&gt;buffer);
</div></div></div><div class="div_line"  data-info=({id:40465,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/routines.c#line270' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>eFree</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40466,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40467,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40468,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40469,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern vString *<span class='ctd fndef'>vStringNew</span> (void)
</div></div></div><div class="div_line"  data-info=({id:40470,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40471,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;vString *const string = xMalloc (1, vString);
</div></div></div><div class="div_line"  data-info=({id:40472,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40473,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;length = 0;
</div></div></div><div class="div_line"  data-info=({id:40474,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;size   = <a href='ctags/vstring.c#line28' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>vStringInitialSize</a>;
</div></div></div><div class="div_line"  data-info=({id:40475,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;buffer = xMalloc (string-&gt;size, char);
</div></div></div><div class="div_line"  data-info=({id:40476,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40477,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line59' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringClear</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40478,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40479,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return string;
</div></div></div><div class="div_line"  data-info=({id:40480,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40481,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40482,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ctags/vstring.h#line27' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>VSTRING_PUTC_MACRO</a>
</div></div></div><div class="div_line"  data-info=({id:40483,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringPut</span> (vString *const string, const int c)
</div></div></div><div class="div_line"  data-info=({id:40484,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40485,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (string-&gt;length + 1 == string-&gt;size)  /*  check for buffer overflow */
</div></div></div><div class="div_line"  data-info=({id:40486,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line46' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringAutoResize</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40487,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40488,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;buffer [string-&gt;length] = c;
</div></div></div><div class="div_line"  data-info=({id:40489,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (c != '\0')
</div></div></div><div class="div_line"  data-info=({id:40490,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [++string-&gt;length] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40491,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40492,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:40493,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40494,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringCatS</span> (vString *const string, const char *const s)
</div></div></div><div class="div_line"  data-info=({id:40495,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40496,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#if 1
</div></div></div><div class="div_line"  data-info=({id:40497,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const size_t len = strlen (s);
</div></div></div><div class="div_line"  data-info=({id:40498,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (string-&gt;length + len + 1 &gt;= string-&gt;size)/*  check for buffer overflow */
</div></div></div><div class="div_line"  data-info=({id:40499,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line46' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringAutoResize</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40500,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;strcpy (string-&gt;buffer + string-&gt;length, s);
</div></div></div><div class="div_line"  data-info=({id:40501,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;length += len;
</div></div></div><div class="div_line"  data-info=({id:40502,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#else
</div></div></div><div class="div_line"  data-info=({id:40503,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *p = s;
</div></div></div><div class="div_line"  data-info=({id:40504,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;do
</div></div></div><div class="div_line"  data-info=({id:40505,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line90' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringPut</a> (string, *p);
</div></div></div><div class="div_line"  data-info=({id:40506,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (*p++ != '\0');
</div></div></div><div class="div_line"  data-info=({id:40507,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:40508,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40509,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40510,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern vString *<span class='ctd fndef'>vStringNewCopy</span> (const vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40511,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40512,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;vString *vs = <a href='ctags/vstring.c#line76' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringNew</a> ();
</div></div></div><div class="div_line"  data-info=({id:40513,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line101' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringCatS</a> (vs, string-&gt;buffer);
</div></div></div><div class="div_line"  data-info=({id:40514,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return vs;
</div></div></div><div class="div_line"  data-info=({id:40515,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40516,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40517,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern vString *<span class='ctd fndef'>vStringNewInit</span> (const char *const s)
</div></div></div><div class="div_line"  data-info=({id:40518,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40519,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;vString *vs = <a href='ctags/vstring.c#line76' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringNew</a> ();
</div></div></div><div class="div_line"  data-info=({id:40520,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line101' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringCatS</a> (vs, s);
</div></div></div><div class="div_line"  data-info=({id:40521,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return vs;
</div></div></div><div class="div_line"  data-info=({id:40522,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40523,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40524,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringNCatS</span> (
</div></div></div><div class="div_line"  data-info=({id:40525,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;vString *const string, const char *const s, const size_t length)
</div></div></div><div class="div_line"  data-info=({id:40526,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40527,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *p = s;
</div></div></div><div class="div_line"  data-info=({id:40528,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;size_t remain = length;
</div></div></div><div class="div_line"  data-info=({id:40529,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40530,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (*p != '\0'  &&  remain &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:40531,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40532,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line90' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringPut</a> (string, *p);
</div></div></div><div class="div_line"  data-info=({id:40533,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;--remain;
</div></div></div><div class="div_line"  data-info=({id:40534,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;++p;
</div></div></div><div class="div_line"  data-info=({id:40535,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40536,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;vStringTerminate (string);
</div></div></div><div class="div_line"  data-info=({id:40537,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40538,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40539,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  Strip trailing newline from string.
</div></div></div><div class="div_line"  data-info=({id:40540,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:40541,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringStripNewline</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40542,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40543,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const size_t final = string-&gt;length - 1;
</div></div></div><div class="div_line"  data-info=({id:40544,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (string-&gt;buffer [final] == '\n')
</div></div></div><div class="div_line"  data-info=({id:40545,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40546,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [final] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40547,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;length--;
</div></div></div><div class="div_line"  data-info=({id:40548,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40549,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40550,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40551,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  Strip leading white space from string.
</div></div></div><div class="div_line"  data-info=({id:40552,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:40553,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringStripLeading</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40554,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40555,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (isspace ((int) string-&gt;buffer [0]) && string-&gt;length &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:40556,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40557,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t i;
</div></div></div><div class="div_line"  data-info=({id:40558,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;for (i = 1  ;  i &lt; string-&gt;length  ;  ++i)
</div></div></div><div class="div_line"  data-info=({id:40559,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [i - 1] = string-&gt;buffer [i];
</div></div></div><div class="div_line"  data-info=({id:40560,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;--string-&gt;length;
</div></div></div><div class="div_line"  data-info=({id:40561,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [string-&gt;length] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40562,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40563,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40564,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40565,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  Strip trailing white space from string.
</div></div></div><div class="div_line"  data-info=({id:40566,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:40567,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringStripTrailing</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40568,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40569,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (isspace ((int) string-&gt;buffer [string-&gt;length - 1]) &&
</div></div></div><div class="div_line"  data-info=({id:40570,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;   string-&gt;length &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:40571,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40572,ln:179}) id=l179><div class="dl_wrapper"><a name=line179 onclick='overload_click(this)' class="a_ln">179<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;length--;
</div></div></div><div class="div_line"  data-info=({id:40573,ln:180}) id=l180><div class="dl_wrapper"><a name=line180 onclick='overload_click(this)' class="a_ln">180<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [string-&gt;length] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40574,ln:181}) id=l181><div class="dl_wrapper"><a name=line181 onclick='overload_click(this)' class="a_ln">181<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40575,ln:182}) id=l182><div class="dl_wrapper"><a name=line182 onclick='overload_click(this)' class="a_ln">182<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40576,ln:183}) id=l183><div class="dl_wrapper"><a name=line183 onclick='overload_click(this)' class="a_ln">183<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40577,ln:184}) id=l184><div class="dl_wrapper"><a name=line184 onclick='overload_click(this)' class="a_ln">184<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*  Chop last character from string.
</div></div></div><div class="div_line"  data-info=({id:40578,ln:185}) id=l185><div class="dl_wrapper"><a name=line185 onclick='overload_click(this)' class="a_ln">185<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:40579,ln:186}) id=l186><div class="dl_wrapper"><a name=line186 onclick='overload_click(this)' class="a_ln">186<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringChop</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40580,ln:187}) id=l187><div class="dl_wrapper"><a name=line187 onclick='overload_click(this)' class="a_ln">187<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40581,ln:188}) id=l188><div class="dl_wrapper"><a name=line188 onclick='overload_click(this)' class="a_ln">188<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (string-&gt;length &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:40582,ln:189}) id=l189><div class="dl_wrapper"><a name=line189 onclick='overload_click(this)' class="a_ln">189<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40583,ln:190}) id=l190><div class="dl_wrapper"><a name=line190 onclick='overload_click(this)' class="a_ln">190<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;--string-&gt;length;
</div></div></div><div class="div_line"  data-info=({id:40584,ln:191}) id=l191><div class="dl_wrapper"><a name=line191 onclick='overload_click(this)' class="a_ln">191<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;string-&gt;buffer [string-&gt;length] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40585,ln:192}) id=l192><div class="dl_wrapper"><a name=line192 onclick='overload_click(this)' class="a_ln">192<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40586,ln:193}) id=l193><div class="dl_wrapper"><a name=line193 onclick='overload_click(this)' class="a_ln">193<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40587,ln:194}) id=l194><div class="dl_wrapper"><a name=line194 onclick='overload_click(this)' class="a_ln">194<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40588,ln:195}) id=l195><div class="dl_wrapper"><a name=line195 onclick='overload_click(this)' class="a_ln">195<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringCopyS</span> (vString *const string, const char *const s)
</div></div></div><div class="div_line"  data-info=({id:40589,ln:196}) id=l196><div class="dl_wrapper"><a name=line196 onclick='overload_click(this)' class="a_ln">196<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40590,ln:197}) id=l197><div class="dl_wrapper"><a name=line197 onclick='overload_click(this)' class="a_ln">197<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line59' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringClear</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40591,ln:198}) id=l198><div class="dl_wrapper"><a name=line198 onclick='overload_click(this)' class="a_ln">198<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line101' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringCatS</a> (string, s);
</div></div></div><div class="div_line"  data-info=({id:40592,ln:199}) id=l199><div class="dl_wrapper"><a name=line199 onclick='overload_click(this)' class="a_ln">199<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40593,ln:200}) id=l200><div class="dl_wrapper"><a name=line200 onclick='overload_click(this)' class="a_ln">200<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40594,ln:201}) id=l201><div class="dl_wrapper"><a name=line201 onclick='overload_click(this)' class="a_ln">201<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringNCopyS</span> (
</div></div></div><div class="div_line"  data-info=({id:40595,ln:202}) id=l202><div class="dl_wrapper"><a name=line202 onclick='overload_click(this)' class="a_ln">202<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;vString *const string, const char *const s, const size_t length)
</div></div></div><div class="div_line"  data-info=({id:40596,ln:203}) id=l203><div class="dl_wrapper"><a name=line203 onclick='overload_click(this)' class="a_ln">203<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40597,ln:204}) id=l204><div class="dl_wrapper"><a name=line204 onclick='overload_click(this)' class="a_ln">204<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line59' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringClear</a> (string);
</div></div></div><div class="div_line"  data-info=({id:40598,ln:205}) id=l205><div class="dl_wrapper"><a name=line205 onclick='overload_click(this)' class="a_ln">205<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line131' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringNCatS</a> (string, s, length);
</div></div></div><div class="div_line"  data-info=({id:40599,ln:206}) id=l206><div class="dl_wrapper"><a name=line206 onclick='overload_click(this)' class="a_ln">206<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40600,ln:207}) id=l207><div class="dl_wrapper"><a name=line207 onclick='overload_click(this)' class="a_ln">207<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40601,ln:208}) id=l208><div class="dl_wrapper"><a name=line208 onclick='overload_click(this)' class="a_ln">208<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringCopyToLower</span> (vString *const dest, const vString *const src)
</div></div></div><div class="div_line"  data-info=({id:40602,ln:209}) id=l209><div class="dl_wrapper"><a name=line209 onclick='overload_click(this)' class="a_ln">209<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40603,ln:210}) id=l210><div class="dl_wrapper"><a name=line210 onclick='overload_click(this)' class="a_ln">210<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const size_t length = src-&gt;length;
</div></div></div><div class="div_line"  data-info=({id:40604,ln:211}) id=l211><div class="dl_wrapper"><a name=line211 onclick='overload_click(this)' class="a_ln">211<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *s = src-&gt;buffer;
</div></div></div><div class="div_line"  data-info=({id:40605,ln:212}) id=l212><div class="dl_wrapper"><a name=line212 onclick='overload_click(this)' class="a_ln">212<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *d;
</div></div></div><div class="div_line"  data-info=({id:40606,ln:213}) id=l213><div class="dl_wrapper"><a name=line213 onclick='overload_click(this)' class="a_ln">213<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;size_t i;
</div></div></div><div class="div_line"  data-info=({id:40607,ln:214}) id=l214><div class="dl_wrapper"><a name=line214 onclick='overload_click(this)' class="a_ln">214<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40608,ln:215}) id=l215><div class="dl_wrapper"><a name=line215 onclick='overload_click(this)' class="a_ln">215<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (dest-&gt;size &lt; src-&gt;size)
</div></div></div><div class="div_line"  data-info=({id:40609,ln:216}) id=l216><div class="dl_wrapper"><a name=line216 onclick='overload_click(this)' class="a_ln">216<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ctags/vstring.c#line34' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>vStringResize</a> (dest, src-&gt;size);
</div></div></div><div class="div_line"  data-info=({id:40610,ln:217}) id=l217><div class="dl_wrapper"><a name=line217 onclick='overload_click(this)' class="a_ln">217<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;d = dest-&gt;buffer;
</div></div></div><div class="div_line"  data-info=({id:40611,ln:218}) id=l218><div class="dl_wrapper"><a name=line218 onclick='overload_click(this)' class="a_ln">218<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;for (i = 0  ;  i &lt; length  ;  ++i)
</div></div></div><div class="div_line"  data-info=({id:40612,ln:219}) id=l219><div class="dl_wrapper"><a name=line219 onclick='overload_click(this)' class="a_ln">219<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;{
</div></div></div><div class="div_line"  data-info=({id:40613,ln:220}) id=l220><div class="dl_wrapper"><a name=line220 onclick='overload_click(this)' class="a_ln">220<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int c = s [i];
</div></div></div><div class="div_line"  data-info=({id:40614,ln:221}) id=l221><div class="dl_wrapper"><a name=line221 onclick='overload_click(this)' class="a_ln">221<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40615,ln:222}) id=l222><div class="dl_wrapper"><a name=line222 onclick='overload_click(this)' class="a_ln">222<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;d [i] = tolower (c);
</div></div></div><div class="div_line"  data-info=({id:40616,ln:223}) id=l223><div class="dl_wrapper"><a name=line223 onclick='overload_click(this)' class="a_ln">223<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:40617,ln:224}) id=l224><div class="dl_wrapper"><a name=line224 onclick='overload_click(this)' class="a_ln">224<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;d [i] = '\0';
</div></div></div><div class="div_line"  data-info=({id:40618,ln:225}) id=l225><div class="dl_wrapper"><a name=line225 onclick='overload_click(this)' class="a_ln">225<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40619,ln:226}) id=l226><div class="dl_wrapper"><a name=line226 onclick='overload_click(this)' class="a_ln">226<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40620,ln:227}) id=l227><div class="dl_wrapper"><a name=line227 onclick='overload_click(this)' class="a_ln">227<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern void <span class='ctd fndef'>vStringSetLength</span> (vString *const string)
</div></div></div><div class="div_line"  data-info=({id:40621,ln:228}) id=l228><div class="dl_wrapper"><a name=line228 onclick='overload_click(this)' class="a_ln">228<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:40622,ln:229}) id=l229><div class="dl_wrapper"><a name=line229 onclick='overload_click(this)' class="a_ln">229<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;string-&gt;length = strlen (string-&gt;buffer);
</div></div></div><div class="div_line"  data-info=({id:40623,ln:230}) id=l230><div class="dl_wrapper"><a name=line230 onclick='overload_click(this)' class="a_ln">230<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:40624,ln:231}) id=l231><div class="dl_wrapper"><a name=line231 onclick='overload_click(this)' class="a_ln">231<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:40625,ln:232}) id=l232><div class="dl_wrapper"><a name=line232 onclick='overload_click(this)' class="a_ln">232<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* vi:set tabstop=4 shiftwidth=4: */
</div></div></div><script>var local_symbol_set='([{name:"vStringAutoResize",ln:46},{name:"vStringCatS",ln:101},{name:"vStringChop",ln:186},{name:"vStringClear",ln:59},{name:"vStringCopyS",ln:195},{name:"vStringCopyToLower",ln:208},{name:"vStringDelete",ln:66},{name:"vStringInitialSize",ln:28},{name:"vStringNCatS",ln:131},{name:"vStringNCopyS",ln:201},{name:"vStringNew",ln:76},{name:"vStringNewCopy",ln:117},{name:"vStringNewInit",ln:124},{name:"vStringPut",ln:90},{name:"vStringResize",ln:34},{name:"vStringSetLength",ln:227},{name:"vStringStripLeading",ln:160},{name:"vStringStripNewline",ln:148},{name:"vStringStripTrailing",ln:174},])';
var file_info = '({folder:0,project:"ctags5_8", table:"comments", topdir:"ctags_5_8", path:"ctags/vstring.c"})';
</script>