<div class="div_line"  data-info=({id:98241,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:98242,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98243,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:98244,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98245,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2010  Nokia Corporation and/or its subsidiary(-ies).
</div></div></div><div class="div_line"  data-info=({id:98246,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2010  ProFUSION embedded systems.
</div></div></div><div class="div_line"  data-info=({id:98247,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98248,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:98249,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:98250,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:98251,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98252,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:98253,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:98254,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:98255,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:98256,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98257,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:98258,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:98259,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:98260,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:98261,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:98262,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98263,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ofono/include/location-reporting.h#line24' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>__OFONO_LOCATION_REPORTING_H</a>
</div></div></div><div class="div_line"  data-info=({id:98264,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>__OFONO_LOCATION_REPORTING_H</span>
</div></div></div><div class="div_line"  data-info=({id:98265,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98266,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:98267,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern "C" {
</div></div></div><div class="div_line"  data-info=({id:98268,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:98269,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98270,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/types.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:98271,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98272,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a>;
</div></div></div><div class="div_line"  data-info=({id:98273,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98274,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">enum <span class='ctd enumdef'>ofono_location_reporting_type</span> {
</div></div></div><div class="div_line"  data-info=({id:98275,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;OFONO_LOCATION_REPORTING_TYPE_NMEA = 0,
</div></div></div><div class="div_line"  data-info=({id:98276,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:98277,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98278,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_location_reporting_enable_cb_t)(
</div></div></div><div class="div_line"  data-info=({id:98279,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:98280,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd typedef'>fd</span>, void *data);
</div></div></div><div class="div_line"  data-info=({id:98281,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_location_reporting_disable_cb_t)(
</div></div></div><div class="div_line"  data-info=({id:98282,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:98283,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:98284,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98285,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ofono_location_reporting_driver</span> {
</div></div></div><div class="div_line"  data-info=({id:98286,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>;
</div></div></div><div class="div_line"  data-info=({id:98287,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;enum <a href='ofono/include/location-reporting.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting_type</a> <a href='ofono/drivers/mbmmodem/location-reporting.c#line236' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:178})'>type</a>;
</div></div></div><div class="div_line"  data-info=({id:98288,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<a href='ofono/drivers/atmodem/call-barring.c#line217' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>probe</a>)(struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *lr, unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:98289,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:98290,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/call-barring.c#line218' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>remove</a>)(struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *lr);
</div></div></div><div class="div_line"  data-info=({id:98291,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/mbmmodem/location-reporting.c#line239' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:37})'>enable</a>)(struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *lr,
</div></div></div><div class="div_line"  data-info=({id:98292,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_location_reporting_enable_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:98293,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/mbmmodem/location-reporting.c#line240' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:37})'>disable</a>)(struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *lr,
</div></div></div><div class="div_line"  data-info=({id:98294,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_location_reporting_disable_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:98295,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:98296,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98297,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int ofono_location_reporting_driver_register(
</div></div></div><div class="div_line"  data-info=({id:98298,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/location-reporting.h#line45' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting_driver</a> *d);
</div></div></div><div class="div_line"  data-info=({id:98299,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void ofono_location_reporting_driver_unregister(
</div></div></div><div class="div_line"  data-info=({id:98300,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/location-reporting.h#line45' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting_driver</a> *d);
</div></div></div><div class="div_line"  data-info=({id:98301,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98302,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *ofono_location_reporting_create(
</div></div></div><div class="div_line"  data-info=({id:98303,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>,
</div></div></div><div class="div_line"  data-info=({id:98304,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:98305,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:98306,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98307,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a>_register(struct ofono_location_reporting *lr);
</div></div></div><div class="div_line"  data-info=({id:98308,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a>_remove(struct ofono_location_reporting *lr);
</div></div></div><div class="div_line"  data-info=({id:98309,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98310,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a>_set_data(struct ofono_location_reporting *lr,
</div></div></div><div class="div_line"  data-info=({id:98311,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:98312,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void *<a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a>_get_data(struct ofono_location_reporting *lr);
</div></div></div><div class="div_line"  data-info=({id:98313,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98314,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *ofono_location_reporting_get_modem(
</div></div></div><div class="div_line"  data-info=({id:98315,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/src/location-reporting.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_location_reporting</a> *lr);
</div></div></div><div class="div_line"  data-info=({id:98316,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98317,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:98318,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:98319,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:98320,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:98321,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif /* __OFONO_LOCATION_REPORTING_H */
</div></div></div><script>var local_symbol_set='([{name:"OFONO_LOCATION_REPORTING_TYPE_NMEA",ln:35},{name:"__OFONO_LOCATION_REPORTING_H",ln:24},{name:"disable",ln:53},{name:"enable",ln:51},{name:"name",ln:46},{name:"ofono_location_reporting_disable_cb_t",ln:41},{name:"ofono_location_reporting_driver",ln:45},{name:"ofono_location_reporting_enable_cb_t",ln:38},{name:"ofono_location_reporting_type",ln:34},{name:"probe",ln:48},{name:"remove",ln:50},{name:"type",ln:47},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/include/location-reporting.h"})';
</script>