<div class="div_line"  data-info=({id:96542,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:96543,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96544,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:96545,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96546,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:96547,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96548,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:96549,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:96550,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:96551,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96552,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:96553,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:96554,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:96555,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:96556,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96557,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:96558,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:96559,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:96560,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96561,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:96562,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96563,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ofono/include/netreg.h#line23' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>__OFONO_NETREG_H</a>
</div></div></div><div class="div_line"  data-info=({id:96564,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>__OFONO_NETREG_H</span>
</div></div></div><div class="div_line"  data-info=({id:96565,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96566,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:96567,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern "C" {
</div></div></div><div class="div_line"  data-info=({id:96568,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:96569,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96570,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/types.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:96571,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96572,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>;
</div></div></div><div class="div_line"  data-info=({id:96573,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96574,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Theoretical limit is 16, but each GSM char can be encoded into
</div></div></div><div class="div_line"  data-info=({id:96575,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  * 3 UTF8 characters resulting in 16*3=48 chars
</div></div></div><div class="div_line"  data-info=({id:96576,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *   */
</div></div></div><div class="div_line"  data-info=({id:96577,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>OFONO_MAX_OPERATOR_NAME_LENGTH</span> 63
</div></div></div><div class="div_line"  data-info=({id:96578,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96579,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ofono_network_operator</span> {
</div></div></div><div class="div_line"  data-info=({id:96580,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char <a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>[<a href='ofono/include/netreg.h#line36' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>OFONO_MAX_OPERATOR_NAME_LENGTH</a> + 1];
</div></div></div><div class="div_line"  data-info=({id:96581,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char mcc[<a href='ofono/include/types.h#line40' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>OFONO_MAX_MCC_LENGTH</a> + 1];
</div></div></div><div class="div_line"  data-info=({id:96582,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char <a href='ofono/unit/test-stkutil.c#line18267' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:14})'>mnc</a>[<a href='ofono/include/types.h#line41' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>OFONO_MAX_MNC_LENGTH</a> + 1];
</div></div></div><div class="div_line"  data-info=({id:96583,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int <a href='ofono/unit/test-stkutil.c#line13084' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:11})'>status</a>;
</div></div></div><div class="div_line"  data-info=({id:96584,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int tech;
</div></div></div><div class="div_line"  data-info=({id:96585,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:96586,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96587,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_netreg_operator_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:96588,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <span class='ctd typedef'>ofono_network_operator</span> *op,
</div></div></div><div class="div_line"  data-info=({id:96589,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:96590,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96591,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_netreg_register_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:96592,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:96593,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96594,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_netreg_operator_list_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:96595,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd typedef'>total</span>,
</div></div></div><div class="div_line"  data-info=({id:96596,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <span class='ctd typedef'>ofono_network_operator</span> *list,
</div></div></div><div class="div_line"  data-info=({id:96597,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:96598,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96599,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_netreg_status_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:96600,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd typedef'>status</span>, int lac, int ci, int tech,
</div></div></div><div class="div_line"  data-info=({id:96601,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:96602,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96603,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_netreg_strength_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:96604,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd typedef'>strength</span>, void *data);
</div></div></div><div class="div_line"  data-info=({id:96605,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96606,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Network related functions, including registration status, operator selection
</div></div></div><div class="div_line"  data-info=({id:96607,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * and signal strength indicators.
</div></div></div><div class="div_line"  data-info=({id:96608,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:96609,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * It is up to the plugin to implement CSQ polling if the modem does not support
</div></div></div><div class="div_line"  data-info=({id:96610,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * vendor extensions for signal strength notification.
</div></div></div><div class="div_line"  data-info=({id:96611,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:96612,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ofono_netreg_driver</span> {
</div></div></div><div class="div_line"  data-info=({id:96613,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>;
</div></div></div><div class="div_line"  data-info=({id:96614,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<a href='ofono/drivers/atmodem/call-barring.c#line217' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>probe</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg, unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:96615,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96616,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/call-barring.c#line218' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>remove</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg);
</div></div></div><div class="div_line"  data-info=({id:96617,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2024' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>registration_status</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96618,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_status_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96619,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2025' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>current_operator</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96620,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_operator_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96621,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2026' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>list_operators</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96622,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_operator_list_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96623,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2027' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>register_auto</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96624,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_register_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96625,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2028' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>register_manual</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96626,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *mcc, const char *<a href='ofono/unit/test-stkutil.c#line18267' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:14})'>mnc</a>,
</div></div></div><div class="div_line"  data-info=({id:96627,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_register_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96628,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/network-registration.c#line2029' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>strength</a>)(struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *netreg,
</div></div></div><div class="div_line"  data-info=({id:96629,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_netreg_strength_cb_t, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96630,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:96631,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96632,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_strength_notify(struct ofono_netreg *netreg, int <a href='ofono/drivers/atmodem/network-registration.c#line2029' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>strength</a>);
</div></div></div><div class="div_line"  data-info=({id:96633,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_status_notify(struct ofono_netreg *netreg, int <a href='ofono/unit/test-stkutil.c#line13084' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:11})'>status</a>,
</div></div></div><div class="div_line"  data-info=({id:96634,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int lac, int <a href='ofono/unit/test-stkutil.c#line18270' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>ci</a>, int tech);
</div></div></div><div class="div_line"  data-info=({id:96635,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_time_notify(struct ofono_netreg *netreg,
</div></div></div><div class="div_line"  data-info=({id:96636,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/include/types.h#line101' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_network_time</a> *<a href='ofono/gdbus/mainloop.c#line33' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>info</a>);
</div></div></div><div class="div_line"  data-info=({id:96637,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96638,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/include/netreg.h#line71' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg_driver</a>_register(const struct ofono_netreg_driver *d);
</div></div></div><div class="div_line"  data-info=({id:96639,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/include/netreg.h#line71' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg_driver</a>_unregister(const struct ofono_netreg_driver *d);
</div></div></div><div class="div_line"  data-info=({id:96640,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96641,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a> *ofono_netreg_create(struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>,
</div></div></div><div class="div_line"  data-info=({id:96642,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:96643,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>,
</div></div></div><div class="div_line"  data-info=({id:96644,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96645,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96646,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_register(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96647,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_remove(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96648,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96649,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_set_data(struct ofono_netreg *netreg, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:96650,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void *<a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_data(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96651,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96652,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_location(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96653,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_cellid(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96654,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_status(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96655,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_technology(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96656,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">const char *<a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_mcc(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96657,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">const char *<a href='ofono/src/network.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_netreg</a>_get_mnc(struct ofono_netreg *netreg);
</div></div></div><div class="div_line"  data-info=({id:96658,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96659,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:96660,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:96661,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:96662,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:96663,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif /* __OFONO_NETREG_H */
</div></div></div><script>var local_symbol_set='([{name:"OFONO_MAX_OPERATOR_NAME_LENGTH",ln:36},{name:"__OFONO_NETREG_H",ln:23},{name:"current_operator",ln:78},{name:"list_operators",ln:80},{name:"mcc",ln:40},{name:"mnc",ln:41},{name:"name",ln:39},{name:"name",ln:72},{name:"ofono_netreg_driver",ln:71},{name:"ofono_netreg_operator_cb_t",ln:46},{name:"ofono_netreg_operator_list_cb_t",ln:53},{name:"ofono_netreg_register_cb_t",ln:50},{name:"ofono_netreg_status_cb_t",ln:58},{name:"ofono_netreg_strength_cb_t",ln:62},{name:"ofono_network_operator",ln:38},{name:"probe",ln:73},{name:"register_auto",ln:82},{name:"register_manual",ln:84},{name:"registration_status",ln:76},{name:"remove",ln:75},{name:"status",ln:42},{name:"strength",ln:87},{name:"tech",ln:43},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/include/netreg.h"})';
</script>