<div class="div_line"  data-info=({id:97384,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:97385,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97386,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:97387,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97388,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:97389,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97390,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:97391,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:97392,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:97393,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97394,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:97395,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:97396,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:97397,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:97398,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97399,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:97400,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:97401,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:97402,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97403,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:97404,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97405,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ofono/include/voicecall.h#line23' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>__OFONO_VOICECALL_H</a>
</div></div></div><div class="div_line"  data-info=({id:97406,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>__OFONO_VOICECALL_H</span>
</div></div></div><div class="div_line"  data-info=({id:97407,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97408,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:97409,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern "C" {
</div></div></div><div class="div_line"  data-info=({id:97410,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:97411,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97412,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/types.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:97413,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97414,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>;
</div></div></div><div class="div_line"  data-info=({id:97415,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97416,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*ofono_voicecall_cb_t)(const struct <span class='ctd typedef'>ofono_error</span> *error,
</div></div></div><div class="div_line"  data-info=({id:97417,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>data</span>);
</div></div></div><div class="div_line"  data-info=({id:97418,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97419,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Voice call related functionality, including ATD, ATA, +CHLD, CTFR, CLCC
</div></div></div><div class="div_line"  data-info=({id:97420,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * and VTS.
</div></div></div><div class="div_line"  data-info=({id:97421,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:97422,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * It is up to the plugin to implement polling of CLCC if the modem does
</div></div></div><div class="div_line"  data-info=({id:97423,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * not support vendor extensions for call progress indication.
</div></div></div><div class="div_line"  data-info=({id:97424,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:97425,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ofono_voicecall_driver</span> {
</div></div></div><div class="div_line"  data-info=({id:97426,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>;
</div></div></div><div class="div_line"  data-info=({id:97427,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<a href='ofono/drivers/atmodem/call-barring.c#line217' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>probe</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc, unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:97428,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97429,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/call-barring.c#line218' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:129})'>remove</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc);
</div></div></div><div class="div_line"  data-info=({id:97430,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97431,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* According to 22.030 the dial is expected to do the following:
</div></div></div><div class="div_line"  data-info=({id:97432,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * - If an there is an existing active call(s), and the dial is
</div></div></div><div class="div_line"  data-info=({id:97433,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   successful, the active calls are automatically put on hold.
</div></div></div><div class="div_line"  data-info=({id:97434,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   Driver must take special care to put the call on hold before
</div></div></div><div class="div_line"  data-info=({id:97435,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   returning from atd call.
</div></div></div><div class="div_line"  data-info=({id:97436,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *
</div></div></div><div class="div_line"  data-info=({id:97437,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * - The dial has no affect on the state of the waiting call,
</div></div></div><div class="div_line"  data-info=({id:97438,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   if the hardware does not support this, then it is better
</div></div></div><div class="div_line"  data-info=({id:97439,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   to return an error here.  No special handling of the
</div></div></div><div class="div_line"  data-info=({id:97440,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *   waiting call is performed by the core
</div></div></div><div class="div_line"  data-info=({id:97441,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97442,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1163' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:8})'>dial</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97443,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/types.h#line76' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_phone_number</a> *<a href='ofono/unit/test-stkutil.c#line10856' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:57})'>number</a>,
</div></div></div><div class="div_line"  data-info=({id:97444,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;enum <a href='ofono/include/types.h#line46' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_clir_option</a> clir, ofono_voicecall_cb_t cb,
</div></div></div><div class="div_line"  data-info=({id:97445,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97446,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* Answers an incoming call, this usually corresponds to ATA */
</div></div></div><div class="div_line"  data-info=({id:97447,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1164' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>answer</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97448,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97449,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97450,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* Hangs up active, dialing, alerting or incoming calls */
</div></div></div><div class="div_line"  data-info=({id:97451,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/calypsomodem/voicecall.c#line412' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>hangup_active</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97452,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97453,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* Hangs up all calls except waiting calls */
</div></div></div><div class="div_line"  data-info=({id:97454,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1165' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>hangup_all</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97455,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97456,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97457,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Holds all active calls and answers waiting call.  If there is
</div></div></div><div class="div_line"  data-info=({id:97458,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * no waiting calls, retrieves held call.  This usually
</div></div></div><div class="div_line"  data-info=({id:97459,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * corresponds to +CHLD=2
</div></div></div><div class="div_line"  data-info=({id:97460,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97461,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1166' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>hold_all_active</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97462,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97463,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* Releases all held calls, this usually corresponds to +CHLD=0*/
</div></div></div><div class="div_line"  data-info=({id:97464,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1167' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>release_all_held</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97465,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97466,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97467,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Sets the UDUB condition on a waiting call.  This usually
</div></div></div><div class="div_line"  data-info=({id:97468,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * corresponds to +CHLD=0
</div></div></div><div class="div_line"  data-info=({id:97469,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97470,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1168' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>set_udub</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97471,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97472,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97473,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Releases all active calls and accepts a possible waiting call.
</div></div></div><div class="div_line"  data-info=({id:97474,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * This usually corresponds to +CHLD=1
</div></div></div><div class="div_line"  data-info=({id:97475,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97476,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1169' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>release_all_active</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97477,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97478,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97479,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Releases a specific call given by id.  This usually corresponds to
</div></div></div><div class="div_line"  data-info=({id:97480,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * +CHLD=1X.  In 3GPP this command is only guaranteed to affect active
</div></div></div><div class="div_line"  data-info=({id:97481,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * calls.  Plugins are encouraged to implement this using vendor
</div></div></div><div class="div_line"  data-info=({id:97482,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * commands that can also affect held calls
</div></div></div><div class="div_line"  data-info=({id:97483,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97484,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1170' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>release_specific</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:97485,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97486,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97487,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Breaks out a party given by id from a multiparty call.  This
</div></div></div><div class="div_line"  data-info=({id:97488,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * usually corresponds to +CHLD=2X
</div></div></div><div class="div_line"  data-info=({id:97489,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97490,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1171' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>private_chat</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:97491,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97492,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97493,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Joins held and active calls together into a multiparty call.  This
</div></div></div><div class="div_line"  data-info=({id:97494,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * usually corresponds to +CHLD=3
</div></div></div><div class="div_line"  data-info=({id:97495,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97496,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>create_multiparty</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97497,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97498,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97499,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Connects two calls together and disconnects from both calls.  This
</div></div></div><div class="div_line"  data-info=({id:97500,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * usually corresponds to +CHLD=4
</div></div></div><div class="div_line"  data-info=({id:97501,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97502,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1173' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>transfer</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97503,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97504,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97505,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Deflects an incoming or waiting call to a given number.  This
</div></div></div><div class="div_line"  data-info=({id:97506,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * usually corresponds to +CTFR
</div></div></div><div class="div_line"  data-info=({id:97507,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97508,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1174' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>deflect</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97509,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/types.h#line76' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_phone_number</a> *ph,
</div></div></div><div class="div_line"  data-info=({id:97510,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97511,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:97512,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * This is equivalent to +CHLD=2 but does not affect a possible
</div></div></div><div class="div_line"  data-info=({id:97513,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * waiting call.
</div></div></div><div class="div_line"  data-info=({id:97514,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:97515,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1175' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>swap_without_accept</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc,
</div></div></div><div class="div_line"  data-info=({id:97516,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97517,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<a href='ofono/drivers/atmodem/voicecall.c#line1176' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>send_tones</a>)(struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *vc, const char *tones,
</div></div></div><div class="div_line"  data-info=({id:97518,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_voicecall_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97519,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:97520,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97521,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_en_list_notify(struct ofono_voicecall *vc,
</div></div></div><div class="div_line"  data-info=({id:97522,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;char **nw_en_list);
</div></div></div><div class="div_line"  data-info=({id:97523,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97524,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_notify(struct ofono_voicecall *vc,
</div></div></div><div class="div_line"  data-info=({id:97525,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/types.h#line89' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_call</a> *call);
</div></div></div><div class="div_line"  data-info=({id:97526,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_disconnected(struct ofono_voicecall *vc, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:97527,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;enum <a href='ofono/include/types.h#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_disconnect_reason</a> reason,
</div></div></div><div class="div_line"  data-info=({id:97528,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/types.h#line68' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_error</a> *<a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>);
</div></div></div><div class="div_line"  data-info=({id:97529,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97530,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:97531,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * For those protocols where MPTY creation happens outside of oFono's control,
</div></div></div><div class="div_line"  data-info=({id:97532,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * e.g. Bluetooth Handsfree, set the hint of the MPTY call list by passing
</div></div></div><div class="div_line"  data-info=({id:97533,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> * in a bitmask of ids participating in the MPTY call
</div></div></div><div class="div_line"  data-info=({id:97534,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:97535,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_mpty_hint(struct ofono_voicecall *vc, unsigned int ids);
</div></div></div><div class="div_line"  data-info=({id:97536,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97537,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/include/voicecall.h#line42' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall_driver</a>_register(const struct ofono_voicecall_driver *d);
</div></div></div><div class="div_line"  data-info=({id:97538,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/include/voicecall.h#line42' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall_driver</a>_unregister(const struct ofono_voicecall_driver *d);
</div></div></div><div class="div_line"  data-info=({id:97539,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97540,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a> *ofono_voicecall_create(struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>,
</div></div></div><div class="div_line"  data-info=({id:97541,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:97542,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97543,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97544,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_register(struct ofono_voicecall *vc);
</div></div></div><div class="div_line"  data-info=({id:97545,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_remove(struct ofono_voicecall *vc);
</div></div></div><div class="div_line"  data-info=({id:97546,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97547,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_set_data(struct ofono_voicecall *vc, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:97548,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void *<a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_get_data(struct ofono_voicecall *vc);
</div></div></div><div class="div_line"  data-info=({id:97549,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_get_next_callid(struct ofono_voicecall *vc);
</div></div></div><div class="div_line"  data-info=({id:97550,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97551,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_ssn_mo_notify(struct ofono_voicecall *vc, unsigned int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:97552,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int code, int index);
</div></div></div><div class="div_line"  data-info=({id:97553,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/voicecall.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_voicecall</a>_ssn_mt_notify(struct ofono_voicecall *vc, unsigned int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:97554,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int code, int index,
</div></div></div><div class="div_line"  data-info=({id:97555,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/types.h#line76' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_phone_number</a> *ph);
</div></div></div><div class="div_line"  data-info=({id:97556,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97557,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:97558,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:97559,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:97560,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:97561,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif /* __OFONO_VOICECALL_H */
</div></div></div><script>var local_symbol_set='([{name:"__OFONO_VOICECALL_H",ln:23},{name:"answer",ln:64},{name:"create_multiparty",ln:113},{name:"deflect",ln:125},{name:"dial",ln:59},{name:"hangup_active",ln:68},{name:"hangup_all",ln:71},{name:"hold_all_active",ln:78},{name:"name",ln:43},{name:"ofono_voicecall_cb_t",ln:33},{name:"ofono_voicecall_driver",ln:42},{name:"private_chat",ln:107},{name:"probe",ln:44},{name:"release_all_active",ln:93},{name:"release_all_held",ln:81},{name:"release_specific",ln:101},{name:"remove",ln:46},{name:"send_tones",ln:134},{name:"set_udub",ln:87},{name:"swap_without_accept",ln:132},{name:"transfer",ln:119},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/include/voicecall.h"})';
</script>