<div class="div_line"  data-info=({id:22937,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:22938,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22939,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:22940,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22941,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2011-2012  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:22942,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22943,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:22944,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:22945,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:22946,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22947,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:22948,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:22949,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:22950,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:22951,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22952,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:22953,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:22954,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:22955,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:22956,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:22957,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22958,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef HAVE_CONFIG_H
</div></div></div><div class="div_line"  data-info=({id:22959,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>config.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:22960,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:22961,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22962,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/log.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:22963,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/modem.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:22964,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/radio-settings.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:22965,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22966,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>qmi.h</span>"
</div></div></div><div class="div_line"  data-info=({id:22967,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>nas.h</span>"
</div></div></div><div class="div_line"  data-info=({id:22968,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22969,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>qmimodem.h</span>"
</div></div></div><div class="div_line"  data-info=({id:22970,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22971,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>settings_data</span> {
</div></div></div><div class="div_line"  data-info=({id:22972,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/qmimodem/qmi.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>qmi_service</a> *<span class='ctd member'>nas</span>;
</div></div></div><div class="div_line"  data-info=({id:22973,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;uint16_t <span class='ctd member'>major</span>;
</div></div></div><div class="div_line"  data-info=({id:22974,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;uint16_t <span class='ctd member'>minor</span>;
</div></div></div><div class="div_line"  data-info=({id:22975,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:22976,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22977,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>create_nas_cb</span>(struct qmi_service *service, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:22978,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:22979,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/radio-settings.c#line40' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_radio_settings</a> *rs = user_data;
</div></div></div><div class="div_line"  data-info=({id:22980,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/isimodem/call-settings.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>settings_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/radio-settings.c#line735' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_get_data</a>(rs);
</div></div></div><div class="div_line"  data-info=({id:22981,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22982,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:22983,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22984,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!service) {
</div></div></div><div class="div_line"  data-info=({id:22985,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Failed to <a href='ofono/drivers/atmodem/ussd.c#line334' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:6})'>request</a> NAS service");
</div></div></div><div class="div_line"  data-info=({id:22986,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line724' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_remove</a>(rs);
</div></div></div><div class="div_line"  data-info=({id:22987,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:22988,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:22989,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22990,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/drivers/qmimodem/qmi.c#line1799' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>qmi_service_get_version</a>(service, &<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;major, &data-&gt;<a href='ofono/drivers/isimodem/infoserver.c#line50' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>minor</a>)) {
</div></div></div><div class="div_line"  data-info=({id:22991,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Failed to get NAS service version");
</div></div></div><div class="div_line"  data-info=({id:22992,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line724' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_remove</a>(rs);
</div></div></div><div class="div_line"  data-info=({id:22993,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:22994,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:22995,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22996,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;nas = <a href='ofono/drivers/qmimodem/qmi.c#line1752' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>qmi_service_ref</a>(service);
</div></div></div><div class="div_line"  data-info=({id:22997,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:22998,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line704' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_register</a>(rs);
</div></div></div><div class="div_line"  data-info=({id:22999,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:23000,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23001,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>qmi_radio_settings_probe</span>(struct ofono_radio_settings *rs,
</div></div></div><div class="div_line"  data-info=({id:23002,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned int vendor, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:23003,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:23004,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/qmimodem/qmi.c#line42' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>qmi_device</a> *device = user_data;
</div></div></div><div class="div_line"  data-info=({id:23005,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/isimodem/call-settings.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>settings_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:23006,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23007,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:23008,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23009,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = g_new0(struct <a href='ofono/drivers/isimodem/call-settings.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>settings_data</a>, 1);
</div></div></div><div class="div_line"  data-info=({id:23010,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23011,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line729' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_set_data</a>(rs, <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:23012,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23013,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/drivers/qmimodem/qmi.c#line1669' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>qmi_service_create</a>(device, <a href='ofono/drivers/qmimodem/qmi.h#line28' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>QMI_SERVICE_NAS</a>, create_nas_cb, rs, NULL);
</div></div></div><div class="div_line"  data-info=({id:23014,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23015,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:23016,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23017,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:23018,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23019,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>qmi_radio_settings_remove</span>(struct ofono_radio_settings *rs)
</div></div></div><div class="div_line"  data-info=({id:23020,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:23021,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/isimodem/call-settings.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>settings_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/radio-settings.c#line735' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_get_data</a>(rs);
</div></div></div><div class="div_line"  data-info=({id:23022,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23023,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:23024,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23025,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line729' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_set_data</a>(rs, NULL);
</div></div></div><div class="div_line"  data-info=({id:23026,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23027,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/drivers/qmimodem/qmi.c#line2057' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>qmi_service_unregister_all</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;nas);
</div></div></div><div class="div_line"  data-info=({id:23028,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23029,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/drivers/qmimodem/qmi.c#line1762' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>qmi_service_unref</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;nas);
</div></div></div><div class="div_line"  data-info=({id:23030,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23031,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:23032,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:23033,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23034,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static struct <a href='ofono/include/radio-settings.h#line83' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_radio_settings_driver</a> <span class='ctd gvdef'>driver</span> = {
</div></div></div><div class="div_line"  data-info=({id:23035,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= "qmimodem",
</div></div></div><div class="div_line"  data-info=({id:23036,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>probe</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= qmi_radio_settings_probe,
</div></div></div><div class="div_line"  data-info=({id:23037,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>remove</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= qmi_radio_settings_remove,
</div></div></div><div class="div_line"  data-info=({id:23038,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:23039,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23040,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <span class='ctd fndef'>qmi_radio_settings_init</span>(void)
</div></div></div><div class="div_line"  data-info=({id:23041,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:23042,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line620' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_driver_register</a>(&<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>);
</div></div></div><div class="div_line"  data-info=({id:23043,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:23044,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:23045,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <span class='ctd fndef'>qmi_radio_settings_exit</span>(void)
</div></div></div><div class="div_line"  data-info=({id:23046,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:23047,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/radio-settings.c#line632' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_radio_settings_driver_unregister</a>(&<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>);
</div></div></div><div class="div_line"  data-info=({id:23048,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><script>var local_symbol_set='([{name:"create_nas_cb",ln:41},{name:"driver",ln:98},{name:"major",ln:37},{name:"minor",ln:38},{name:"nas",ln:36},{name:"qmi_radio_settings_exit",ln:109},{name:"qmi_radio_settings_init",ln:104},{name:"qmi_radio_settings_probe",ln:65},{name:"qmi_radio_settings_remove",ln:83},{name:"settings_data",ln:35},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/drivers/qmimodem/radio-settings.c"})';
</script>