<div class="div_line"  data-info=({id:15294,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:15295,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15296,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:15297,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15298,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:15299,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15300,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:15301,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:15302,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:15303,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15304,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:15305,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:15306,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:15307,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:15308,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15309,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:15310,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:15311,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:15312,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:15313,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:15314,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15315,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef HAVE_CONFIG_H
</div></div></div><div class="div_line"  data-info=({id:15316,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>config.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15317,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:15318,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15319,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>_GNU_SOURCE</span>
</div></div></div><div class="div_line"  data-info=({id:15320,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>string.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15321,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>stdio.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15322,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15323,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>glib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15324,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15325,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/log.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15326,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/modem.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15327,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/cbs.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:15328,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>util.h</span>"
</div></div></div><div class="div_line"  data-info=({id:15329,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15330,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>gatchat.h</span>"
</div></div></div><div class="div_line"  data-info=({id:15331,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>gatresult.h</span>"
</div></div></div><div class="div_line"  data-info=({id:15332,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15333,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>atmodem.h</span>"
</div></div></div><div class="div_line"  data-info=({id:15334,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>vendor.h</span>"
</div></div></div><div class="div_line"  data-info=({id:15335,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15336,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static const char *<span class='ctd gvdef'>none_prefix</span>[] = { NULL };
</div></div></div><div class="div_line"  data-info=({id:15337,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static const char *<span class='ctd gvdef'>cscb_prefix</span>[] = { "+CSCB:", NULL };
</div></div></div><div class="div_line"  data-info=({id:15338,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15339,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>cbs_data</span> {
</div></div></div><div class="div_line"  data-info=({id:15340,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *<span class='ctd member'>chat</span>;
</div></div></div><div class="div_line"  data-info=({id:15341,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int <span class='ctd member'>vendor</span>;
</div></div></div><div class="div_line"  data-info=({id:15342,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:15343,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15344,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cbm_notify</span>(GAtResult *result, gpointer user_data)
</div></div></div><div class="div_line"  data-info=({id:15345,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15346,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/cbs.c#line54' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_cbs</a> *<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a> = user_data;
</div></div></div><div class="div_line"  data-info=({id:15347,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *hexpdu;
</div></div></div><div class="div_line"  data-info=({id:15348,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int pdulen;
</div></div></div><div class="div_line"  data-info=({id:15349,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtResultIter iter;
</div></div></div><div class="div_line"  data-info=({id:15350,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned char pdu[88];
</div></div></div><div class="div_line"  data-info=({id:15351,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;long hexpdulen;
</div></div></div><div class="div_line"  data-info=({id:15352,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15353,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:15354,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15355,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatresult.c#line33' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_init</a>(&iter, <a href='ofono/unit/test-stkutil.c#line16244' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:176})'>result</a>);
</div></div></div><div class="div_line"  data-info=({id:15356,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15357,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/gatchat/gatresult.c#line42' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_next</a>(&iter, "+CBM:"))
</div></div></div><div class="div_line"  data-info=({id:15358,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15359,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15360,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/gatchat/gatresult.c#line259' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_next_number</a>(&iter, &pdulen))
</div></div></div><div class="div_line"  data-info=({id:15361,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15362,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15363,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (pdulen != 88) {
</div></div></div><div class="div_line"  data-info=({id:15364,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Got a CBM <a href='ofono/src/message.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>message</a> with invalid PDU size!");
</div></div></div><div class="div_line"  data-info=({id:15365,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15366,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:15367,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15368,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;hexpdu = <a href='ofono/gatchat/gatresult.c#line506' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_pdu</a>(<a href='ofono/unit/test-stkutil.c#line16244' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:176})'>result</a>);
</div></div></div><div class="div_line"  data-info=({id:15369,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (hexpdu == NULL) {
</div></div></div><div class="div_line"  data-info=({id:15370,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Got a CBM, but no PDU.  Are we in <a href='ofono/unit/test-cdmasms.c#line65' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:443})'>text</a> mode?");
</div></div></div><div class="div_line"  data-info=({id:15371,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15372,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:15373,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15374,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("Got new Cell Broadcast via CBM: %s, %d", hexpdu, pdulen);
</div></div></div><div class="div_line"  data-info=({id:15375,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15376,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/src/util.c#line881' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>decode_hex_own_buf</a>(hexpdu, -1, &hexpdulen, 0, pdu) == NULL) {
</div></div></div><div class="div_line"  data-info=({id:15377,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Unable to hex-decode the PDU");
</div></div></div><div class="div_line"  data-info=({id:15378,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15379,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:15380,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15381,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (hexpdulen != pdulen) {
</div></div></div><div class="div_line"  data-info=({id:15382,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("hexpdu length not equal to reported pdu length");
</div></div></div><div class="div_line"  data-info=({id:15383,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15384,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:15385,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15386,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line174' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_notify</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>, pdu, pdulen);
</div></div></div><div class="div_line"  data-info=({id:15387,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15388,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15389,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cscb_set_cb</span>(gboolean ok, GAtResult *result, gpointer user_data)
</div></div></div><div class="div_line"  data-info=({id:15390,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15391,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/atutil.h#line86' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>cb_data</a> *cbd = user_data;
</div></div></div><div class="div_line"  data-info=({id:15392,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;ofono_cbs_set_cb_t cb = cbd-&gt;cb;
</div></div></div><div class="div_line"  data-info=({id:15393,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/include/types.h#line68' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_error</a> <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:15394,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15395,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/drivers/atmodem/atutil.c#line53' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>decode_at_error</a>(&<a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>, <a href='ofono/gatchat/gatresult.c#line498' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_final_response</a>(<a href='ofono/unit/test-stkutil.c#line16244' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:176})'>result</a>));
</div></div></div><div class="div_line"  data-info=({id:15396,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15397,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;cb(&<a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>, cbd-&gt;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:15398,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15399,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15400,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cbs_set_topics</span>(struct ofono_cbs *cbs, const char *topics,
</div></div></div><div class="div_line"  data-info=({id:15401,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_cbs_set_cb_t cb, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:15402,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15403,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/cbs.c#line1128' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_get_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15404,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/atutil.h#line86' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>cb_data</a> *cbd = <a href='ofono/drivers/atmodem/atutil.h#line92' class='a_code_tag multi_def' data-info='({type:"fncall",tagreg:3})'>cb_data_new</a>(cb, user_data);
</div></div></div><div class="div_line"  data-info=({id:15405,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char *buf;
</div></div></div><div class="div_line"  data-info=({id:15406,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>;
</div></div></div><div class="div_line"  data-info=({id:15407,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15408,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:15409,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15410,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* For the Qualcomm based devices it is required to clear
</div></div></div><div class="div_line"  data-info=({id:15411,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * the list of topics first.  Otherwise setting the new
</div></div></div><div class="div_line"  data-info=({id:15412,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * topic ranges will fail.
</div></div></div><div class="div_line"  data-info=({id:15413,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:15414,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;switch (<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;vendor) {
</div></div></div><div class="div_line"  data-info=({id:15415,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;case OFONO_VENDOR_GOBI:
</div></div></div><div class="div_line"  data-info=({id:15416,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;case OFONO_VENDOR_QUALCOMM_MSM:
</div></div></div><div class="div_line"  data-info=({id:15417,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, "AT+CSCB=0", <a href='ofono/drivers/atmodem/call-barring.c#line43' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:68})'>none_prefix</a>,
</div></div></div><div class="div_line"  data-info=({id:15418,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;NULL, NULL, NULL);
</div></div></div><div class="div_line"  data-info=({id:15419,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;break;
</div></div></div><div class="div_line"  data-info=({id:15420,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;default:
</div></div></div><div class="div_line"  data-info=({id:15421,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;break;
</div></div></div><div class="div_line"  data-info=({id:15422,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:15423,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15424,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;buf = g_strdup_printf("AT+CSCB=0,\"%s\"", topics);
</div></div></div><div class="div_line"  data-info=({id:15425,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15426,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a> = <a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, buf, <a href='ofono/drivers/atmodem/call-barring.c#line43' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:68})'>none_prefix</a>,
</div></div></div><div class="div_line"  data-info=({id:15427,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;at_cscb_set_cb, cbd, g_free);
</div></div></div><div class="div_line"  data-info=({id:15428,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15429,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(buf);
</div></div></div><div class="div_line"  data-info=({id:15430,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15431,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a> &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:15432,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15433,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15434,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(cbd);
</div></div></div><div class="div_line"  data-info=({id:15435,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15436,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;CALLBACK_WITH_FAILURE(cb, user_data);
</div></div></div><div class="div_line"  data-info=({id:15437,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15438,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15439,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cbs_clear_topics</span>(struct ofono_cbs *cbs,
</div></div></div><div class="div_line"  data-info=({id:15440,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_cbs_set_cb_t cb, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:15441,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15442,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/cbs.c#line1128' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_get_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15443,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/atutil.h#line86' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>cb_data</a> *cbd = <a href='ofono/drivers/atmodem/atutil.h#line92' class='a_code_tag multi_def' data-info='({type:"fncall",tagreg:3})'>cb_data_new</a>(cb, user_data);
</div></div></div><div class="div_line"  data-info=({id:15444,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15445,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:15446,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15447,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, "AT+CSCB=0", <a href='ofono/drivers/atmodem/call-barring.c#line43' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:68})'>none_prefix</a>,
</div></div></div><div class="div_line"  data-info=({id:15448,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;at_cscb_set_cb, cbd, g_free) &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:15449,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15450,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15451,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(cbd);
</div></div></div><div class="div_line"  data-info=({id:15452,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15453,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;CALLBACK_WITH_FAILURE(cb, user_data);
</div></div></div><div class="div_line"  data-info=({id:15454,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15455,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15456,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cbs_register</span>(gboolean ok, GAtResult *result, gpointer user)
</div></div></div><div class="div_line"  data-info=({id:15457,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15458,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/cbs.c#line54' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_cbs</a> *<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a> = user;
</div></div></div><div class="div_line"  data-info=({id:15459,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/cbs.c#line1128' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_get_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15460,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15461,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* This driver assumes that something else will properly setup
</div></div></div><div class="div_line"  data-info=({id:15462,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * CNMI notifications to deliver CBS broadcasts via +CBM.  We do
</div></div></div><div class="div_line"  data-info=({id:15463,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * not setup CNMI string ourselves here to avoid race conditions
</div></div></div><div class="div_line"  data-info=({id:15464,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * with the SMS driver which will also be setting the CNMI itself
</div></div></div><div class="div_line"  data-info=({id:15465,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; *
</div></div></div><div class="div_line"  data-info=({id:15466,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * The default SMS driver will setup the CNMI for +CBM delivery
</div></div></div><div class="div_line"  data-info=({id:15467,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * appropriately for us
</div></div></div><div class="div_line"  data-info=({id:15468,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:15469,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1543' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_register</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, "+CBM:", at_cbm_notify, <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>, <a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:15470,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15471,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line1084' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_register</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15472,ln:179}) id=l179><div class="dl_wrapper"><a name=line179 onclick='overload_click(this)' class="a_ln">179<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15473,ln:180}) id=l180><div class="dl_wrapper"><a name=line180 onclick='overload_click(this)' class="a_ln">180<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15474,ln:181}) id=l181><div class="dl_wrapper"><a name=line181 onclick='overload_click(this)' class="a_ln">181<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cscb_support_cb</span>(gboolean ok, GAtResult *result, gpointer user)
</div></div></div><div class="div_line"  data-info=({id:15475,ln:182}) id=l182><div class="dl_wrapper"><a name=line182 onclick='overload_click(this)' class="a_ln">182<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15476,ln:183}) id=l183><div class="dl_wrapper"><a name=line183 onclick='overload_click(this)' class="a_ln">183<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/cbs.c#line54' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_cbs</a> *<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a> = user;
</div></div></div><div class="div_line"  data-info=({id:15477,ln:184}) id=l184><div class="dl_wrapper"><a name=line184 onclick='overload_click(this)' class="a_ln">184<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/cbs.c#line1128' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_get_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15478,ln:185}) id=l185><div class="dl_wrapper"><a name=line185 onclick='overload_click(this)' class="a_ln">185<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gint range[2];
</div></div></div><div class="div_line"  data-info=({id:15479,ln:186}) id=l186><div class="dl_wrapper"><a name=line186 onclick='overload_click(this)' class="a_ln">186<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtResultIter iter;
</div></div></div><div class="div_line"  data-info=({id:15480,ln:187}) id=l187><div class="dl_wrapper"><a name=line187 onclick='overload_click(this)' class="a_ln">187<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15481,ln:188}) id=l188><div class="dl_wrapper"><a name=line188 onclick='overload_click(this)' class="a_ln">188<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!ok)
</div></div></div><div class="div_line"  data-info=({id:15482,ln:189}) id=l189><div class="dl_wrapper"><a name=line189 onclick='overload_click(this)' class="a_ln">189<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;goto <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:15483,ln:190}) id=l190><div class="dl_wrapper"><a name=line190 onclick='overload_click(this)' class="a_ln">190<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15484,ln:191}) id=l191><div class="dl_wrapper"><a name=line191 onclick='overload_click(this)' class="a_ln">191<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatresult.c#line33' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_init</a>(&iter, <a href='ofono/unit/test-stkutil.c#line16244' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:176})'>result</a>);
</div></div></div><div class="div_line"  data-info=({id:15485,ln:192}) id=l192><div class="dl_wrapper"><a name=line192 onclick='overload_click(this)' class="a_ln">192<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15486,ln:193}) id=l193><div class="dl_wrapper"><a name=line193 onclick='overload_click(this)' class="a_ln">193<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/gatchat/gatresult.c#line42' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_next</a>(&iter, "+CSCB:"))
</div></div></div><div class="div_line"  data-info=({id:15487,ln:194}) id=l194><div class="dl_wrapper"><a name=line194 onclick='overload_click(this)' class="a_ln">194<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;goto <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:15488,ln:195}) id=l195><div class="dl_wrapper"><a name=line195 onclick='overload_click(this)' class="a_ln">195<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15489,ln:196}) id=l196><div class="dl_wrapper"><a name=line196 onclick='overload_click(this)' class="a_ln">196<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/gatchat/gatresult.c#line442' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_open_list</a>(&iter))
</div></div></div><div class="div_line"  data-info=({id:15490,ln:197}) id=l197><div class="dl_wrapper"><a name=line197 onclick='overload_click(this)' class="a_ln">197<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;goto <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:15491,ln:198}) id=l198><div class="dl_wrapper"><a name=line198 onclick='overload_click(this)' class="a_ln">198<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15492,ln:199}) id=l199><div class="dl_wrapper"><a name=line199 onclick='overload_click(this)' class="a_ln">199<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;while (<a href='ofono/gatchat/gatresult.c#line325' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_next_range</a>(&iter, &range[0], &range[1]))
</div></div></div><div class="div_line"  data-info=({id:15493,ln:200}) id=l200><div class="dl_wrapper"><a name=line200 onclick='overload_click(this)' class="a_ln">200<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;;
</div></div></div><div class="div_line"  data-info=({id:15494,ln:201}) id=l201><div class="dl_wrapper"><a name=line201 onclick='overload_click(this)' class="a_ln">201<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15495,ln:202}) id=l202><div class="dl_wrapper"><a name=line202 onclick='overload_click(this)' class="a_ln">202<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (!<a href='ofono/gatchat/gatresult.c#line471' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_iter_close_list</a>(&iter))
</div></div></div><div class="div_line"  data-info=({id:15496,ln:203}) id=l203><div class="dl_wrapper"><a name=line203 onclick='overload_click(this)' class="a_ln">203<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;goto <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:15497,ln:204}) id=l204><div class="dl_wrapper"><a name=line204 onclick='overload_click(this)' class="a_ln">204<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15498,ln:205}) id=l205><div class="dl_wrapper"><a name=line205 onclick='overload_click(this)' class="a_ln">205<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, "AT+CSCB=0", <a href='ofono/drivers/atmodem/call-barring.c#line43' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:68})'>none_prefix</a>,
</div></div></div><div class="div_line"  data-info=({id:15499,ln:206}) id=l206><div class="dl_wrapper"><a name=line206 onclick='overload_click(this)' class="a_ln">206<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;at_<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>_register, cbs, NULL) &gt; 0)
</div></div></div><div class="div_line"  data-info=({id:15500,ln:207}) id=l207><div class="dl_wrapper"><a name=line207 onclick='overload_click(this)' class="a_ln">207<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:15501,ln:208}) id=l208><div class="dl_wrapper"><a name=line208 onclick='overload_click(this)' class="a_ln">208<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15502,ln:209}) id=l209><div class="dl_wrapper"><a name=line209 onclick='overload_click(this)' class="a_ln">209<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"><a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>:
</div></div></div><div class="div_line"  data-info=({id:15503,ln:210}) id=l210><div class="dl_wrapper"><a name=line210 onclick='overload_click(this)' class="a_ln">210<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("CSCB not supported");
</div></div></div><div class="div_line"  data-info=({id:15504,ln:211}) id=l211><div class="dl_wrapper"><a name=line211 onclick='overload_click(this)' class="a_ln">211<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line1118' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_remove</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15505,ln:212}) id=l212><div class="dl_wrapper"><a name=line212 onclick='overload_click(this)' class="a_ln">212<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15506,ln:213}) id=l213><div class="dl_wrapper"><a name=line213 onclick='overload_click(this)' class="a_ln">213<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15507,ln:214}) id=l214><div class="dl_wrapper"><a name=line214 onclick='overload_click(this)' class="a_ln">214<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>at_cbs_probe</span>(struct ofono_cbs *cbs, unsigned int vendor,
</div></div></div><div class="div_line"  data-info=({id:15508,ln:215}) id=l215><div class="dl_wrapper"><a name=line215 onclick='overload_click(this)' class="a_ln">215<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *user)
</div></div></div><div class="div_line"  data-info=({id:15509,ln:216}) id=l216><div class="dl_wrapper"><a name=line216 onclick='overload_click(this)' class="a_ln">216<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15510,ln:217}) id=l217><div class="dl_wrapper"><a name=line217 onclick='overload_click(this)' class="a_ln">217<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = user;
</div></div></div><div class="div_line"  data-info=({id:15511,ln:218}) id=l218><div class="dl_wrapper"><a name=line218 onclick='overload_click(this)' class="a_ln">218<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:15512,ln:219}) id=l219><div class="dl_wrapper"><a name=line219 onclick='overload_click(this)' class="a_ln">219<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15513,ln:220}) id=l220><div class="dl_wrapper"><a name=line220 onclick='overload_click(this)' class="a_ln">220<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = g_new0(struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a>, 1);
</div></div></div><div class="div_line"  data-info=({id:15514,ln:221}) id=l221><div class="dl_wrapper"><a name=line221 onclick='overload_click(this)' class="a_ln">221<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat = <a href='ofono/gatchat/gatchat.c#line1321' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_clone</a>(chat);
</div></div></div><div class="div_line"  data-info=({id:15515,ln:222}) id=l222><div class="dl_wrapper"><a name=line222 onclick='overload_click(this)' class="a_ln">222<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;vendor = vendor;
</div></div></div><div class="div_line"  data-info=({id:15516,ln:223}) id=l223><div class="dl_wrapper"><a name=line223 onclick='overload_click(this)' class="a_ln">223<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15517,ln:224}) id=l224><div class="dl_wrapper"><a name=line224 onclick='overload_click(this)' class="a_ln">224<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line1123' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_set_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>, <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:15518,ln:225}) id=l225><div class="dl_wrapper"><a name=line225 onclick='overload_click(this)' class="a_ln">225<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15519,ln:226}) id=l226><div class="dl_wrapper"><a name=line226 onclick='overload_click(this)' class="a_ln">226<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, "AT+CSCB=?", <a href='ofono/drivers/atmodem/cbs.c#line44' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cscb_prefix</a>,
</div></div></div><div class="div_line"  data-info=({id:15520,ln:227}) id=l227><div class="dl_wrapper"><a name=line227 onclick='overload_click(this)' class="a_ln">227<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;at_cscb_support_cb, <a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:15521,ln:228}) id=l228><div class="dl_wrapper"><a name=line228 onclick='overload_click(this)' class="a_ln">228<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15522,ln:229}) id=l229><div class="dl_wrapper"><a name=line229 onclick='overload_click(this)' class="a_ln">229<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:15523,ln:230}) id=l230><div class="dl_wrapper"><a name=line230 onclick='overload_click(this)' class="a_ln">230<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15524,ln:231}) id=l231><div class="dl_wrapper"><a name=line231 onclick='overload_click(this)' class="a_ln">231<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15525,ln:232}) id=l232><div class="dl_wrapper"><a name=line232 onclick='overload_click(this)' class="a_ln">232<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>at_cbs_remove</span>(struct ofono_cbs *cbs)
</div></div></div><div class="div_line"  data-info=({id:15526,ln:233}) id=l233><div class="dl_wrapper"><a name=line233 onclick='overload_click(this)' class="a_ln">233<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15527,ln:234}) id=l234><div class="dl_wrapper"><a name=line234 onclick='overload_click(this)' class="a_ln">234<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/cbs.c#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>cbs_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/cbs.c#line1128' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_get_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>);
</div></div></div><div class="div_line"  data-info=({id:15528,ln:235}) id=l235><div class="dl_wrapper"><a name=line235 onclick='overload_click(this)' class="a_ln">235<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15529,ln:236}) id=l236><div class="dl_wrapper"><a name=line236 onclick='overload_click(this)' class="a_ln">236<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line1123' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_set_data</a>(<a href='ofono/src/smsutil.h#line389' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>cbs</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:15530,ln:237}) id=l237><div class="dl_wrapper"><a name=line237 onclick='overload_click(this)' class="a_ln">237<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15531,ln:238}) id=l238><div class="dl_wrapper"><a name=line238 onclick='overload_click(this)' class="a_ln">238<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1409' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_unref</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:15532,ln:239}) id=l239><div class="dl_wrapper"><a name=line239 onclick='overload_click(this)' class="a_ln">239<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:15533,ln:240}) id=l240><div class="dl_wrapper"><a name=line240 onclick='overload_click(this)' class="a_ln">240<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15534,ln:241}) id=l241><div class="dl_wrapper"><a name=line241 onclick='overload_click(this)' class="a_ln">241<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15535,ln:242}) id=l242><div class="dl_wrapper"><a name=line242 onclick='overload_click(this)' class="a_ln">242<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static struct <a href='ofono/include/cbs.h#line36' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_cbs_driver</a> <span class='ctd gvdef'>driver</span> = {
</div></div></div><div class="div_line"  data-info=({id:15536,ln:243}) id=l243><div class="dl_wrapper"><a name=line243 onclick='overload_click(this)' class="a_ln">243<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a> = "atmodem",
</div></div></div><div class="div_line"  data-info=({id:15537,ln:244}) id=l244><div class="dl_wrapper"><a name=line244 onclick='overload_click(this)' class="a_ln">244<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>probe</span> = at_cbs_probe,
</div></div></div><div class="div_line"  data-info=({id:15538,ln:245}) id=l245><div class="dl_wrapper"><a name=line245 onclick='overload_click(this)' class="a_ln">245<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>remove</span> = at_cbs_remove,
</div></div></div><div class="div_line"  data-info=({id:15539,ln:246}) id=l246><div class="dl_wrapper"><a name=line246 onclick='overload_click(this)' class="a_ln">246<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>set_topics</span> = at_cbs_set_topics,
</div></div></div><div class="div_line"  data-info=({id:15540,ln:247}) id=l247><div class="dl_wrapper"><a name=line247 onclick='overload_click(this)' class="a_ln">247<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>clear_topics</span> = at_cbs_clear_topics,
</div></div></div><div class="div_line"  data-info=({id:15541,ln:248}) id=l248><div class="dl_wrapper"><a name=line248 onclick='overload_click(this)' class="a_ln">248<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:15542,ln:249}) id=l249><div class="dl_wrapper"><a name=line249 onclick='overload_click(this)' class="a_ln">249<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15543,ln:250}) id=l250><div class="dl_wrapper"><a name=line250 onclick='overload_click(this)' class="a_ln">250<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <span class='ctd fndef'>at_cbs_init</span>(void)
</div></div></div><div class="div_line"  data-info=({id:15544,ln:251}) id=l251><div class="dl_wrapper"><a name=line251 onclick='overload_click(this)' class="a_ln">251<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15545,ln:252}) id=l252><div class="dl_wrapper"><a name=line252 onclick='overload_click(this)' class="a_ln">252<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line563' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_driver_register</a>(&<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>);
</div></div></div><div class="div_line"  data-info=({id:15546,ln:253}) id=l253><div class="dl_wrapper"><a name=line253 onclick='overload_click(this)' class="a_ln">253<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:15547,ln:254}) id=l254><div class="dl_wrapper"><a name=line254 onclick='overload_click(this)' class="a_ln">254<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:15548,ln:255}) id=l255><div class="dl_wrapper"><a name=line255 onclick='overload_click(this)' class="a_ln">255<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <span class='ctd fndef'>at_cbs_exit</span>(void)
</div></div></div><div class="div_line"  data-info=({id:15549,ln:256}) id=l256><div class="dl_wrapper"><a name=line256 onclick='overload_click(this)' class="a_ln">256<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:15550,ln:257}) id=l257><div class="dl_wrapper"><a name=line257 onclick='overload_click(this)' class="a_ln">257<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cbs.c#line575' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cbs_driver_unregister</a>(&<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>);
</div></div></div><div class="div_line"  data-info=({id:15551,ln:258}) id=l258><div class="dl_wrapper"><a name=line258 onclick='overload_click(this)' class="a_ln">258<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><script>var local_symbol_set='([{name:"_GNU_SOURCE",ln:26},{name:"at_cbm_notify",ln:51},{name:"at_cbs_clear_topics",ln:146},{name:"at_cbs_exit",ln:255},{name:"at_cbs_init",ln:250},{name:"at_cbs_probe",ln:214},{name:"at_cbs_register",ln:163},{name:"at_cbs_remove",ln:232},{name:"at_cbs_set_topics",ln:107},{name:"at_cscb_set_cb",ln:96},{name:"at_cscb_support_cb",ln:181},{name:"cbs_data",ln:46},{name:"chat",ln:47},{name:"cscb_prefix",ln:44},{name:"driver",ln:242},{name:"none_prefix",ln:43},{name:"vendor",ln:48},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/drivers/atmodem/cbs.c"})';
</script>