<div class="div_line"  data-info=({id:128124,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:128125,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128126,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:128127,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128128,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2009-2010  Nokia Corporation and/or its subsidiary(-ies).
</div></div></div><div class="div_line"  data-info=({id:128129,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128130,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:128131,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:128132,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:128133,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128134,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:128135,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:128136,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:128137,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:128138,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128139,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:128140,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:128141,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:128142,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:128143,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:128144,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128145,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ofono/gisi/modem.h#line23' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>__GISI_MODEM_H</a>
</div></div></div><div class="div_line"  data-info=({id:128146,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>__GISI_MODEM_H</span>
</div></div></div><div class="div_line"  data-info=({id:128147,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128148,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>stdint.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:128149,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128150,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>phonet.h</span>"
</div></div></div><div class="div_line"  data-info=({id:128151,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>message.h</span>"
</div></div></div><div class="div_line"  data-info=({id:128152,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128153,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:128154,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern "C" {
</div></div></div><div class="div_line"  data-info=({id:128155,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:128156,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128157,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">enum <span class='ctd enumdef'>GIsiModemFlags</span> {
</div></div></div><div class="div_line"  data-info=({id:128158,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GISI_MODEM_FLAG_USE_LEGACY_SUBSCRIBE = 1,
</div></div></div><div class="div_line"  data-info=({id:128159,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:128160,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128161,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/gisi/modem.c#line60' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GIsiModem</a>;
</div></div></div><div class="div_line"  data-info=({id:128162,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <a href='ofono/gisi/modem.c#line60' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GIsiModem</a> <span class='ctd typedef'>GIsiModem</span>;
</div></div></div><div class="div_line"  data-info=({id:128163,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128164,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/gisi/modem.c#line75' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GIsiPending</a>;
</div></div></div><div class="div_line"  data-info=({id:128165,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <a href='ofono/gisi/modem.c#line75' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GIsiPending</a> <span class='ctd typedef'>GIsiPending</span>;
</div></div></div><div class="div_line"  data-info=({id:128166,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128167,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*GIsiNotifyFunc)(const <span class='ctd typedef'>GIsiMessage</span> *msg, void *opaque);
</div></div></div><div class="div_line"  data-info=({id:128168,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*GIsiDebugFunc)(const char *<span class='ctd typedef'>fmt</span>, ...);
</div></div></div><div class="div_line"  data-info=({id:128169,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128170,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiModem *g_isi_modem_create(unsigned index);
</div></div></div><div class="div_line"  data-info=({id:128171,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiModem *g_isi_modem_create_by_<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>(const char *name);
</div></div></div><div class="div_line"  data-info=({id:128172,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_modem_destroy(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:128173,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128174,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">unsigned g_isi_modem_index(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:128175,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128176,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">uint8_t g_isi_modem_device(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:128177,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_modem_set_device(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t dev);
</div></div></div><div class="div_line"  data-info=({id:128178,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128179,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_modem_set_trace(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, GIsiNotifyFunc notify);
</div></div></div><div class="div_line"  data-info=({id:128180,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_modem_set_debug(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, GIsiDebugFunc <a href='ofono/gdbus/mainloop.c#line35' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>debug</a>);
</div></div></div><div class="div_line"  data-info=({id:128181,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128182,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void *g_isi_modem_set_userdata(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:128183,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void *g_isi_modem_get_userdata(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:128184,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128185,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">unsigned long g_isi_modem_flags(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:128186,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_modem_set_flags(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, unsigned long <a href='ofono/include/log.h#line49' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>flags</a>);
</div></div></div><div class="div_line"  data-info=({id:128187,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128188,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_request_send(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128189,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const void *__restrict buf, size_t <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>,
</div></div></div><div class="div_line"  data-info=({id:128190,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned timeout, GIsiNotifyFunc notify,
</div></div></div><div class="div_line"  data-info=({id:128191,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128192,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128193,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_request_vsend(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128194,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct iovec *__restrict iov,
</div></div></div><div class="div_line"  data-info=({id:128195,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t iovlen, unsigned timeout,
</div></div></div><div class="div_line"  data-info=({id:128196,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GIsiNotifyFunc notify, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>,
</div></div></div><div class="div_line"  data-info=({id:128197,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128198,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128199,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_request_sendto(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, struct <a href='ofono/gisi/phonet.h#line49' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sockaddr_pn</a> *<a href='ofono/unit/test-stkutil.c#line11939' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:251})'>dst</a>,
</div></div></div><div class="div_line"  data-info=({id:128200,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const void *__restrict buf, size_t <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>,
</div></div></div><div class="div_line"  data-info=({id:128201,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned timeout, GIsiNotifyFunc notify,
</div></div></div><div class="div_line"  data-info=({id:128202,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128203,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128204,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_request_vsendto(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, struct <a href='ofono/gisi/phonet.h#line49' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sockaddr_pn</a> *<a href='ofono/unit/test-stkutil.c#line11939' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:251})'>dst</a>,
</div></div></div><div class="div_line"  data-info=({id:128205,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct iovec *__restrict iov,
</div></div></div><div class="div_line"  data-info=({id:128206,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t iovlen, unsigned timeout,
</div></div></div><div class="div_line"  data-info=({id:128207,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GIsiNotifyFunc notify, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>,
</div></div></div><div class="div_line"  data-info=({id:128208,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128209,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128210,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_modem_send(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128211,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const void *__restrict buf, size_t <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:128212,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128213,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_modem_vsend(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128214,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct iovec *__restrict iov,
</div></div></div><div class="div_line"  data-info=({id:128215,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t iovlen);
</div></div></div><div class="div_line"  data-info=({id:128216,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128217,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_modem_sendto(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, struct <a href='ofono/gisi/phonet.h#line49' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sockaddr_pn</a> *<a href='ofono/unit/test-stkutil.c#line11939' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:251})'>dst</a>,
</div></div></div><div class="div_line"  data-info=({id:128218,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const void *__restrict buf, size_t <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:128219,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128220,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_modem_vsendto(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, struct <a href='ofono/gisi/phonet.h#line49' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sockaddr_pn</a> *<a href='ofono/unit/test-stkutil.c#line11939' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:251})'>dst</a>,
</div></div></div><div class="div_line"  data-info=({id:128221,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct iovec *__restrict iov,
</div></div></div><div class="div_line"  data-info=({id:128222,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t iovlen);
</div></div></div><div class="div_line"  data-info=({id:128223,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128224,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">uint8_t g_isi_request_utid(GIsiPending *resp);
</div></div></div><div class="div_line"  data-info=({id:128225,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128226,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_ind_subscribe(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128227,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;uint8_t <a href='ofono/drivers/mbmmodem/location-reporting.c#line236' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:178})'>type</a>, GIsiNotifyFunc notify,
</div></div></div><div class="div_line"  data-info=({id:128228,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128229,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128230,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_ntf_subscribe(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128231,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;uint8_t <a href='ofono/drivers/mbmmodem/location-reporting.c#line236' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:178})'>type</a>, GIsiNotifyFunc notify,
</div></div></div><div class="div_line"  data-info=({id:128232,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128233,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128234,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_service_bind(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128235,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;uint8_t <a href='ofono/drivers/mbmmodem/location-reporting.c#line236' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:178})'>type</a>, GIsiNotifyFunc notify,
</div></div></div><div class="div_line"  data-info=({id:128236,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128237,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128238,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_response_send(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, const GIsiMessage *<a href='ofono/gisi/netlink.c#line351' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>req</a>,
</div></div></div><div class="div_line"  data-info=({id:128239,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const void *__restrict buf, size_t <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:128240,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128241,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int g_isi_response_vsend(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, const GIsiMessage *<a href='ofono/gisi/netlink.c#line351' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>req</a>,
</div></div></div><div class="div_line"  data-info=({id:128242,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct iovec *__restrict iov,
</div></div></div><div class="div_line"  data-info=({id:128243,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;size_t iovlen);
</div></div></div><div class="div_line"  data-info=({id:128244,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128245,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_pending_remove(GIsiPending *op);
</div></div></div><div class="div_line"  data-info=({id:128246,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_pending_set_owner(GIsiPending *op, gpointer owner);
</div></div></div><div class="div_line"  data-info=({id:128247,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_isi_remove_pending_by_owner(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128248,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;gpointer owner);
</div></div></div><div class="div_line"  data-info=({id:128249,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128250,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GIsiPending *g_isi_resource_ping(GIsiModem *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, uint8_t resource,
</div></div></div><div class="div_line"  data-info=({id:128251,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GIsiNotifyFunc notify, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>,
</div></div></div><div class="div_line"  data-info=({id:128252,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;GDestroyNotify destroy);
</div></div></div><div class="div_line"  data-info=({id:128253,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128254,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:128255,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:128256,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:128257,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:128258,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif /* __GISI_MODEM_H */
</div></div></div><script>var local_symbol_set='([{name:"GISI_MODEM_FLAG_USE_LEGACY_SUBSCRIBE",ln:35},{name:"GIsiDebugFunc",ln:45},{name:"GIsiModem",ln:39},{name:"GIsiModemFlags",ln:34},{name:"GIsiNotifyFunc",ln:44},{name:"GIsiPending",ln:42},{name:"__GISI_MODEM_H",ln:23},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/gisi/modem.h"})';
</script>