<div class="div_line"  data-info=({id:174121,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:174122,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174123,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:174124,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174125,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2010  Gustavo F. Padovan &lt;gustavo@padovan.org&gt;
</div></div></div><div class="div_line"  data-info=({id:174126,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174127,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:174128,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:174129,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:174130,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174131,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:174132,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:174133,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:174134,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:174135,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174136,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:174137,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:174138,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:174139,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:174140,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:174141,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174142,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/modem.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:174143,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/dbus.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:174144,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174145,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define&#160;&#160;&#160;&#160;<span class='ctd macdef'>BLUEZ_SERVICE</span> "org.bluez"
</div></div></div><div class="div_line"  data-info=({id:174146,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define&#160;&#160;&#160;&#160;<span class='ctd macdef'>BLUEZ_MANAGER_INTERFACE</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/plugins/bluez4.h#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>BLUEZ_SERVICE</a> ".Manager"
</div></div></div><div class="div_line"  data-info=({id:174147,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define&#160;&#160;&#160;&#160;<span class='ctd macdef'>BLUEZ_ADAPTER_INTERFACE</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/plugins/bluez4.h#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>BLUEZ_SERVICE</a> ".Adapter"
</div></div></div><div class="div_line"  data-info=({id:174148,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define&#160;&#160;&#160;&#160;<span class='ctd macdef'>BLUEZ_DEVICE_INTERFACE</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/plugins/bluez4.h#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>BLUEZ_SERVICE</a> ".Device"
</div></div></div><div class="div_line"  data-info=({id:174149,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define&#160;&#160;&#160;&#160;<span class='ctd macdef'>BLUEZ_SERVICE_INTERFACE</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/plugins/bluez4.h#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>BLUEZ_SERVICE</a> ".Service"
</div></div></div><div class="div_line"  data-info=({id:174150,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>BLUEZ_SERIAL_INTERFACE</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/plugins/bluez4.h#line25' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>BLUEZ_SERVICE</a> ".Serial"
</div></div></div><div class="div_line"  data-info=({id:174151,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174152,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>DBUS_TIMEOUT</span> 60
</div></div></div><div class="div_line"  data-info=({id:174153,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174154,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>DUN_GW_UUID</span>&#160;&#160;&#160;&#160;"00001103-0000-1000-8000-00805f9b34fb"
</div></div></div><div class="div_line"  data-info=({id:174155,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HFP_AG_UUID</span>&#160;&#160;&#160;&#160;"0000111f-0000-1000-8000-00805f9b34fb"
</div></div></div><div class="div_line"  data-info=({id:174156,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>HFP_HS_UUID</span>&#160;&#160;&#160;&#160;"0000111e-0000-1000-8000-00805f9b34fb"
</div></div></div><div class="div_line"  data-info=({id:174157,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>SAP_UUID</span>&#160;&#160;&#160;&#160;"0000112d-0000-1000-8000-00805f9b34fb"
</div></div></div><div class="div_line"  data-info=({id:174158,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174159,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>bluetooth_profile</span> {
</div></div></div><div class="div_line"  data-info=({id:174160,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<span class='ctd member'>name</span>;
</div></div></div><div class="div_line"  data-info=({id:174161,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<span class='ctd member'>probe</span>)(const char *device, const char *dev_addr,
</div></div></div><div class="div_line"  data-info=({id:174162,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<span class='ctd member'>adapter_addr</span>, const char *alias);
</div></div></div><div class="div_line"  data-info=({id:174163,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>remove</span>)(const char *prefix);
</div></div></div><div class="div_line"  data-info=({id:174164,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>set_alias</span>)(const char *device, const char *);
</div></div></div><div class="div_line"  data-info=({id:174165,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:174166,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174167,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>bluetooth_sap_driver</span> {
</div></div></div><div class="div_line"  data-info=({id:174168,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<span class='ctd member'>name</span>;
</div></div></div><div class="div_line"  data-info=({id:174169,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<span class='ctd member'>enable</span>) (struct ofono_modem *modem, struct ofono_modem *sap_modem,
</div></div></div><div class="div_line"  data-info=({id:174170,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd member'>bt_fd</span>);
</div></div></div><div class="div_line"  data-info=({id:174171,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>pre_sim</span>) (struct ofono_modem *modem);
</div></div></div><div class="div_line"  data-info=({id:174172,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>post_sim</span>) (struct ofono_modem *modem);
</div></div></div><div class="div_line"  data-info=({id:174173,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>set_online</span>) (struct ofono_modem *modem, ofono_bool_t online,
</div></div></div><div class="div_line"  data-info=({id:174174,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_modem_online_<span class='ctd member'>cb</span>_t cb, void *user_data);
</div></div></div><div class="div_line"  data-info=({id:174175,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>post_online</span>) (struct ofono_modem *modem);
</div></div></div><div class="div_line"  data-info=({id:174176,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;int (*<span class='ctd member'>disable</span>) (struct ofono_modem *modem);
</div></div></div><div class="div_line"  data-info=({id:174177,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:174178,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174179,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd gvdef'>server</span>;
</div></div></div><div class="div_line"  data-info=({id:174180,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174181,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>ConnectFunc</span>)(GIOChannel *io, GError *err, gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:174182,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174183,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/bluez4.c#line906' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_get_properties</a>();
</div></div></div><div class="div_line"  data-info=({id:174184,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/plugins/bluez4.c#line912' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_register_uuid</a>(const char *uuid,
</div></div></div><div class="div_line"  data-info=({id:174185,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/bluez4.h#line39' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>bluetooth_profile</a> *profile);
</div></div></div><div class="div_line"  data-info=({id:174186,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/bluez4.c#line924' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_unregister_uuid</a>(const char *uuid);
</div></div></div><div class="div_line"  data-info=({id:174187,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174188,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/btio/btio.c#line80' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>server</a> *<a href='ofono/plugins/bluez4.c#line931' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_register_server</a>(guint8 channel, const char *sdp_record,
</div></div></div><div class="div_line"  data-info=({id:174189,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ConnectFunc cb, gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:174190,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/bluez4.c#line970' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_unregister_server</a>(struct <a href='ofono/btio/btio.c#line80' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>server</a> *server);
</div></div></div><div class="div_line"  data-info=({id:174191,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174192,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/bluez4.c#line68' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_create_path</a>(const char *dev_addr, const char *adapter_addr,
</div></div></div><div class="div_line"  data-info=({id:174193,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;char *buf, int size);
</div></div></div><div class="div_line"  data-info=({id:174194,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174195,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/plugins/bluez4.c#line91' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_send_with_reply</a>(const char *path, const char *interface,
</div></div></div><div class="div_line"  data-info=({id:174196,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *method, DBusPendingCall **call,
</div></div></div><div class="div_line"  data-info=({id:174197,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;DBusPendingCallNotifyFunction cb,
</div></div></div><div class="div_line"  data-info=({id:174198,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *user_data, DBusFreeFunction free_func,
</div></div></div><div class="div_line"  data-info=({id:174199,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int timeout, int <a href='ofono/drivers/mbmmodem/location-reporting.c#line236' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:178})'>type</a>, ...);
</div></div></div><div class="div_line"  data-info=({id:174200,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/bluez4.c#line165' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_parse_properties</a>(<a href='ofono/tools/stktest.c#line67' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>DBusMessage</a> *reply, const char *property, ...);
</div></div></div><div class="div_line"  data-info=({id:174201,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:174202,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/plugins/sap.c#line60' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_sap_client_register</a>(struct <a href='ofono/plugins/bluez4.h#line47' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>bluetooth_sap_driver</a> *<a href='ofono/plugins/sap.c#line320' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>sap</a>,
</div></div></div><div class="div_line"  data-info=({id:174203,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:174204,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/plugins/sap.c#line74' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>bluetooth_sap_client_unregister</a>(struct <a href='ofono/src/modem.c#line61' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem</a> *<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><script>var local_symbol_set='([{name:"BLUEZ_ADAPTER_INTERFACE",ln:27},{name:"BLUEZ_DEVICE_INTERFACE",ln:28},{name:"BLUEZ_MANAGER_INTERFACE",ln:26},{name:"BLUEZ_SERIAL_INTERFACE",ln:30},{name:"BLUEZ_SERVICE",ln:25},{name:"BLUEZ_SERVICE_INTERFACE",ln:29},{name:"ConnectFunc",ln:61},{name:"DBUS_TIMEOUT",ln:32},{name:"DUN_GW_UUID",ln:34},{name:"HFP_AG_UUID",ln:35},{name:"HFP_HS_UUID",ln:36},{name:"SAP_UUID",ln:37},{name:"bluetooth_profile",ln:39},{name:"bluetooth_sap_driver",ln:47},{name:"disable",ln:56},{name:"enable",ln:49},{name:"name",ln:40},{name:"name",ln:48},{name:"post_online",ln:55},{name:"post_sim",ln:52},{name:"pre_sim",ln:51},{name:"probe",ln:41},{name:"remove",ln:43},{name:"set_alias",ln:44},{name:"set_online",ln:53},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/plugins/bluez4.h"})';
</script>