<div class="div_line"  data-info=({id:185058,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:185059,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185060,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:185061,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185062,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:185063,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2010-2011  Nokia Corporation and/or its subsidiary(-ies).
</div></div></div><div class="div_line"  data-info=({id:185064,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185065,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:185066,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:185067,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:185068,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185069,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:185070,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:185071,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:185072,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:185073,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185074,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:185075,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:185076,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:185077,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:185078,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:185079,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185080,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef HAVE_CONFIG_H
</div></div></div><div class="div_line"  data-info=({id:185081,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>config.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185082,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:185083,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185084,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>stdlib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185085,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>errno.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185086,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>termios.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185087,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>string.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185088,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>unistd.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185089,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>sys/types.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185090,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>sys/stat.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185091,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>fcntl.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185092,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185093,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>glib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185094,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>gatchat.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185095,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>gattty.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185096,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185097,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>OFONO_API_SUBJECT_TO_CHANGE</span>
</div></div></div><div class="div_line"  data-info=({id:185098,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/plugin.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185099,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/log.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185100,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/modem.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185101,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185102,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>drivers/atmodem/atutil.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185103,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/cdma-voicecall.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185104,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/devinfo.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185105,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/cdma-connman.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:185106,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185107,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>common.h</span>"
</div></div></div><div class="div_line"  data-info=({id:185108,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185109,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>nokiacdma_data</span> {
</div></div></div><div class="div_line"  data-info=({id:185110,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *<span class='ctd member'>chat</span>;
</div></div></div><div class="div_line"  data-info=({id:185111,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:185112,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185113,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_debug</span>(const char *str, void *data)
</div></div></div><div class="div_line"  data-info=({id:185114,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185115,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *prefix = <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:185116,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185117,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_info</a>("%s%s", prefix, str);
</div></div></div><div class="div_line"  data-info=({id:185118,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185119,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185120,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>nokiacdma_probe</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185121,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185122,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:185123,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185124,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185125,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185126,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = g_try_new0(struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a>, 1);
</div></div></div><div class="div_line"  data-info=({id:185127,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> == NULL)
</div></div></div><div class="div_line"  data-info=({id:185128,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -ENOMEM;
</div></div></div><div class="div_line"  data-info=({id:185129,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185130,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line162' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_set_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:185131,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185132,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:185133,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185134,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185135,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_remove</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185136,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185137,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185138,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185139,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185140,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185141,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line162' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_set_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:185142,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185143,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1409' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_unref</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:185144,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185145,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:185146,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185147,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185148,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>nokiacdma_enable</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185149,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185150,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185151,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtSyntax *syntax;
</div></div></div><div class="div_line"  data-info=({id:185152,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GIOChannel *channel;
</div></div></div><div class="div_line"  data-info=({id:185153,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *device;
</div></div></div><div class="div_line"  data-info=({id:185154,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185155,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185156,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185157,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;device = <a href='ofono/src/modem.c#line1748' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_string</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, "Device");
</div></div></div><div class="div_line"  data-info=({id:185158,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (device == NULL)
</div></div></div><div class="div_line"  data-info=({id:185159,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -EINVAL;
</div></div></div><div class="div_line"  data-info=({id:185160,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185161,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;channel = <a href='ofono/gatchat/gattty.c#line243' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_tty_open</a>(device, NULL);
</div></div></div><div class="div_line"  data-info=({id:185162,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (channel == NULL)
</div></div></div><div class="div_line"  data-info=({id:185163,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -EIO;
</div></div></div><div class="div_line"  data-info=({id:185164,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185165,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:185166,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * TODO: Will need a CDMA AT syntax parser later.
</div></div></div><div class="div_line"  data-info=({id:185167,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Using GSM V1 for now.
</div></div></div><div class="div_line"  data-info=({id:185168,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:185169,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;syntax = <a href='ofono/gatchat/gatsyntax.c#line390' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_syntax_new_gsmv1</a>();
</div></div></div><div class="div_line"  data-info=({id:185170,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185171,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat = <a href='ofono/gatchat/gatchat.c#line1311' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_new</a>(channel, syntax);
</div></div></div><div class="div_line"  data-info=({id:185172,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatsyntax.c#line411' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_syntax_unref</a>(syntax);
</div></div></div><div class="div_line"  data-info=({id:185173,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_io_channel_unref(channel);
</div></div></div><div class="div_line"  data-info=({id:185174,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185175,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat == NULL)
</div></div></div><div class="div_line"  data-info=({id:185176,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -ENOMEM;
</div></div></div><div class="div_line"  data-info=({id:185177,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185178,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (getenv("OFONO_AT_DEBUG"))
</div></div></div><div class="div_line"  data-info=({id:185179,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1441' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_set_debug</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat, nokiacdma_debug,
</div></div></div><div class="div_line"  data-info=({id:185180,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;"CDMA Device: ");
</div></div></div><div class="div_line"  data-info=({id:185181,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185182,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:185183,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185184,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185185,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>nokiacdma_disable</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185186,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185187,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185188,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185189,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185190,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185191,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1409' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_unref</a>(<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:185192,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat = NULL;
</div></div></div><div class="div_line"  data-info=({id:185193,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185194,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:185195,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185196,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185197,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_pre_sim</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185198,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185199,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185200,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185201,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185202,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185203,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cdma-voicecall.c#line495' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cdma_voicecall_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "cdmamodem", <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:185204,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line1578' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_devinfo_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "cdmamodem", <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:185205,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185206,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185207,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_post_sim</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185208,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185209,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185210,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185211,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185212,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_post_online</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185213,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185214,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/plugins/nokiacdma.c#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a> = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185215,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185216,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185217,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185218,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/cdma-connman.c#line622' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_cdma_connman_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "cdmamodem", <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>-&gt;chat);
</div></div></div><div class="div_line"  data-info=({id:185219,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185220,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185221,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static struct <a href='ofono/include/modem.h#line46' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem_driver</a> <span class='ctd gvdef'>nokiacdma_driver</span> = {
</div></div></div><div class="div_line"  data-info=({id:185222,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= "nokiacdma",
</div></div></div><div class="div_line"  data-info=({id:185223,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>probe</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= nokiacdma_probe,
</div></div></div><div class="div_line"  data-info=({id:185224,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>remove</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= nokiacdma_remove,
</div></div></div><div class="div_line"  data-info=({id:185225,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>enable</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= nokiacdma_enable,
</div></div></div><div class="div_line"  data-info=({id:185226,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>disable</span>&#160;&#160;&#160;&#160;= nokiacdma_disable,
</div></div></div><div class="div_line"  data-info=({id:185227,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>pre_sim</span>&#160;&#160;&#160;&#160;= nokiacdma_pre_sim,
</div></div></div><div class="div_line"  data-info=({id:185228,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>post_sim</span>&#160;&#160;&#160;&#160;= nokiacdma_post_sim,
</div></div></div><div class="div_line"  data-info=({id:185229,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>post_online</span>&#160;&#160;&#160;&#160;= nokiacdma_post_online,
</div></div></div><div class="div_line"  data-info=({id:185230,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:185231,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185232,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>nokiacdma_init</span>(void)
</div></div></div><div class="div_line"  data-info=({id:185233,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185234,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return <a href='ofono/src/modem.c#line2145' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_driver_register</a>(&<a href='ofono/plugins/nokiacdma.c#line164' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_driver</a>);
</div></div></div><div class="div_line"  data-info=({id:185235,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185236,ln:179}) id=l179><div class="dl_wrapper"><a name=line179 onclick='overload_click(this)' class="a_ln">179<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185237,ln:180}) id=l180><div class="dl_wrapper"><a name=line180 onclick='overload_click(this)' class="a_ln">180<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>nokiacdma_exit</span>(void)
</div></div></div><div class="div_line"  data-info=({id:185238,ln:181}) id=l181><div class="dl_wrapper"><a name=line181 onclick='overload_click(this)' class="a_ln">181<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185239,ln:182}) id=l182><div class="dl_wrapper"><a name=line182 onclick='overload_click(this)' class="a_ln">182<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line2157' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_driver_unregister</a>(&<a href='ofono/plugins/nokiacdma.c#line164' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>nokiacdma_driver</a>);
</div></div></div><div class="div_line"  data-info=({id:185240,ln:183}) id=l183><div class="dl_wrapper"><a name=line183 onclick='overload_click(this)' class="a_ln">183<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185241,ln:184}) id=l184><div class="dl_wrapper"><a name=line184 onclick='overload_click(this)' class="a_ln">184<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185242,ln:185}) id=l185><div class="dl_wrapper"><a name=line185 onclick='overload_click(this)' class="a_ln">185<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"><a href='ofono/include/plugin.h#line69' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>OFONO_PLUGIN_DEFINE</a>(nokiacdma, "Nokia CDMA AT Modem", VERSION,
</div></div></div><div class="div_line"  data-info=({id:185243,ln:186}) id=l186><div class="dl_wrapper"><a name=line186 onclick='overload_click(this)' class="a_ln">186<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/include/plugin.h#line38' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>OFONO_PLUGIN_PRIORITY_DEFAULT</a>,
</div></div></div><div class="div_line"  data-info=({id:185244,ln:187}) id=l187><div class="dl_wrapper"><a name=line187 onclick='overload_click(this)' class="a_ln">187<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;nokiacdma_init, nokiacdma_exit)
</div></div></div><script>var local_symbol_set='([{name:"OFONO_API_SUBJECT_TO_CHANGE",ln:40},{name:"chat",ln:53},{name:"nokiacdma_data",ln:52},{name:"nokiacdma_debug",ln:56},{name:"nokiacdma_disable",ln:128},{name:"nokiacdma_driver",ln:164},{name:"nokiacdma_enable",ln:91},{name:"nokiacdma_exit",ln:180},{name:"nokiacdma_init",ln:175},{name:"nokiacdma_post_online",ln:155},{name:"nokiacdma_post_sim",ln:150},{name:"nokiacdma_pre_sim",ln:140},{name:"nokiacdma_probe",ln:63},{name:"nokiacdma_remove",ln:78},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/plugins/nokiacdma.c"})';
</script>