<div class="div_line"  data-info=({id:184813,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:184814,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184815,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:184816,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184817,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:184818,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184819,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:184820,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:184821,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:184822,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184823,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:184824,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:184825,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:184826,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:184827,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184828,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:184829,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:184830,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:184831,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:184832,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:184833,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184834,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef HAVE_CONFIG_H
</div></div></div><div class="div_line"  data-info=({id:184835,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>config.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184836,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:184837,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184838,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>errno.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184839,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>stdlib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184840,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184841,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>glib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184842,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>gatchat.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184843,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>gattty.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184844,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184845,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>OFONO_API_SUBJECT_TO_CHANGE</span>
</div></div></div><div class="div_line"  data-info=({id:184846,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/plugin.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184847,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/log.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184848,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/modem.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184849,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/call-barring.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184850,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/call-forwarding.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184851,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/call-meter.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184852,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/call-settings.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184853,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/devinfo.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184854,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/message-waiting.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184855,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/netreg.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184856,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/phonebook.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184857,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/sim.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184858,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/sms.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184859,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/ussd.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184860,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/voicecall.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184861,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184862,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>drivers/atmodem/atutil.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184863,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184864,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/gprs.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184865,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>ofono/gprs-context.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:184866,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184867,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>tc65_probe</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184868,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184869,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:184870,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184871,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184872,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_remove</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184873,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184874,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184875,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184876,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_debug</span>(const char *str, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:184877,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184878,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *prefix = user_data;
</div></div></div><div class="div_line"  data-info=({id:184879,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184880,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_info</a>("%s%s", prefix, str);
</div></div></div><div class="div_line"  data-info=({id:184881,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184882,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184883,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>tc65_enable</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184884,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184885,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat;
</div></div></div><div class="div_line"  data-info=({id:184886,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GIOChannel *channel;
</div></div></div><div class="div_line"  data-info=({id:184887,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtSyntax *syntax;
</div></div></div><div class="div_line"  data-info=({id:184888,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GHashTable *<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>;
</div></div></div><div class="div_line"  data-info=({id:184889,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *device;
</div></div></div><div class="div_line"  data-info=({id:184890,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184891,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184892,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184893,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a> = g_hash_table_new(g_str_hash, g_str_equal);
</div></div></div><div class="div_line"  data-info=({id:184894,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a> == NULL)
</div></div></div><div class="div_line"  data-info=({id:184895,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -ENOMEM;
</div></div></div><div class="div_line"  data-info=({id:184896,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184897,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;device = <a href='ofono/src/modem.c#line1748' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_string</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, "Device");
</div></div></div><div class="div_line"  data-info=({id:184898,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (device == NULL)
</div></div></div><div class="div_line"  data-info=({id:184899,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -EINVAL;
</div></div></div><div class="div_line"  data-info=({id:184900,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184901,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "Baud", "115200");
</div></div></div><div class="div_line"  data-info=({id:184902,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "StopBits", "1");
</div></div></div><div class="div_line"  data-info=({id:184903,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "DataBits", "8");
</div></div></div><div class="div_line"  data-info=({id:184904,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "Parity", "none");
</div></div></div><div class="div_line"  data-info=({id:184905,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "XonXoff", "off");
</div></div></div><div class="div_line"  data-info=({id:184906,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "RtsCts", "on");
</div></div></div><div class="div_line"  data-info=({id:184907,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "Local", "on");
</div></div></div><div class="div_line"  data-info=({id:184908,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_insert(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>, "Read", "on");
</div></div></div><div class="div_line"  data-info=({id:184909,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184910,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;channel = <a href='ofono/gatchat/gattty.c#line243' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_tty_open</a>(device, <a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>);
</div></div></div><div class="div_line"  data-info=({id:184911,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_hash_table_destroy(<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>);
</div></div></div><div class="div_line"  data-info=({id:184912,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184913,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (channel == NULL)
</div></div></div><div class="div_line"  data-info=({id:184914,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -EIO;
</div></div></div><div class="div_line"  data-info=({id:184915,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184916,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:184917,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * TC65 works almost as the 27.007 says. But for example after
</div></div></div><div class="div_line"  data-info=({id:184918,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * AT+CRSM the modem replies with the data in the queried EF and
</div></div></div><div class="div_line"  data-info=({id:184919,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * writes three pairs of &lt;CR&gt;&lt;LF&gt; after the data and before OK.
</div></div></div><div class="div_line"  data-info=({id:184920,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:184921,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;syntax = <a href='ofono/gatchat/gatsyntax.c#line395' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_syntax_new_gsm_permissive</a>();
</div></div></div><div class="div_line"  data-info=({id:184922,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184923,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;chat = <a href='ofono/gatchat/gatchat.c#line1311' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_new</a>(channel, syntax);
</div></div></div><div class="div_line"  data-info=({id:184924,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatsyntax.c#line411' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_syntax_unref</a>(syntax);
</div></div></div><div class="div_line"  data-info=({id:184925,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_io_channel_unref(channel);
</div></div></div><div class="div_line"  data-info=({id:184926,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184927,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (chat == NULL)
</div></div></div><div class="div_line"  data-info=({id:184928,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return -ENOMEM;
</div></div></div><div class="div_line"  data-info=({id:184929,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184930,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (getenv("OFONO_AT_DEBUG"))
</div></div></div><div class="div_line"  data-info=({id:184931,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1441' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_set_debug</a>(chat, tc65_debug, "");
</div></div></div><div class="div_line"  data-info=({id:184932,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184933,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line162' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_set_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, chat);
</div></div></div><div class="div_line"  data-info=({id:184934,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184935,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:184936,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184937,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184938,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>tc65_disable</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184939,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184940,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184941,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184942,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184943,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184944,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line162' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_set_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:184945,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184946,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(chat, "AT+CFUN=7", NULL, NULL, NULL, NULL);
</div></div></div><div class="div_line"  data-info=({id:184947,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184948,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/gatchat/gatchat.c#line1409' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_unref</a>(chat);
</div></div></div><div class="div_line"  data-info=({id:184949,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184950,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:184951,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184952,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184953,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>set_online_cb</span>(gboolean ok, GAtResult *result, gpointer user_data)
</div></div></div><div class="div_line"  data-info=({id:184954,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184955,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/atutil.h#line86' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>cb_data</a> *cbd = user_data;
</div></div></div><div class="div_line"  data-info=({id:184956,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;ofono_modem_online_cb_t cb = cbd-&gt;cb;
</div></div></div><div class="div_line"  data-info=({id:184957,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/include/types.h#line68' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_error</a> <a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>;
</div></div></div><div class="div_line"  data-info=({id:184958,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184959,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/drivers/atmodem/atutil.c#line53' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>decode_at_error</a>(&<a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>, <a href='ofono/gatchat/gatresult.c#line498' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_result_final_response</a>(<a href='ofono/unit/test-stkutil.c#line16244' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:176})'>result</a>));
</div></div></div><div class="div_line"  data-info=({id:184960,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184961,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;cb(&<a href='ofono/gdbus/mainloop.c#line34' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>error</a>, cbd-&gt;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:184962,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184963,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184964,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_set_online</span>(struct ofono_modem *modem, ofono_bool_t online,
</div></div></div><div class="div_line"  data-info=({id:184965,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_modem_online_cb_t cb, void *user_data)
</div></div></div><div class="div_line"  data-info=({id:184966,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184967,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184968,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/drivers/atmodem/atutil.h#line86' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:4})'>cb_data</a> *cbd = <a href='ofono/drivers/atmodem/atutil.h#line92' class='a_code_tag multi_def' data-info='({type:"fncall",tagreg:3})'>cb_data_new</a>(cb, user_data);
</div></div></div><div class="div_line"  data-info=({id:184969,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;char const *command = online ? "AT+CFUN=1" : "AT+CFUN=7";
</div></div></div><div class="div_line"  data-info=({id:184970,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184971,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a> %p %s", modem, online ? "online" : "offline");
</div></div></div><div class="div_line"  data-info=({id:184972,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184973,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/gatchat/gatchat.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>g_at_chat_send</a>(chat, command, NULL, set_online_cb, cbd, g_free))
</div></div></div><div class="div_line"  data-info=({id:184974,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return;
</div></div></div><div class="div_line"  data-info=({id:184975,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184976,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_free(cbd);
</div></div></div><div class="div_line"  data-info=({id:184977,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184978,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;CALLBACK_WITH_FAILURE(cb, cbd-&gt;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:184979,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184980,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184981,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_pre_sim</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184982,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184983,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184984,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/sim.c#line51' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim</a> *sim;
</div></div></div><div class="div_line"  data-info=({id:184985,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184986,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184987,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184988,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line1578' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_devinfo_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:184989,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;sim = <a href='ofono/src/sim.c#line2862' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_sim_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:184990,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/voicecall.c#line2812' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_voicecall_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:184991,ln:179}) id=l179><div class="dl_wrapper"><a name=line179 onclick='overload_click(this)' class="a_ln">179<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184992,ln:180}) id=l180><div class="dl_wrapper"><a name=line180 onclick='overload_click(this)' class="a_ln">180<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (sim)
</div></div></div><div class="div_line"  data-info=({id:184993,ln:181}) id=l181><div class="dl_wrapper"><a name=line181 onclick='overload_click(this)' class="a_ln">181<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/sim.c#line2452' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_sim_inserted_notify</a>(sim, <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>);
</div></div></div><div class="div_line"  data-info=({id:184994,ln:182}) id=l182><div class="dl_wrapper"><a name=line182 onclick='overload_click(this)' class="a_ln">182<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:184995,ln:183}) id=l183><div class="dl_wrapper"><a name=line183 onclick='overload_click(this)' class="a_ln">183<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:184996,ln:184}) id=l184><div class="dl_wrapper"><a name=line184 onclick='overload_click(this)' class="a_ln">184<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_post_sim</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:184997,ln:185}) id=l185><div class="dl_wrapper"><a name=line185 onclick='overload_click(this)' class="a_ln">185<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:184998,ln:186}) id=l186><div class="dl_wrapper"><a name=line186 onclick='overload_click(this)' class="a_ln">186<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:184999,ln:187}) id=l187><div class="dl_wrapper"><a name=line187 onclick='overload_click(this)' class="a_ln">187<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185000,ln:188}) id=l188><div class="dl_wrapper"><a name=line188 onclick='overload_click(this)' class="a_ln">188<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185001,ln:189}) id=l189><div class="dl_wrapper"><a name=line189 onclick='overload_click(this)' class="a_ln">189<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185002,ln:190}) id=l190><div class="dl_wrapper"><a name=line190 onclick='overload_click(this)' class="a_ln">190<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/phonebook.c#line539' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_phonebook_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185003,ln:191}) id=l191><div class="dl_wrapper"><a name=line191 onclick='overload_click(this)' class="a_ln">191<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185004,ln:192}) id=l192><div class="dl_wrapper"><a name=line192 onclick='overload_click(this)' class="a_ln">192<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/sms.c#line1780' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_sms_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185005,ln:193}) id=l193><div class="dl_wrapper"><a name=line193 onclick='overload_click(this)' class="a_ln">193<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185006,ln:194}) id=l194><div class="dl_wrapper"><a name=line194 onclick='overload_click(this)' class="a_ln">194<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185007,ln:195}) id=l195><div class="dl_wrapper"><a name=line195 onclick='overload_click(this)' class="a_ln">195<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_post_online</span>(struct ofono_modem *modem)
</div></div></div><div class="div_line"  data-info=({id:185008,ln:196}) id=l196><div class="dl_wrapper"><a name=line196 onclick='overload_click(this)' class="a_ln">196<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185009,ln:197}) id=l197><div class="dl_wrapper"><a name=line197 onclick='overload_click(this)' class="a_ln">197<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GAtChat *chat = <a href='ofono/src/modem.c#line170' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_get_data</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185010,ln:198}) id=l198><div class="dl_wrapper"><a name=line198 onclick='overload_click(this)' class="a_ln">198<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/message-waiting.c#line47' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_message_waiting</a> *mw;
</div></div></div><div class="div_line"  data-info=({id:185011,ln:199}) id=l199><div class="dl_wrapper"><a name=line199 onclick='overload_click(this)' class="a_ln">199<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/gprs.c#line73' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_gprs</a> *<a href='ofono/unit/test-stkutil.c#line15684' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>gprs</a>;
</div></div></div><div class="div_line"  data-info=({id:185012,ln:200}) id=l200><div class="dl_wrapper"><a name=line200 onclick='overload_click(this)' class="a_ln">200<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/gprs.c#line123' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_gprs_context</a> *gc;
</div></div></div><div class="div_line"  data-info=({id:185013,ln:201}) id=l201><div class="dl_wrapper"><a name=line201 onclick='overload_click(this)' class="a_ln">201<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185014,ln:202}) id=l202><div class="dl_wrapper"><a name=line202 onclick='overload_click(this)' class="a_ln">202<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("%p", <a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185015,ln:203}) id=l203><div class="dl_wrapper"><a name=line203 onclick='overload_click(this)' class="a_ln">203<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185016,ln:204}) id=l204><div class="dl_wrapper"><a name=line204 onclick='overload_click(this)' class="a_ln">204<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/ussd.c#line822' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_ussd_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185017,ln:205}) id=l205><div class="dl_wrapper"><a name=line205 onclick='overload_click(this)' class="a_ln">205<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/call-forwarding.c#line1478' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_call_forwarding_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185018,ln:206}) id=l206><div class="dl_wrapper"><a name=line206 onclick='overload_click(this)' class="a_ln">206<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/call-settings.c#line1404' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_call_settings_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185019,ln:207}) id=l207><div class="dl_wrapper"><a name=line207 onclick='overload_click(this)' class="a_ln">207<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/network.c#line1850' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_netreg_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185020,ln:208}) id=l208><div class="dl_wrapper"><a name=line208 onclick='overload_click(this)' class="a_ln">208<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/call-meter.c#line729' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_call_meter_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185021,ln:209}) id=l209><div class="dl_wrapper"><a name=line209 onclick='overload_click(this)' class="a_ln">209<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/call-barring.c#line1050' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_call_barring_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185022,ln:210}) id=l210><div class="dl_wrapper"><a name=line210 onclick='overload_click(this)' class="a_ln">210<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185023,ln:211}) id=l211><div class="dl_wrapper"><a name=line211 onclick='overload_click(this)' class="a_ln">211<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/unit/test-stkutil.c#line15684' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>gprs</a> = <a href='ofono/src/gprs.c#line2710' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_gprs_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185024,ln:212}) id=l212><div class="dl_wrapper"><a name=line212 onclick='overload_click(this)' class="a_ln">212<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gc = <a href='ofono/src/gprs.c#line2424' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_gprs_context_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>, 0, "atmodem", chat);
</div></div></div><div class="div_line"  data-info=({id:185025,ln:213}) id=l213><div class="dl_wrapper"><a name=line213 onclick='overload_click(this)' class="a_ln">213<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185026,ln:214}) id=l214><div class="dl_wrapper"><a name=line214 onclick='overload_click(this)' class="a_ln">214<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (<a href='ofono/unit/test-stkutil.c#line15684' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>gprs</a> && gc)
</div></div></div><div class="div_line"  data-info=({id:185027,ln:215}) id=l215><div class="dl_wrapper"><a name=line215 onclick='overload_click(this)' class="a_ln">215<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/gprs.c#line2318' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_gprs_add_context</a>(<a href='ofono/unit/test-stkutil.c#line15684' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:7})'>gprs</a>, gc);
</div></div></div><div class="div_line"  data-info=({id:185028,ln:216}) id=l216><div class="dl_wrapper"><a name=line216 onclick='overload_click(this)' class="a_ln">216<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185029,ln:217}) id=l217><div class="dl_wrapper"><a name=line217 onclick='overload_click(this)' class="a_ln">217<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;mw = <a href='ofono/src/message-waiting.c#line1096' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_message_waiting_create</a>(<a href='ofono/gatchat/gsmdial.c#line65' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>modem</a>);
</div></div></div><div class="div_line"  data-info=({id:185030,ln:218}) id=l218><div class="dl_wrapper"><a name=line218 onclick='overload_click(this)' class="a_ln">218<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (mw)
</div></div></div><div class="div_line"  data-info=({id:185031,ln:219}) id=l219><div class="dl_wrapper"><a name=line219 onclick='overload_click(this)' class="a_ln">219<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/message-waiting.c#line1024' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_message_waiting_register</a>(mw);
</div></div></div><div class="div_line"  data-info=({id:185032,ln:220}) id=l220><div class="dl_wrapper"><a name=line220 onclick='overload_click(this)' class="a_ln">220<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185033,ln:221}) id=l221><div class="dl_wrapper"><a name=line221 onclick='overload_click(this)' class="a_ln">221<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185034,ln:222}) id=l222><div class="dl_wrapper"><a name=line222 onclick='overload_click(this)' class="a_ln">222<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static struct <a href='ofono/include/modem.h#line46' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_modem_driver</a> <span class='ctd gvdef'>tc65_driver</span> = {
</div></div></div><div class="div_line"  data-info=({id:185035,ln:223}) id=l223><div class="dl_wrapper"><a name=line223 onclick='overload_click(this)' class="a_ln">223<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= "tc65",
</div></div></div><div class="div_line"  data-info=({id:185036,ln:224}) id=l224><div class="dl_wrapper"><a name=line224 onclick='overload_click(this)' class="a_ln">224<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>probe</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= tc65_probe,
</div></div></div><div class="div_line"  data-info=({id:185037,ln:225}) id=l225><div class="dl_wrapper"><a name=line225 onclick='overload_click(this)' class="a_ln">225<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>remove</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= tc65_remove,
</div></div></div><div class="div_line"  data-info=({id:185038,ln:226}) id=l226><div class="dl_wrapper"><a name=line226 onclick='overload_click(this)' class="a_ln">226<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>enable</span>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;= tc65_enable,
</div></div></div><div class="div_line"  data-info=({id:185039,ln:227}) id=l227><div class="dl_wrapper"><a name=line227 onclick='overload_click(this)' class="a_ln">227<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>disable</span>&#160;&#160;&#160;&#160;= tc65_disable,
</div></div></div><div class="div_line"  data-info=({id:185040,ln:228}) id=l228><div class="dl_wrapper"><a name=line228 onclick='overload_click(this)' class="a_ln">228<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>set_online</span>&#160;&#160;&#160;&#160;= tc65_set_online,
</div></div></div><div class="div_line"  data-info=({id:185041,ln:229}) id=l229><div class="dl_wrapper"><a name=line229 onclick='overload_click(this)' class="a_ln">229<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>pre_sim</span>&#160;&#160;&#160;&#160;= tc65_pre_sim,
</div></div></div><div class="div_line"  data-info=({id:185042,ln:230}) id=l230><div class="dl_wrapper"><a name=line230 onclick='overload_click(this)' class="a_ln">230<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>post_sim</span>&#160;&#160;&#160;&#160;= tc65_post_sim,
</div></div></div><div class="div_line"  data-info=({id:185043,ln:231}) id=l231><div class="dl_wrapper"><a name=line231 onclick='overload_click(this)' class="a_ln">231<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;.<span class='ctd gvdef'>post_online</span>&#160;&#160;&#160;&#160;= tc65_post_online,
</div></div></div><div class="div_line"  data-info=({id:185044,ln:232}) id=l232><div class="dl_wrapper"><a name=line232 onclick='overload_click(this)' class="a_ln">232<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:185045,ln:233}) id=l233><div class="dl_wrapper"><a name=line233 onclick='overload_click(this)' class="a_ln">233<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185046,ln:234}) id=l234><div class="dl_wrapper"><a name=line234 onclick='overload_click(this)' class="a_ln">234<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static int <span class='ctd fndef'>tc65_init</span>(void)
</div></div></div><div class="div_line"  data-info=({id:185047,ln:235}) id=l235><div class="dl_wrapper"><a name=line235 onclick='overload_click(this)' class="a_ln">235<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185048,ln:236}) id=l236><div class="dl_wrapper"><a name=line236 onclick='overload_click(this)' class="a_ln">236<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return <a href='ofono/src/modem.c#line2145' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_driver_register</a>(&<a href='ofono/plugins/tc65.c#line222' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>tc65_driver</a>);
</div></div></div><div class="div_line"  data-info=({id:185049,ln:237}) id=l237><div class="dl_wrapper"><a name=line237 onclick='overload_click(this)' class="a_ln">237<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185050,ln:238}) id=l238><div class="dl_wrapper"><a name=line238 onclick='overload_click(this)' class="a_ln">238<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185051,ln:239}) id=l239><div class="dl_wrapper"><a name=line239 onclick='overload_click(this)' class="a_ln">239<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static void <span class='ctd fndef'>tc65_exit</span>(void)
</div></div></div><div class="div_line"  data-info=({id:185052,ln:240}) id=l240><div class="dl_wrapper"><a name=line240 onclick='overload_click(this)' class="a_ln">240<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:185053,ln:241}) id=l241><div class="dl_wrapper"><a name=line241 onclick='overload_click(this)' class="a_ln">241<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/modem.c#line2157' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_modem_driver_unregister</a>(&<a href='ofono/plugins/tc65.c#line222' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>tc65_driver</a>);
</div></div></div><div class="div_line"  data-info=({id:185054,ln:242}) id=l242><div class="dl_wrapper"><a name=line242 onclick='overload_click(this)' class="a_ln">242<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:185055,ln:243}) id=l243><div class="dl_wrapper"><a name=line243 onclick='overload_click(this)' class="a_ln">243<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:185056,ln:244}) id=l244><div class="dl_wrapper"><a name=line244 onclick='overload_click(this)' class="a_ln">244<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"><a href='ofono/include/plugin.h#line69' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>OFONO_PLUGIN_DEFINE</a>(tc65, "Cinterion TC65 <a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a> plugin", VERSION,
</div></div></div><div class="div_line"  data-info=({id:185057,ln:245}) id=l245><div class="dl_wrapper"><a name=line245 onclick='overload_click(this)' class="a_ln">245<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/include/plugin.h#line38' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>OFONO_PLUGIN_PRIORITY_DEFAULT</a>, tc65_init, tc65_exit)
</div></div></div><script>var local_symbol_set='([{name:"OFONO_API_SUBJECT_TO_CHANGE",ln:33},{name:"set_online_cb",ln:141},{name:"tc65_debug",ln:64},{name:"tc65_disable",ln:126},{name:"tc65_driver",ln:222},{name:"tc65_enable",ln:71},{name:"tc65_exit",ln:239},{name:"tc65_init",ln:234},{name:"tc65_post_online",ln:195},{name:"tc65_post_sim",ln:184},{name:"tc65_pre_sim",ln:169},{name:"tc65_probe",ln:55},{name:"tc65_remove",ln:60},{name:"tc65_set_online",ln:152},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/plugins/tc65.c"})';
</script>