<div class="div_line"  data-info=({id:240056,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:240057,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240058,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:240059,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240060,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:240061,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240062,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:240063,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:240064,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:240065,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240066,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:240067,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:240068,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:240069,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:240070,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240071,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:240072,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:240073,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:240074,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:240075,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:240076,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240077,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef HAVE_CONFIG_H
</div></div></div><div class="div_line"  data-info=({id:240078,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>config.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:240079,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:240080,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240081,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>dlfcn.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:240082,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240083,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include &lt;<span class='ctd include'>glib.h</span>&gt;
</div></div></div><div class="div_line"  data-info=({id:240084,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240085,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>ofono.h</span>"
</div></div></div><div class="div_line"  data-info=({id:240086,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240087,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static GSList *<span class='ctd gvdef'>plugins</span> = NULL;
</div></div></div><div class="div_line"  data-info=({id:240088,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240089,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ofono_plugin</span> {
</div></div></div><div class="div_line"  data-info=({id:240090,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void *<span class='ctd member'>handle</span>;
</div></div></div><div class="div_line"  data-info=({id:240091,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gboolean <span class='ctd member'>active</span>;
</div></div></div><div class="div_line"  data-info=({id:240092,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/include/plugin.h#line47' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin_desc</a> *<span class='ctd member'>desc</span>;
</div></div></div><div class="div_line"  data-info=({id:240093,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:240094,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240095,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static gint <span class='ctd fndef'>compare_priority</span>(gconstpointer a, gconstpointer b)
</div></div></div><div class="div_line"  data-info=({id:240096,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:240097,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a> *plugin1 = a;
</div></div></div><div class="div_line"  data-info=({id:240098,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a> *plugin2 = b;
</div></div></div><div class="div_line"  data-info=({id:240099,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240100,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return plugin2-&gt;desc-&gt;<a href='ofono/examples/provision.c#line84' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>priority</a> - plugin1-&gt;desc-&gt;priority;
</div></div></div><div class="div_line"  data-info=({id:240101,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:240102,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240103,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static gboolean <span class='ctd fndef'>add_plugin</span>(void *handle, struct ofono_plugin_desc *desc)
</div></div></div><div class="div_line"  data-info=({id:240104,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:240105,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a> *plugin;
</div></div></div><div class="div_line"  data-info=({id:240106,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240107,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (desc-&gt;init == NULL)
</div></div></div><div class="div_line"  data-info=({id:240108,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240109,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240110,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (g_str_equal(desc-&gt;version, OFONO_VERSION) == <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>) {
</div></div></div><div class="div_line"  data-info=({id:240111,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Invalid version %s for %s", desc-&gt;version,
</div></div></div><div class="div_line"  data-info=({id:240112,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;desc-&gt;description);
</div></div></div><div class="div_line"  data-info=({id:240113,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240114,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240115,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240116,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;plugin = g_try_new0(struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a>, 1);
</div></div></div><div class="div_line"  data-info=({id:240117,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (plugin == NULL)
</div></div></div><div class="div_line"  data-info=({id:240118,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240119,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240120,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;plugin-&gt;handle = handle;
</div></div></div><div class="div_line"  data-info=({id:240121,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;plugin-&gt;active = <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240122,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;plugin-&gt;desc = desc;
</div></div></div><div class="div_line"  data-info=({id:240123,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240124,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line268' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>__ofono_log_enable</a>(desc-&gt;debug_start, desc-&gt;debug_stop);
</div></div></div><div class="div_line"  data-info=({id:240125,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240126,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<a href='ofono/src/plugin.c#line32' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>plugins</a> = g_slist_insert_sorted(plugins, plugin, compare_priority);
</div></div></div><div class="div_line"  data-info=({id:240127,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240128,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>;
</div></div></div><div class="div_line"  data-info=({id:240129,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:240130,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240131,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">static gboolean <span class='ctd fndef'>check_plugin</span>(struct ofono_plugin_desc *desc,
</div></div></div><div class="div_line"  data-info=({id:240132,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;char **patterns, char **excludes)
</div></div></div><div class="div_line"  data-info=({id:240133,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:240134,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (excludes) {
</div></div></div><div class="div_line"  data-info=({id:240135,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;for (; *excludes; excludes++)
</div></div></div><div class="div_line"  data-info=({id:240136,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (g_pattern_match_simple(*excludes, desc-&gt;<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>))
</div></div></div><div class="div_line"  data-info=({id:240137,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;break;
</div></div></div><div class="div_line"  data-info=({id:240138,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (*excludes) {
</div></div></div><div class="div_line"  data-info=({id:240139,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_info</a>("Excluding %s", desc-&gt;description);
</div></div></div><div class="div_line"  data-info=({id:240140,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240141,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240142,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240143,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240144,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (patterns) {
</div></div></div><div class="div_line"  data-info=({id:240145,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;for (; *patterns; patterns++)
</div></div></div><div class="div_line"  data-info=({id:240146,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (g_pattern_match_simple(*patterns, desc-&gt;<a href='ofono/gatchat/ppp_ipcp.c#line451' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:5})'>name</a>))
</div></div></div><div class="div_line"  data-info=({id:240147,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;break;
</div></div></div><div class="div_line"  data-info=({id:240148,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (*patterns == NULL) {
</div></div></div><div class="div_line"  data-info=({id:240149,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_info</a>("Ignoring %s", desc-&gt;description);
</div></div></div><div class="div_line"  data-info=({id:240150,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>;
</div></div></div><div class="div_line"  data-info=({id:240151,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240152,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240153,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240154,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>;
</div></div></div><div class="div_line"  data-info=({id:240155,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:240156,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240157,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>builtin.h</span>"
</div></div></div><div class="div_line"  data-info=({id:240158,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240159,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <span class='ctd fndef'>__ofono_plugin_init</span>(const char *pattern, const char *exclude)
</div></div></div><div class="div_line"  data-info=({id:240160,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:240161,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gchar **patterns = NULL;
</div></div></div><div class="div_line"  data-info=({id:240162,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gchar **excludes = NULL;
</div></div></div><div class="div_line"  data-info=({id:240163,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GSList *<a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>;
</div></div></div><div class="div_line"  data-info=({id:240164,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GDir *dir;
</div></div></div><div class="div_line"  data-info=({id:240165,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const gchar *<a href='ofono/include/log.h#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>file</a>;
</div></div></div><div class="div_line"  data-info=({id:240166,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;gchar *filename;
</div></div></div><div class="div_line"  data-info=({id:240167,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;unsigned int i;
</div></div></div><div class="div_line"  data-info=({id:240168,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240169,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:240170,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240171,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (pattern)
</div></div></div><div class="div_line"  data-info=({id:240172,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;patterns = g_strsplit_set(pattern, ":, ", -1);
</div></div></div><div class="div_line"  data-info=({id:240173,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240174,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (exclude)
</div></div></div><div class="div_line"  data-info=({id:240175,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;excludes = g_strsplit_set(exclude, ":, ", -1);
</div></div></div><div class="div_line"  data-info=({id:240176,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240177,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;for (i = 0; __ofono_builtin[i]; i++) {
</div></div></div><div class="div_line"  data-info=({id:240178,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (<a href='ofono/src/plugin.c#line76' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>check_plugin</a>(__ofono_builtin[i],
</div></div></div><div class="div_line"  data-info=({id:240179,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;patterns, excludes) == <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>)
</div></div></div><div class="div_line"  data-info=({id:240180,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240181,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240182,ln:127}) id=l127><div class="dl_wrapper"><a name=line127 onclick='overload_click(this)' class="a_ln">127<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/plugin.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>add_plugin</a>(NULL, __ofono_builtin[i]);
</div></div></div><div class="div_line"  data-info=({id:240183,ln:128}) id=l128><div class="dl_wrapper"><a name=line128 onclick='overload_click(this)' class="a_ln">128<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240184,ln:129}) id=l129><div class="dl_wrapper"><a name=line129 onclick='overload_click(this)' class="a_ln">129<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240185,ln:130}) id=l130><div class="dl_wrapper"><a name=line130 onclick='overload_click(this)' class="a_ln">130<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;dir = g_dir_open(PLUGINDIR, 0, NULL);
</div></div></div><div class="div_line"  data-info=({id:240186,ln:131}) id=l131><div class="dl_wrapper"><a name=line131 onclick='overload_click(this)' class="a_ln">131<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;if (dir != NULL) {
</div></div></div><div class="div_line"  data-info=({id:240187,ln:132}) id=l132><div class="dl_wrapper"><a name=line132 onclick='overload_click(this)' class="a_ln">132<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;while ((<a href='ofono/include/log.h#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>file</a> = g_dir_read_name(dir)) != NULL) {
</div></div></div><div class="div_line"  data-info=({id:240188,ln:133}) id=l133><div class="dl_wrapper"><a name=line133 onclick='overload_click(this)' class="a_ln">133<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *handle;
</div></div></div><div class="div_line"  data-info=({id:240189,ln:134}) id=l134><div class="dl_wrapper"><a name=line134 onclick='overload_click(this)' class="a_ln">134<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/include/plugin.h#line47' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin_desc</a> *desc;
</div></div></div><div class="div_line"  data-info=({id:240190,ln:135}) id=l135><div class="dl_wrapper"><a name=line135 onclick='overload_click(this)' class="a_ln">135<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240191,ln:136}) id=l136><div class="dl_wrapper"><a name=line136 onclick='overload_click(this)' class="a_ln">136<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (g_str_has_prefix(<a href='ofono/include/log.h#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>file</a>, "lib") == <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a> ||
</div></div></div><div class="div_line"  data-info=({id:240192,ln:137}) id=l137><div class="dl_wrapper"><a name=line137 onclick='overload_click(this)' class="a_ln">137<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;g_str_has_suffix(<a href='ofono/include/log.h#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>file</a>, ".so") == <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>)
</div></div></div><div class="div_line"  data-info=({id:240193,ln:138}) id=l138><div class="dl_wrapper"><a name=line138 onclick='overload_click(this)' class="a_ln">138<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240194,ln:139}) id=l139><div class="dl_wrapper"><a name=line139 onclick='overload_click(this)' class="a_ln">139<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240195,ln:140}) id=l140><div class="dl_wrapper"><a name=line140 onclick='overload_click(this)' class="a_ln">140<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;filename = g_build_filename(PLUGINDIR, <a href='ofono/include/log.h#line46' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>file</a>, NULL);
</div></div></div><div class="div_line"  data-info=({id:240196,ln:141}) id=l141><div class="dl_wrapper"><a name=line141 onclick='overload_click(this)' class="a_ln">141<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240197,ln:142}) id=l142><div class="dl_wrapper"><a name=line142 onclick='overload_click(this)' class="a_ln">142<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;handle = dlopen(filename, RTLD_NOW);
</div></div></div><div class="div_line"  data-info=({id:240198,ln:143}) id=l143><div class="dl_wrapper"><a name=line143 onclick='overload_click(this)' class="a_ln">143<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (handle == NULL) {
</div></div></div><div class="div_line"  data-info=({id:240199,ln:144}) id=l144><div class="dl_wrapper"><a name=line144 onclick='overload_click(this)' class="a_ln">144<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Can't load %s: %s",
</div></div></div><div class="div_line"  data-info=({id:240200,ln:145}) id=l145><div class="dl_wrapper"><a name=line145 onclick='overload_click(this)' class="a_ln">145<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;filename, dlerror());
</div></div></div><div class="div_line"  data-info=({id:240201,ln:146}) id=l146><div class="dl_wrapper"><a name=line146 onclick='overload_click(this)' class="a_ln">146<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;g_free(filename);
</div></div></div><div class="div_line"  data-info=({id:240202,ln:147}) id=l147><div class="dl_wrapper"><a name=line147 onclick='overload_click(this)' class="a_ln">147<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240203,ln:148}) id=l148><div class="dl_wrapper"><a name=line148 onclick='overload_click(this)' class="a_ln">148<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240204,ln:149}) id=l149><div class="dl_wrapper"><a name=line149 onclick='overload_click(this)' class="a_ln">149<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240205,ln:150}) id=l150><div class="dl_wrapper"><a name=line150 onclick='overload_click(this)' class="a_ln">150<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;g_free(filename);
</div></div></div><div class="div_line"  data-info=({id:240206,ln:151}) id=l151><div class="dl_wrapper"><a name=line151 onclick='overload_click(this)' class="a_ln">151<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240207,ln:152}) id=l152><div class="dl_wrapper"><a name=line152 onclick='overload_click(this)' class="a_ln">152<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;desc = dlsym(handle, "ofono_plugin_desc");
</div></div></div><div class="div_line"  data-info=({id:240208,ln:153}) id=l153><div class="dl_wrapper"><a name=line153 onclick='overload_click(this)' class="a_ln">153<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (desc == NULL) {
</div></div></div><div class="div_line"  data-info=({id:240209,ln:154}) id=l154><div class="dl_wrapper"><a name=line154 onclick='overload_click(this)' class="a_ln">154<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<a href='ofono/src/log.c#line84' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>ofono_error</a>("Can't load symbol: %s",
</div></div></div><div class="div_line"  data-info=({id:240210,ln:155}) id=l155><div class="dl_wrapper"><a name=line155 onclick='overload_click(this)' class="a_ln">155<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;dlerror());
</div></div></div><div class="div_line"  data-info=({id:240211,ln:156}) id=l156><div class="dl_wrapper"><a name=line156 onclick='overload_click(this)' class="a_ln">156<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;dlclose(handle);
</div></div></div><div class="div_line"  data-info=({id:240212,ln:157}) id=l157><div class="dl_wrapper"><a name=line157 onclick='overload_click(this)' class="a_ln">157<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240213,ln:158}) id=l158><div class="dl_wrapper"><a name=line158 onclick='overload_click(this)' class="a_ln">158<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240214,ln:159}) id=l159><div class="dl_wrapper"><a name=line159 onclick='overload_click(this)' class="a_ln">159<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240215,ln:160}) id=l160><div class="dl_wrapper"><a name=line160 onclick='overload_click(this)' class="a_ln">160<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (<a href='ofono/src/plugin.c#line76' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>check_plugin</a>(desc, patterns, excludes) == <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>) {
</div></div></div><div class="div_line"  data-info=({id:240216,ln:161}) id=l161><div class="dl_wrapper"><a name=line161 onclick='overload_click(this)' class="a_ln">161<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;dlclose(handle);
</div></div></div><div class="div_line"  data-info=({id:240217,ln:162}) id=l162><div class="dl_wrapper"><a name=line162 onclick='overload_click(this)' class="a_ln">162<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240218,ln:163}) id=l163><div class="dl_wrapper"><a name=line163 onclick='overload_click(this)' class="a_ln">163<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240219,ln:164}) id=l164><div class="dl_wrapper"><a name=line164 onclick='overload_click(this)' class="a_ln">164<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240220,ln:165}) id=l165><div class="dl_wrapper"><a name=line165 onclick='overload_click(this)' class="a_ln">165<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (<a href='ofono/src/plugin.c#line48' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>add_plugin</a>(handle, desc) == <a href='ofono/include/types.h#line30' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>FALSE</a>)
</div></div></div><div class="div_line"  data-info=({id:240221,ln:166}) id=l166><div class="dl_wrapper"><a name=line166 onclick='overload_click(this)' class="a_ln">166<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;dlclose(handle);
</div></div></div><div class="div_line"  data-info=({id:240222,ln:167}) id=l167><div class="dl_wrapper"><a name=line167 onclick='overload_click(this)' class="a_ln">167<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240223,ln:168}) id=l168><div class="dl_wrapper"><a name=line168 onclick='overload_click(this)' class="a_ln">168<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240224,ln:169}) id=l169><div class="dl_wrapper"><a name=line169 onclick='overload_click(this)' class="a_ln">169<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;g_dir_close(dir);
</div></div></div><div class="div_line"  data-info=({id:240225,ln:170}) id=l170><div class="dl_wrapper"><a name=line170 onclick='overload_click(this)' class="a_ln">170<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240226,ln:171}) id=l171><div class="dl_wrapper"><a name=line171 onclick='overload_click(this)' class="a_ln">171<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240227,ln:172}) id=l172><div class="dl_wrapper"><a name=line172 onclick='overload_click(this)' class="a_ln">172<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;for (<a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a> = <a href='ofono/src/plugin.c#line32' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>plugins</a>; <a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>; list = list-&gt;next) {
</div></div></div><div class="div_line"  data-info=({id:240228,ln:173}) id=l173><div class="dl_wrapper"><a name=line173 onclick='overload_click(this)' class="a_ln">173<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a> *plugin = <a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>-&gt;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:240229,ln:174}) id=l174><div class="dl_wrapper"><a name=line174 onclick='overload_click(this)' class="a_ln">174<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240230,ln:175}) id=l175><div class="dl_wrapper"><a name=line175 onclick='overload_click(this)' class="a_ln">175<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (plugin-&gt;desc-&gt;init() &lt; 0)
</div></div></div><div class="div_line"  data-info=({id:240231,ln:176}) id=l176><div class="dl_wrapper"><a name=line176 onclick='overload_click(this)' class="a_ln">176<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;continue;
</div></div></div><div class="div_line"  data-info=({id:240232,ln:177}) id=l177><div class="dl_wrapper"><a name=line177 onclick='overload_click(this)' class="a_ln">177<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240233,ln:178}) id=l178><div class="dl_wrapper"><a name=line178 onclick='overload_click(this)' class="a_ln">178<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;plugin-&gt;active = <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a>;
</div></div></div><div class="div_line"  data-info=({id:240234,ln:179}) id=l179><div class="dl_wrapper"><a name=line179 onclick='overload_click(this)' class="a_ln">179<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240235,ln:180}) id=l180><div class="dl_wrapper"><a name=line180 onclick='overload_click(this)' class="a_ln">180<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240236,ln:181}) id=l181><div class="dl_wrapper"><a name=line181 onclick='overload_click(this)' class="a_ln">181<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_strfreev(patterns);
</div></div></div><div class="div_line"  data-info=({id:240237,ln:182}) id=l182><div class="dl_wrapper"><a name=line182 onclick='overload_click(this)' class="a_ln">182<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_strfreev(excludes);
</div></div></div><div class="div_line"  data-info=({id:240238,ln:183}) id=l183><div class="dl_wrapper"><a name=line183 onclick='overload_click(this)' class="a_ln">183<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240239,ln:184}) id=l184><div class="dl_wrapper"><a name=line184 onclick='overload_click(this)' class="a_ln">184<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;return 0;
</div></div></div><div class="div_line"  data-info=({id:240240,ln:185}) id=l185><div class="dl_wrapper"><a name=line185 onclick='overload_click(this)' class="a_ln">185<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:240241,ln:186}) id=l186><div class="dl_wrapper"><a name=line186 onclick='overload_click(this)' class="a_ln">186<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240242,ln:187}) id=l187><div class="dl_wrapper"><a name=line187 onclick='overload_click(this)' class="a_ln">187<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <span class='ctd fndef'>__ofono_plugin_cleanup</span>(void)
</div></div></div><div class="div_line"  data-info=({id:240243,ln:188}) id=l188><div class="dl_wrapper"><a name=line188 onclick='overload_click(this)' class="a_ln">188<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">{
</div></div></div><div class="div_line"  data-info=({id:240244,ln:189}) id=l189><div class="dl_wrapper"><a name=line189 onclick='overload_click(this)' class="a_ln">189<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;GSList *<a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>;
</div></div></div><div class="div_line"  data-info=({id:240245,ln:190}) id=l190><div class="dl_wrapper"><a name=line190 onclick='overload_click(this)' class="a_ln">190<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240246,ln:191}) id=l191><div class="dl_wrapper"><a name=line191 onclick='overload_click(this)' class="a_ln">191<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;DBG("");
</div></div></div><div class="div_line"  data-info=({id:240247,ln:192}) id=l192><div class="dl_wrapper"><a name=line192 onclick='overload_click(this)' class="a_ln">192<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240248,ln:193}) id=l193><div class="dl_wrapper"><a name=line193 onclick='overload_click(this)' class="a_ln">193<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;for (<a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a> = <a href='ofono/src/plugin.c#line32' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>plugins</a>; <a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>; list = list-&gt;next) {
</div></div></div><div class="div_line"  data-info=({id:240249,ln:194}) id=l194><div class="dl_wrapper"><a name=line194 onclick='overload_click(this)' class="a_ln">194<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;struct <a href='ofono/src/plugin.c#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_plugin</a> *plugin = <a href='ofono/unit/test-stkutil.c#line4122' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:44})'>list</a>-&gt;<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>;
</div></div></div><div class="div_line"  data-info=({id:240250,ln:195}) id=l195><div class="dl_wrapper"><a name=line195 onclick='overload_click(this)' class="a_ln">195<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240251,ln:196}) id=l196><div class="dl_wrapper"><a name=line196 onclick='overload_click(this)' class="a_ln">196<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (plugin-&gt;active == <a href='ofono/include/types.h#line34' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>TRUE</a> && plugin-&gt;desc-&gt;exit)
</div></div></div><div class="div_line"  data-info=({id:240252,ln:197}) id=l197><div class="dl_wrapper"><a name=line197 onclick='overload_click(this)' class="a_ln">197<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;plugin-&gt;desc-&gt;exit();
</div></div></div><div class="div_line"  data-info=({id:240253,ln:198}) id=l198><div class="dl_wrapper"><a name=line198 onclick='overload_click(this)' class="a_ln">198<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240254,ln:199}) id=l199><div class="dl_wrapper"><a name=line199 onclick='overload_click(this)' class="a_ln">199<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (plugin-&gt;handle)
</div></div></div><div class="div_line"  data-info=({id:240255,ln:200}) id=l200><div class="dl_wrapper"><a name=line200 onclick='overload_click(this)' class="a_ln">200<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;dlclose(plugin-&gt;handle);
</div></div></div><div class="div_line"  data-info=({id:240256,ln:201}) id=l201><div class="dl_wrapper"><a name=line201 onclick='overload_click(this)' class="a_ln">201<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240257,ln:202}) id=l202><div class="dl_wrapper"><a name=line202 onclick='overload_click(this)' class="a_ln">202<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;g_free(plugin);
</div></div></div><div class="div_line"  data-info=({id:240258,ln:203}) id=l203><div class="dl_wrapper"><a name=line203 onclick='overload_click(this)' class="a_ln">203<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;}
</div></div></div><div class="div_line"  data-info=({id:240259,ln:204}) id=l204><div class="dl_wrapper"><a name=line204 onclick='overload_click(this)' class="a_ln">204<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:240260,ln:205}) id=l205><div class="dl_wrapper"><a name=line205 onclick='overload_click(this)' class="a_ln">205<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;g_slist_free(<a href='ofono/src/plugin.c#line32' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>plugins</a>);
</div></div></div><div class="div_line"  data-info=({id:240261,ln:206}) id=l206><div class="dl_wrapper"><a name=line206 onclick='overload_click(this)' class="a_ln">206<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><script>var local_symbol_set='([{name:"__ofono_plugin_cleanup",ln:187},{name:"__ofono_plugin_init",ln:104},{name:"active",ln:36},{name:"add_plugin",ln:48},{name:"check_plugin",ln:76},{name:"compare_priority",ln:40},{name:"desc",ln:37},{name:"handle",ln:35},{name:"ofono_plugin",ln:34},{name:"plugins",ln:32},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/src/plugin.c"})';
</script>