<div class="div_line"  data-info=({id:196992,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:196993,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:196994,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  oFono - Open Source Telephony
</div></div></div><div class="div_line"  data-info=({id:196995,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:196996,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2008-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:196997,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:196998,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:196999,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:197000,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:197001,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:197002,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:197003,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:197004,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:197005,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:197006,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:197007,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:197008,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:197009,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:197010,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:197011,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:197012,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197013,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd gvdef'>sim_fs</span>;
</div></div></div><div class="div_line"  data-info=({id:197014,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197015,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*<span class='ctd typedef'>sim_fs_read_info_cb_t</span>)(int ok, unsigned char file_status,
</div></div></div><div class="div_line"  data-info=({id:197016,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <span class='ctd typedef'>total_length</span>, int record_length,
</div></div></div><div class="div_line"  data-info=({id:197017,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *<span class='ctd typedef'>userdata</span>);
</div></div></div><div class="div_line"  data-info=({id:197018,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197019,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *<a href='ofono/src/simfs.c#line129' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_new</a>(struct <a href='ofono/src/sim.c#line51' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim</a> *sim,
</div></div></div><div class="div_line"  data-info=({id:197020,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/include/sim.h#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_driver</a> *<a href='ofono/drivers/atmodem/call-barring.c#line215' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:86})'>driver</a>);
</div></div></div><div class="div_line"  data-info=({id:197021,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *<a href='ofono/src/simfs.c#line145' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_context_new</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs);
</div></div></div><div class="div_line"  data-info=({id:197022,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197023,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">unsigned int <a href='ofono/src/simfs.c#line191' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_file_watch_add</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context,
</div></div></div><div class="div_line"  data-info=({id:197024,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>, ofono_sim_file_changed_cb_t cb,
</div></div></div><div class="div_line"  data-info=({id:197025,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;void *userdata,
</div></div></div><div class="div_line"  data-info=({id:197026,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_destroy_func destroy);
</div></div></div><div class="div_line"  data-info=({id:197027,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line215' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_file_watch_remove</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context,
</div></div></div><div class="div_line"  data-info=({id:197028,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197029,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197030,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* Id of -1 notifies all watches, serving as a wildcard */
</div></div></div><div class="div_line"  data-info=({id:197031,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line221' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_notify_file_watches</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197032,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197033,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/simfs.c#line899' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_read</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:197034,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;enum <a href='ofono/include/sim.h#line35' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_file_structure</a> expected_type,
</div></div></div><div class="div_line"  data-info=({id:197035,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;unsigned short offset, unsigned short num_bytes,
</div></div></div><div class="div_line"  data-info=({id:197036,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const unsigned char *path, unsigned int <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>,
</div></div></div><div class="div_line"  data-info=({id:197037,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_sim_file_read_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:197038,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197039,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/simfs.c#line860' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_read_info</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:197040,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;enum <a href='ofono/include/sim.h#line35' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_file_structure</a> expected_type,
</div></div></div><div class="div_line"  data-info=({id:197041,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;sim_fs_read_info_cb_t cb, void *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:197042,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197043,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1108' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_check_version</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs);
</div></div></div><div class="div_line"  data-info=({id:197044,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197045,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">int <a href='ofono/src/simfs.c#line946' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_write</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>,
</div></div></div><div class="div_line"  data-info=({id:197046,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;ofono_sim_file_write_cb_t cb,
</div></div></div><div class="div_line"  data-info=({id:197047,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;enum <a href='ofono/include/sim.h#line35' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_file_structure</a> structure, int record,
</div></div></div><div class="div_line"  data-info=({id:197048,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const unsigned char *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>, int length, void *userdata);
</div></div></div><div class="div_line"  data-info=({id:197049,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197050,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">char *<a href='ofono/src/simfs.c#line1024' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_get_cached_image</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197051,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197052,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1003' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_cache_image</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs, const char *image, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197053,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197054,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1127' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_cache_flush</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs);
</div></div></div><div class="div_line"  data-info=({id:197055,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1150' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_cache_flush_file</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197056,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1160' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_image_cache_flush</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs);
</div></div></div><div class="div_line"  data-info=({id:197057,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line1182' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_image_cache_flush_file</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs, int <a href='ofono/plugins/connman.c#line51' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:244})'>id</a>);
</div></div></div><div class="div_line"  data-info=({id:197058,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:197059,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line93' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_free</a>(struct <a href='ofono/src/simfs.c#line83' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>sim_fs</a> *fs);
</div></div></div><div class="div_line"  data-info=({id:197060,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/src/simfs.c#line159' class='a_code_tag ' data-info='({type:"fncall",tagreg:1})'>sim_fs_context_free</a>(struct <a href='ofono/src/simfs.c#line124' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>ofono_sim_context</a> *context);
</div></div></div><script>var local_symbol_set='([{name:"sim_fs_read_info_cb_t",ln:24},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/src/simfs.h"})';
</script>