<div class="div_line"  data-info=({id:114760,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:114761,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114762,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  PPP library with GLib integration
</div></div></div><div class="div_line"  data-info=({id:114763,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114764,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2009-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:114765,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114766,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:114767,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:114768,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:114769,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114770,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:114771,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:114772,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:114773,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:114774,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114775,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:114776,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:114777,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:114778,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114779,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:114780,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114781,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifndef <a href='ofono/gatchat/gatppp.h#line23' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>__G_AT_PPP_H</a>
</div></div></div><div class="div_line"  data-info=({id:114782,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#define <span class='ctd macdef'>__G_AT_PPP_H</span>
</div></div></div><div class="div_line"  data-info=({id:114783,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114784,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:114785,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">extern "C" {
</div></div></div><div class="div_line"  data-info=({id:114786,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:114787,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114788,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>gat.h</span>"
</div></div></div><div class="div_line"  data-info=({id:114789,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#include "<span class='ctd include'>gathdlc.h</span>"
</div></div></div><div class="div_line"  data-info=({id:114790,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114791,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/gatchat/gatppp.c#line60' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GAtPPP</a>;
</div></div></div><div class="div_line"  data-info=({id:114792,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114793,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef struct <a href='ofono/gatchat/gatppp.c#line60' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>_GAtPPP</a> <span class='ctd typedef'>GAtPPP</span>;
</div></div></div><div class="div_line"  data-info=({id:114794,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114795,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef enum <span class='ctd enumdef'>_GAtPPPDisconnectReason</span> {
</div></div></div><div class="div_line"  data-info=({id:114796,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_UNKNOWN,
</div></div></div><div class="div_line"  data-info=({id:114797,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_AUTH_FAIL,&#160;&#160;&#160;&#160;/* Failed to authenticate */
</div></div></div><div class="div_line"  data-info=({id:114798,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_IPCP_FAIL,&#160;&#160;&#160;&#160;/* Failed to negotiate IPCP */
</div></div></div><div class="div_line"  data-info=({id:114799,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_NET_FAIL,&#160;&#160;&#160;&#160;/* Failed to create tun */
</div></div></div><div class="div_line"  data-info=({id:114800,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_PEER_CLOSED,&#160;&#160;&#160;&#160;/* Peer initiated a close */
</div></div></div><div class="div_line"  data-info=({id:114801,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_LINK_DEAD,&#160;&#160;&#160;&#160;/* Link to the peer died */
</div></div></div><div class="div_line"  data-info=({id:114802,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_REASON_LOCAL_CLOSE,&#160;&#160;&#160;&#160;/* Normal user close */
</div></div></div><div class="div_line"  data-info=({id:114803,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>GAtPPPDisconnectReason</span>;
</div></div></div><div class="div_line"  data-info=({id:114804,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114805,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef enum <span class='ctd enumdef'>_GAtPPPAuthMethod</span> {
</div></div></div><div class="div_line"  data-info=({id:114806,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_AUTH_METHOD_CHAP,
</div></div></div><div class="div_line"  data-info=({id:114807,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;G_AT_PPP_AUTH_METHOD_PAP,
</div></div></div><div class="div_line"  data-info=({id:114808,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} <span class='ctd typedef'>GAtPPPAuthMethod</span>;
</div></div></div><div class="div_line"  data-info=({id:114809,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114810,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*GAtPPPConnectFunc)(const char *<span class='ctd typedef'>iface</span>, const char *local,
</div></div></div><div class="div_line"  data-info=({id:114811,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<span class='ctd typedef'>peer</span>,
</div></div></div><div class="div_line"  data-info=({id:114812,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *<span class='ctd typedef'>dns1</span>, const char *dns2,
</div></div></div><div class="div_line"  data-info=({id:114813,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<span class='ctd typedef'>gpointer</span> user_data);
</div></div></div><div class="div_line"  data-info=({id:114814,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">typedef void (*GAtPPPDisconnectFunc)(<span class='ctd typedef'>GAtPPPDisconnectReason</span> reason,
</div></div></div><div class="div_line"  data-info=({id:114815,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;<span class='ctd typedef'>gpointer</span> user_data);
</div></div></div><div class="div_line"  data-info=({id:114816,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114817,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GAtPPP *g_at_ppp_new(void);
</div></div></div><div class="div_line"  data-info=({id:114818,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GAtPPP *g_at_ppp_server_new(const char *local);
</div></div></div><div class="div_line"  data-info=({id:114819,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GAtPPP *g_at_ppp_server_new_full(const char *local, int fd);
</div></div></div><div class="div_line"  data-info=({id:114820,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114821,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gboolean g_at_ppp_open(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtIO *io);
</div></div></div><div class="div_line"  data-info=({id:114822,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gboolean g_at_ppp_listen(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtIO *io);
</div></div></div><div class="div_line"  data-info=({id:114823,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_connect_function(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtPPPConnectFunc callback,
</div></div></div><div class="div_line"  data-info=({id:114824,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:114825,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_disconnect_function(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtPPPDisconnectFunc func,
</div></div></div><div class="div_line"  data-info=({id:114826,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:114827,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_suspend_function(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtSuspendFunc func,
</div></div></div><div class="div_line"  data-info=({id:114828,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:114829,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_debug(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtDebugFunc func, gpointer user_data);
</div></div></div><div class="div_line"  data-info=({id:114830,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_shutdown(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114831,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_suspend(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114832,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_resume(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114833,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_ref(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114834,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_unref(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114835,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114836,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gboolean g_at_ppp_set_credentials(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, const char *username,
</div></div></div><div class="div_line"  data-info=({id:114837,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *passwd);
</div></div></div><div class="div_line"  data-info=({id:114838,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">const char *g_at_ppp_get_username(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114839,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">const char *g_at_ppp_get_password(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114840,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114841,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gboolean g_at_ppp_set_auth_method(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, GAtPPPAuthMethod method);
</div></div></div><div class="div_line"  data-info=({id:114842,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GAtPPPAuthMethod g_at_ppp_get_auth_method(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>);
</div></div></div><div class="div_line"  data-info=({id:114843,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114844,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_recording(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, const char *filename);
</div></div></div><div class="div_line"  data-info=({id:114845,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114846,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_server_info(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, const char *remote_ip,
</div></div></div><div class="div_line"  data-info=({id:114847,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const char *dns1, const char *dns2);
</div></div></div><div class="div_line"  data-info=({id:114848,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114849,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_acfc_enabled(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, gboolean <a href='ofono/src/log.c#line247' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>enabled</a>);
</div></div></div><div class="div_line"  data-info=({id:114850,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void g_at_ppp_set_pfc_enabled(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, gboolean <a href='ofono/src/log.c#line247' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>enabled</a>);
</div></div></div><div class="div_line"  data-info=({id:114851,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114852,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#ifdef __cplusplus
</div></div></div><div class="div_line"  data-info=({id:114853,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">}
</div></div></div><div class="div_line"  data-info=({id:114854,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif
</div></div></div><div class="div_line"  data-info=({id:114855,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114856,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">#endif /* __G_AT_PPP_H */
</div></div></div><script>var local_symbol_set='([{name:"GAtPPP",ln:34},{name:"GAtPPPAuthMethod",ln:49},{name:"GAtPPPConnectFunc",ln:51},{name:"GAtPPPDisconnectFunc",ln:55},{name:"GAtPPPDisconnectReason",ln:44},{name:"G_AT_PPP_AUTH_METHOD_CHAP",ln:47},{name:"G_AT_PPP_AUTH_METHOD_PAP",ln:48},{name:"G_AT_PPP_REASON_AUTH_FAIL",ln:38},{name:"G_AT_PPP_REASON_IPCP_FAIL",ln:39},{name:"G_AT_PPP_REASON_LINK_DEAD",ln:42},{name:"G_AT_PPP_REASON_LOCAL_CLOSE",ln:43},{name:"G_AT_PPP_REASON_NET_FAIL",ln:40},{name:"G_AT_PPP_REASON_PEER_CLOSED",ln:41},{name:"G_AT_PPP_REASON_UNKNOWN",ln:37},{name:"_GAtPPPAuthMethod",ln:46},{name:"_GAtPPPDisconnectReason",ln:36},{name:"__G_AT_PPP_H",ln:23},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/gatchat/gatppp.h"})';
</script>