<div class="div_line"  data-info=({id:114857,ln:1}) id=l1><div class="dl_wrapper"><a name=line1 onclick='overload_click(this)' class="a_ln">1<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/*
</div></div></div><div class="div_line"  data-info=({id:114858,ln:2}) id=l2><div class="dl_wrapper"><a name=line2 onclick='overload_click(this)' class="a_ln">2<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114859,ln:3}) id=l3><div class="dl_wrapper"><a name=line3 onclick='overload_click(this)' class="a_ln">3<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  PPP library with GLib integration
</div></div></div><div class="div_line"  data-info=({id:114860,ln:4}) id=l4><div class="dl_wrapper"><a name=line4 onclick='overload_click(this)' class="a_ln">4<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114861,ln:5}) id=l5><div class="dl_wrapper"><a name=line5 onclick='overload_click(this)' class="a_ln">5<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Copyright (C) 2009-2011  Intel Corporation. All rights reserved.
</div></div></div><div class="div_line"  data-info=({id:114862,ln:6}) id=l6><div class="dl_wrapper"><a name=line6 onclick='overload_click(this)' class="a_ln">6<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114863,ln:7}) id=l7><div class="dl_wrapper"><a name=line7 onclick='overload_click(this)' class="a_ln">7<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is free software; you can redistribute it and/or modify
</div></div></div><div class="div_line"  data-info=({id:114864,ln:8}) id=l8><div class="dl_wrapper"><a name=line8 onclick='overload_click(this)' class="a_ln">8<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  it under the terms of the GNU General Public License version 2 as
</div></div></div><div class="div_line"  data-info=({id:114865,ln:9}) id=l9><div class="dl_wrapper"><a name=line9 onclick='overload_click(this)' class="a_ln">9<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  published by the Free Software Foundation.
</div></div></div><div class="div_line"  data-info=({id:114866,ln:10}) id=l10><div class="dl_wrapper"><a name=line10 onclick='overload_click(this)' class="a_ln">10<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114867,ln:11}) id=l11><div class="dl_wrapper"><a name=line11 onclick='overload_click(this)' class="a_ln">11<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  This program is distributed in the hope that it will be useful,
</div></div></div><div class="div_line"  data-info=({id:114868,ln:12}) id=l12><div class="dl_wrapper"><a name=line12 onclick='overload_click(this)' class="a_ln">12<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  but WITHOUT ANY WARRANTY; without even the implied warranty of
</div></div></div><div class="div_line"  data-info=({id:114869,ln:13}) id=l13><div class="dl_wrapper"><a name=line13 onclick='overload_click(this)' class="a_ln">13<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
</div></div></div><div class="div_line"  data-info=({id:114870,ln:14}) id=l14><div class="dl_wrapper"><a name=line14 onclick='overload_click(this)' class="a_ln">14<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  GNU General Public License for more details.
</div></div></div><div class="div_line"  data-info=({id:114871,ln:15}) id=l15><div class="dl_wrapper"><a name=line15 onclick='overload_click(this)' class="a_ln">15<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114872,ln:16}) id=l16><div class="dl_wrapper"><a name=line16 onclick='overload_click(this)' class="a_ln">16<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  You should have received a copy of the GNU General Public License
</div></div></div><div class="div_line"  data-info=({id:114873,ln:17}) id=l17><div class="dl_wrapper"><a name=line17 onclick='overload_click(this)' class="a_ln">17<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  along with this program; if not, write to the Free Software
</div></div></div><div class="div_line"  data-info=({id:114874,ln:18}) id=l18><div class="dl_wrapper"><a name=line18 onclick='overload_click(this)' class="a_ln">18<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
</div></div></div><div class="div_line"  data-info=({id:114875,ln:19}) id=l19><div class="dl_wrapper"><a name=line19 onclick='overload_click(this)' class="a_ln">19<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> *
</div></div></div><div class="div_line"  data-info=({id:114876,ln:20}) id=l20><div class="dl_wrapper"><a name=line20 onclick='overload_click(this)' class="a_ln">20<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents"> */
</div></div></div><div class="div_line"  data-info=({id:114877,ln:21}) id=l21><div class="dl_wrapper"><a name=line21 onclick='overload_click(this)' class="a_ln">21<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114878,ln:22}) id=l22><div class="dl_wrapper"><a name=line22 onclick='overload_click(this)' class="a_ln">22<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd gvdef'>pppcp_data</span>;
</div></div></div><div class="div_line"  data-info=({id:114879,ln:23}) id=l23><div class="dl_wrapper"><a name=line23 onclick='overload_click(this)' class="a_ln">23<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd gvdef'>ppp_option_iter</span>;
</div></div></div><div class="div_line"  data-info=({id:114880,ln:24}) id=l24><div class="dl_wrapper"><a name=line24 onclick='overload_click(this)' class="a_ln">24<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114881,ln:25}) id=l25><div class="dl_wrapper"><a name=line25 onclick='overload_click(this)' class="a_ln">25<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">/* option format */
</div></div></div><div class="div_line"  data-info=({id:114882,ln:26}) id=l26><div class="dl_wrapper"><a name=line26 onclick='overload_click(this)' class="a_ln">26<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ppp_option</span> {
</div></div></div><div class="div_line"  data-info=({id:114883,ln:27}) id=l27><div class="dl_wrapper"><a name=line27 onclick='overload_click(this)' class="a_ln">27<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>type</span>;
</div></div></div><div class="div_line"  data-info=({id:114884,ln:28}) id=l28><div class="dl_wrapper"><a name=line28 onclick='overload_click(this)' class="a_ln">28<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>length</span>;
</div></div></div><div class="div_line"  data-info=({id:114885,ln:29}) id=l29><div class="dl_wrapper"><a name=line29 onclick='overload_click(this)' class="a_ln">29<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>data</span>[0];
</div></div></div><div class="div_line"  data-info=({id:114886,ln:30}) id=l30><div class="dl_wrapper"><a name=line30 onclick='overload_click(this)' class="a_ln">30<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:114887,ln:31}) id=l31><div class="dl_wrapper"><a name=line31 onclick='overload_click(this)' class="a_ln">31<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114888,ln:32}) id=l32><div class="dl_wrapper"><a name=line32 onclick='overload_click(this)' class="a_ln">32<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">enum <span class='ctd enumdef'>rcr_result</span> {
</div></div></div><div class="div_line"  data-info=({id:114889,ln:33}) id=l33><div class="dl_wrapper"><a name=line33 onclick='overload_click(this)' class="a_ln">33<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>RCR_ACCEPT</span>,
</div></div></div><div class="div_line"  data-info=({id:114890,ln:34}) id=l34><div class="dl_wrapper"><a name=line34 onclick='overload_click(this)' class="a_ln">34<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>RCR_REJECT</span>,
</div></div></div><div class="div_line"  data-info=({id:114891,ln:35}) id=l35><div class="dl_wrapper"><a name=line35 onclick='overload_click(this)' class="a_ln">35<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>RCR_NAK</span>,
</div></div></div><div class="div_line"  data-info=({id:114892,ln:36}) id=l36><div class="dl_wrapper"><a name=line36 onclick='overload_click(this)' class="a_ln">36<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:114893,ln:37}) id=l37><div class="dl_wrapper"><a name=line37 onclick='overload_click(this)' class="a_ln">37<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114894,ln:38}) id=l38><div class="dl_wrapper"><a name=line38 onclick='overload_click(this)' class="a_ln">38<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">enum <span class='ctd enumdef'>pppcp_code</span> {
</div></div></div><div class="div_line"  data-info=({id:114895,ln:39}) id=l39><div class="dl_wrapper"><a name=line39 onclick='overload_click(this)' class="a_ln">39<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_CONFIGURE_REQUEST</span> = 1,
</div></div></div><div class="div_line"  data-info=({id:114896,ln:40}) id=l40><div class="dl_wrapper"><a name=line40 onclick='overload_click(this)' class="a_ln">40<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_CONFIGURE_ACK</span>,
</div></div></div><div class="div_line"  data-info=({id:114897,ln:41}) id=l41><div class="dl_wrapper"><a name=line41 onclick='overload_click(this)' class="a_ln">41<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_CONFIGURE_NAK</span>,
</div></div></div><div class="div_line"  data-info=({id:114898,ln:42}) id=l42><div class="dl_wrapper"><a name=line42 onclick='overload_click(this)' class="a_ln">42<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_CONFIGURE_REJECT</span>,
</div></div></div><div class="div_line"  data-info=({id:114899,ln:43}) id=l43><div class="dl_wrapper"><a name=line43 onclick='overload_click(this)' class="a_ln">43<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_TERMINATE_REQUEST</span>,
</div></div></div><div class="div_line"  data-info=({id:114900,ln:44}) id=l44><div class="dl_wrapper"><a name=line44 onclick='overload_click(this)' class="a_ln">44<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_TERMINATE_ACK</span>,
</div></div></div><div class="div_line"  data-info=({id:114901,ln:45}) id=l45><div class="dl_wrapper"><a name=line45 onclick='overload_click(this)' class="a_ln">45<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_CODE_REJECT</span>,
</div></div></div><div class="div_line"  data-info=({id:114902,ln:46}) id=l46><div class="dl_wrapper"><a name=line46 onclick='overload_click(this)' class="a_ln">46<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_PROTOCOL_REJECT</span>,
</div></div></div><div class="div_line"  data-info=({id:114903,ln:47}) id=l47><div class="dl_wrapper"><a name=line47 onclick='overload_click(this)' class="a_ln">47<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_ECHO_REQUEST</span>,
</div></div></div><div class="div_line"  data-info=({id:114904,ln:48}) id=l48><div class="dl_wrapper"><a name=line48 onclick='overload_click(this)' class="a_ln">48<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_ECHO_REPLY</span>,
</div></div></div><div class="div_line"  data-info=({id:114905,ln:49}) id=l49><div class="dl_wrapper"><a name=line49 onclick='overload_click(this)' class="a_ln">49<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;<span class='ctd member'>PPPCP_CODE_TYPE_DISCARD_REQUEST</span>
</div></div></div><div class="div_line"  data-info=({id:114906,ln:50}) id=l50><div class="dl_wrapper"><a name=line50 onclick='overload_click(this)' class="a_ln">50<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:114907,ln:51}) id=l51><div class="dl_wrapper"><a name=line51 onclick='overload_click(this)' class="a_ln">51<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114908,ln:52}) id=l52><div class="dl_wrapper"><a name=line52 onclick='overload_click(this)' class="a_ln">52<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>pppcp_packet</span> {
</div></div></div><div class="div_line"  data-info=({id:114909,ln:53}) id=l53><div class="dl_wrapper"><a name=line53 onclick='overload_click(this)' class="a_ln">53<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>code</span>;
</div></div></div><div class="div_line"  data-info=({id:114910,ln:54}) id=l54><div class="dl_wrapper"><a name=line54 onclick='overload_click(this)' class="a_ln">54<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>identifier</span>;
</div></div></div><div class="div_line"  data-info=({id:114911,ln:55}) id=l55><div class="dl_wrapper"><a name=line55 onclick='overload_click(this)' class="a_ln">55<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint16 <span class='ctd member'>length</span>;
</div></div></div><div class="div_line"  data-info=({id:114912,ln:56}) id=l56><div class="dl_wrapper"><a name=line56 onclick='overload_click(this)' class="a_ln">56<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>data</span>[0];
</div></div></div><div class="div_line"  data-info=({id:114913,ln:57}) id=l57><div class="dl_wrapper"><a name=line57 onclick='overload_click(this)' class="a_ln">57<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">} __attribute__((<a href='ofono/unit/test-stkutil.c#line16750' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>packed</a>));
</div></div></div><div class="div_line"  data-info=({id:114914,ln:58}) id=l58><div class="dl_wrapper"><a name=line58 onclick='overload_click(this)' class="a_ln">58<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114915,ln:59}) id=l59><div class="dl_wrapper"><a name=line59 onclick='overload_click(this)' class="a_ln">59<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>ppp_option_iter</span> {
</div></div></div><div class="div_line"  data-info=({id:114916,ln:60}) id=l60><div class="dl_wrapper"><a name=line60 onclick='overload_click(this)' class="a_ln">60<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint16 <span class='ctd member'>max</span>;
</div></div></div><div class="div_line"  data-info=({id:114917,ln:61}) id=l61><div class="dl_wrapper"><a name=line61 onclick='overload_click(this)' class="a_ln">61<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint16 <span class='ctd member'>pos</span>;
</div></div></div><div class="div_line"  data-info=({id:114918,ln:62}) id=l62><div class="dl_wrapper"><a name=line62 onclick='overload_click(this)' class="a_ln">62<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const guint8 *<span class='ctd member'>pdata</span>;
</div></div></div><div class="div_line"  data-info=({id:114919,ln:63}) id=l63><div class="dl_wrapper"><a name=line63 onclick='overload_click(this)' class="a_ln">63<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>type</span>;
</div></div></div><div class="div_line"  data-info=({id:114920,ln:64}) id=l64><div class="dl_wrapper"><a name=line64 onclick='overload_click(this)' class="a_ln">64<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint8 <span class='ctd member'>len</span>;
</div></div></div><div class="div_line"  data-info=({id:114921,ln:65}) id=l65><div class="dl_wrapper"><a name=line65 onclick='overload_click(this)' class="a_ln">65<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const guint8 *<span class='ctd member'>option_data</span>;
</div></div></div><div class="div_line"  data-info=({id:114922,ln:66}) id=l66><div class="dl_wrapper"><a name=line66 onclick='overload_click(this)' class="a_ln">66<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:114923,ln:67}) id=l67><div class="dl_wrapper"><a name=line67 onclick='overload_click(this)' class="a_ln">67<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114924,ln:68}) id=l68><div class="dl_wrapper"><a name=line68 onclick='overload_click(this)' class="a_ln">68<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <span class='ctd strdef'>pppcp_proto</span> {
</div></div></div><div class="div_line"  data-info=({id:114925,ln:69}) id=l69><div class="dl_wrapper"><a name=line69 onclick='overload_click(this)' class="a_ln">69<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint16 <span class='ctd member'>proto</span>;
</div></div></div><div class="div_line"  data-info=({id:114926,ln:70}) id=l70><div class="dl_wrapper"><a name=line70 onclick='overload_click(this)' class="a_ln">70<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;const char *<span class='ctd member'>name</span>;
</div></div></div><div class="div_line"  data-info=({id:114927,ln:71}) id=l71><div class="dl_wrapper"><a name=line71 onclick='overload_click(this)' class="a_ln">71<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;guint16 <span class='ctd member'>supported_codes</span>;
</div></div></div><div class="div_line"  data-info=({id:114928,ln:72}) id=l72><div class="dl_wrapper"><a name=line72 onclick='overload_click(this)' class="a_ln">72<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>this_layer_up</span>)(struct pppcp_data *data);
</div></div></div><div class="div_line"  data-info=({id:114929,ln:73}) id=l73><div class="dl_wrapper"><a name=line73 onclick='overload_click(this)' class="a_ln">73<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>this_layer_down</span>)(struct pppcp_data *data);
</div></div></div><div class="div_line"  data-info=({id:114930,ln:74}) id=l74><div class="dl_wrapper"><a name=line74 onclick='overload_click(this)' class="a_ln">74<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>this_layer_started</span>)(struct pppcp_data *data);
</div></div></div><div class="div_line"  data-info=({id:114931,ln:75}) id=l75><div class="dl_wrapper"><a name=line75 onclick='overload_click(this)' class="a_ln">75<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>this_layer_finished</span>)(struct pppcp_data *data);
</div></div></div><div class="div_line"  data-info=({id:114932,ln:76}) id=l76><div class="dl_wrapper"><a name=line76 onclick='overload_click(this)' class="a_ln">76<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/* Remote side acked these options, we can now use them */
</div></div></div><div class="div_line"  data-info=({id:114933,ln:77}) id=l77><div class="dl_wrapper"><a name=line77 onclick='overload_click(this)' class="a_ln">77<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>rca</span>)(struct pppcp_data *pppcp, const struct pppcp_packet *pkt);
</div></div></div><div class="div_line"  data-info=({id:114934,ln:78}) id=l78><div class="dl_wrapper"><a name=line78 onclick='overload_click(this)' class="a_ln">78<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:114935,ln:79}) id=l79><div class="dl_wrapper"><a name=line79 onclick='overload_click(this)' class="a_ln">79<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Remote side sent us an Conf-Req-Nak or Conf-Req-Rej.  The protocol
</div></div></div><div class="div_line"  data-info=({id:114936,ln:80}) id=l80><div class="dl_wrapper"><a name=line80 onclick='overload_click(this)' class="a_ln">80<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * driver should examine the packet and update its options accordingly,
</div></div></div><div class="div_line"  data-info=({id:114937,ln:81}) id=l81><div class="dl_wrapper"><a name=line81 onclick='overload_click(this)' class="a_ln">81<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * then use set_local_options to set a new set of options to try
</div></div></div><div class="div_line"  data-info=({id:114938,ln:82}) id=l82><div class="dl_wrapper"><a name=line82 onclick='overload_click(this)' class="a_ln">82<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * before returning
</div></div></div><div class="div_line"  data-info=({id:114939,ln:83}) id=l83><div class="dl_wrapper"><a name=line83 onclick='overload_click(this)' class="a_ln">83<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:114940,ln:84}) id=l84><div class="dl_wrapper"><a name=line84 onclick='overload_click(this)' class="a_ln">84<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>rcn_nak</span>)(struct pppcp_data *pppcp,
</div></div></div><div class="div_line"  data-info=({id:114941,ln:85}) id=l85><div class="dl_wrapper"><a name=line85 onclick='overload_click(this)' class="a_ln">85<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/gatchat/ppp_cp.h#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>pppcp_packet</a> *<span class='ctd member'>pkt</span>);
</div></div></div><div class="div_line"  data-info=({id:114942,ln:86}) id=l86><div class="dl_wrapper"><a name=line86 onclick='overload_click(this)' class="a_ln">86<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;void (*<span class='ctd member'>rcn_rej</span>)(struct pppcp_data *pppcp,
</div></div></div><div class="div_line"  data-info=({id:114943,ln:87}) id=l87><div class="dl_wrapper"><a name=line87 onclick='overload_click(this)' class="a_ln">87<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/gatchat/ppp_cp.h#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>pppcp_packet</a> *<span class='ctd member'>pkt</span>);
</div></div></div><div class="div_line"  data-info=({id:114944,ln:88}) id=l88><div class="dl_wrapper"><a name=line88 onclick='overload_click(this)' class="a_ln">88<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;/*
</div></div></div><div class="div_line"  data-info=({id:114945,ln:89}) id=l89><div class="dl_wrapper"><a name=line89 onclick='overload_click(this)' class="a_ln">89<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * Remote side has sent us a request with its options, return whether
</div></div></div><div class="div_line"  data-info=({id:114946,ln:90}) id=l90><div class="dl_wrapper"><a name=line90 onclick='overload_click(this)' class="a_ln">90<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * we should ack / nak / rej these options.  In the case of nak / rej,
</div></div></div><div class="div_line"  data-info=({id:114947,ln:91}) id=l91><div class="dl_wrapper"><a name=line91 onclick='overload_click(this)' class="a_ln">91<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * the list of options to be sent to the peer is given in the
</div></div></div><div class="div_line"  data-info=({id:114948,ln:92}) id=l92><div class="dl_wrapper"><a name=line92 onclick='overload_click(this)' class="a_ln">92<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; * new_options & new_len out arguments
</div></div></div><div class="div_line"  data-info=({id:114949,ln:93}) id=l93><div class="dl_wrapper"><a name=line93 onclick='overload_click(this)' class="a_ln">93<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160; */
</div></div></div><div class="div_line"  data-info=({id:114950,ln:94}) id=l94><div class="dl_wrapper"><a name=line94 onclick='overload_click(this)' class="a_ln">94<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;enum <a href='ofono/gatchat/ppp_cp.h#line32' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>rcr_result</a> (*<a href='ofono/gatchat/ppp_ipcp.c#line459' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:3})'>rcr</a>)(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<span class='ctd member'>pppcp</span>,
</div></div></div><div class="div_line"  data-info=({id:114951,ln:95}) id=l95><div class="dl_wrapper"><a name=line95 onclick='overload_click(this)' class="a_ln">95<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/gatchat/ppp_cp.h#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>pppcp_packet</a> *<span class='ctd member'>pkt</span>,
</div></div></div><div class="div_line"  data-info=({id:114952,ln:96}) id=l96><div class="dl_wrapper"><a name=line96 onclick='overload_click(this)' class="a_ln">96<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;guint8 **<span class='ctd member'>new_options</span>, guint16 *new_len);
</div></div></div><div class="div_line"  data-info=({id:114953,ln:97}) id=l97><div class="dl_wrapper"><a name=line97 onclick='overload_click(this)' class="a_ln">97<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">};
</div></div></div><div class="div_line"  data-info=({id:114954,ln:98}) id=l98><div class="dl_wrapper"><a name=line98 onclick='overload_click(this)' class="a_ln">98<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114955,ln:99}) id=l99><div class="dl_wrapper"><a name=line99 onclick='overload_click(this)' class="a_ln">99<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void <a href='ofono/gatchat/ppp_cp.h#line23' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp_option_iter</a>_init(struct ppp_option_iter *iter,
</div></div></div><div class="div_line"  data-info=({id:114956,ln:100}) id=l100><div class="dl_wrapper"><a name=line100 onclick='overload_click(this)' class="a_ln">100<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const struct <a href='ofono/gatchat/ppp_cp.h#line52' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>pppcp_packet</a> *packet);
</div></div></div><div class="div_line"  data-info=({id:114957,ln:101}) id=l101><div class="dl_wrapper"><a name=line101 onclick='overload_click(this)' class="a_ln">101<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gboolean <a href='ofono/gatchat/ppp_cp.h#line23' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp_option_iter</a>_next(struct ppp_option_iter *iter);
</div></div></div><div class="div_line"  data-info=({id:114958,ln:102}) id=l102><div class="dl_wrapper"><a name=line102 onclick='overload_click(this)' class="a_ln">102<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">guint8 <a href='ofono/gatchat/ppp_cp.h#line23' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp_option_iter</a>_get_type(struct ppp_option_iter *iter);
</div></div></div><div class="div_line"  data-info=({id:114959,ln:103}) id=l103><div class="dl_wrapper"><a name=line103 onclick='overload_click(this)' class="a_ln">103<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">guint8 <a href='ofono/gatchat/ppp_cp.h#line23' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp_option_iter</a>_get_length(struct ppp_option_iter *iter);
</div></div></div><div class="div_line"  data-info=({id:114960,ln:104}) id=l104><div class="dl_wrapper"><a name=line104 onclick='overload_click(this)' class="a_ln">104<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">const guint8 *<a href='ofono/gatchat/ppp_cp.h#line23' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp_option_iter</a>_get_data(struct ppp_option_iter *iter);
</div></div></div><div class="div_line"  data-info=({id:114961,ln:105}) id=l105><div class="dl_wrapper"><a name=line105 onclick='overload_click(this)' class="a_ln">105<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114962,ln:106}) id=l106><div class="dl_wrapper"><a name=line106 onclick='overload_click(this)' class="a_ln">106<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *pppcp_new(GAtPPP *<a href='ofono/gatchat/gsmdial.c#line63' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>ppp</a>, const struct <a href='ofono/gatchat/ppp_cp.h#line68' class='a_code_tag ' data-info='({type:"glref",tagreg:1})'>pppcp_proto</a> *proto,
</div></div></div><div class="div_line"  data-info=({id:114963,ln:107}) id=l107><div class="dl_wrapper"><a name=line107 onclick='overload_click(this)' class="a_ln">107<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;gboolean dormant, guint max_failure);
</div></div></div><div class="div_line"  data-info=({id:114964,ln:108}) id=l108><div class="dl_wrapper"><a name=line108 onclick='overload_click(this)' class="a_ln">108<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_free(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114965,ln:109}) id=l109><div class="dl_wrapper"><a name=line109 onclick='overload_click(this)' class="a_ln">109<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114966,ln:110}) id=l110><div class="dl_wrapper"><a name=line110 onclick='overload_click(this)' class="a_ln">110<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_set_data(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *pppcp, gpointer <a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114967,ln:111}) id=l111><div class="dl_wrapper"><a name=line111 onclick='overload_click(this)' class="a_ln">111<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">gpointer pppcp_get_data(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *pppcp);
</div></div></div><div class="div_line"  data-info=({id:114968,ln:112}) id=l112><div class="dl_wrapper"><a name=line112 onclick='overload_click(this)' class="a_ln">112<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">GAtPPP *pppcp_get_ppp(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *pppcp);
</div></div></div><div class="div_line"  data-info=({id:114969,ln:113}) id=l113><div class="dl_wrapper"><a name=line113 onclick='overload_click(this)' class="a_ln">113<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114970,ln:114}) id=l114><div class="dl_wrapper"><a name=line114 onclick='overload_click(this)' class="a_ln">114<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">guint8 pppcp_get_code(const guint8 *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114971,ln:115}) id=l115><div class="dl_wrapper"><a name=line115 onclick='overload_click(this)' class="a_ln">115<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114972,ln:116}) id=l116><div class="dl_wrapper"><a name=line116 onclick='overload_click(this)' class="a_ln">116<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_set_local_options(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>,
</div></div></div><div class="div_line"  data-info=({id:114973,ln:117}) id=l117><div class="dl_wrapper"><a name=line117 onclick='overload_click(this)' class="a_ln">117<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const guint8 *<a href='ofono/dundee/main.c#line148' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>options</a>,
</div></div></div><div class="div_line"  data-info=({id:114974,ln:118}) id=l118><div class="dl_wrapper"><a name=line118 onclick='overload_click(this)' class="a_ln">118<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;guint16 <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:114975,ln:119}) id=l119><div class="dl_wrapper"><a name=line119 onclick='overload_click(this)' class="a_ln">119<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">
</div></div></div><div class="div_line"  data-info=({id:114976,ln:120}) id=l120><div class="dl_wrapper"><a name=line120 onclick='overload_click(this)' class="a_ln">120<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_process_packet(gpointer priv, const guint8 *new_packet, gsize <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:114977,ln:121}) id=l121><div class="dl_wrapper"><a name=line121 onclick='overload_click(this)' class="a_ln">121<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_send_protocol_reject(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>,
</div></div></div><div class="div_line"  data-info=({id:114978,ln:122}) id=l122><div class="dl_wrapper"><a name=line122 onclick='overload_click(this)' class="a_ln">122<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;const guint8 *rejected_packet, gsize <a href='ofono/unit/test-sms.c#line814' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:41})'>len</a>);
</div></div></div><div class="div_line"  data-info=({id:114979,ln:123}) id=l123><div class="dl_wrapper"><a name=line123 onclick='overload_click(this)' class="a_ln">123<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_signal_open(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114980,ln:124}) id=l124><div class="dl_wrapper"><a name=line124 onclick='overload_click(this)' class="a_ln">124<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_signal_close(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114981,ln:125}) id=l125><div class="dl_wrapper"><a name=line125 onclick='overload_click(this)' class="a_ln">125<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_signal_up(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><div class="div_line"  data-info=({id:114982,ln:126}) id=l126><div class="dl_wrapper"><a name=line126 onclick='overload_click(this)' class="a_ln">126<span class="glyphicon glyphicon-pencil"></span></a><div class="div_line_contents">void pppcp_signal_down(struct <a href='ofono/gatchat/ppp_cp.c#line172' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:2})'>pppcp_data</a> *<a href='ofono/unit/test-stkutil.c#line11946' class='a_code_tag multi_def' data-info='({type:"glref",tagreg:10})'>data</a>);
</div></div></div><script>var local_symbol_set='([{name:"PPPCP_CODE_TYPE_CODE_REJECT",ln:45},{name:"PPPCP_CODE_TYPE_CONFIGURE_ACK",ln:40},{name:"PPPCP_CODE_TYPE_CONFIGURE_NAK",ln:41},{name:"PPPCP_CODE_TYPE_CONFIGURE_REJECT",ln:42},{name:"PPPCP_CODE_TYPE_CONFIGURE_REQUEST",ln:39},{name:"PPPCP_CODE_TYPE_DISCARD_REQUEST",ln:49},{name:"PPPCP_CODE_TYPE_ECHO_REPLY",ln:48},{name:"PPPCP_CODE_TYPE_ECHO_REQUEST",ln:47},{name:"PPPCP_CODE_TYPE_PROTOCOL_REJECT",ln:46},{name:"PPPCP_CODE_TYPE_TERMINATE_ACK",ln:44},{name:"PPPCP_CODE_TYPE_TERMINATE_REQUEST",ln:43},{name:"RCR_ACCEPT",ln:33},{name:"RCR_NAK",ln:35},{name:"RCR_REJECT",ln:34},{name:"code",ln:53},{name:"data",ln:29},{name:"data",ln:56},{name:"identifier",ln:54},{name:"len",ln:64},{name:"length",ln:28},{name:"length",ln:55},{name:"max",ln:60},{name:"name",ln:70},{name:"option_data",ln:65},{name:"pdata",ln:62},{name:"pos",ln:61},{name:"ppp_option",ln:26},{name:"ppp_option_iter",ln:59},{name:"pppcp_code",ln:38},{name:"pppcp_packet",ln:52},{name:"pppcp_proto",ln:68},{name:"proto",ln:69},{name:"rca",ln:77},{name:"rcn_nak",ln:84},{name:"rcn_rej",ln:86},{name:"rcr",ln:94},{name:"rcr_result",ln:32},{name:"supported_codes",ln:71},{name:"this_layer_down",ln:73},{name:"this_layer_finished",ln:75},{name:"this_layer_started",ln:74},{name:"this_layer_up",ln:72},{name:"type",ln:27},{name:"type",ln:63},])';
var file_info = '({folder:0,project:"ofono1_15", table:"comments", topdir:"ofono_1_15", path:"ofono/gatchat/ppp_cp.h"})';
</script>